/** Auto-generated by scripts/optimize-images.mjs — do not edit */

export type ImageManifestEntry = {
  width: number
  height: number
  blurDataURL: string
  avifSrcSet: string
  webpSrcSet: string
}

export const imageManifest: Record<string, ImageManifestEntry> = {
  "/images/111/mess-internal-0006.jpg": {
    "width": 1600,
    "height": 1066,
    "blurDataURL": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAAAwAgCdASoQAAsAA4BaJbAC7AD2Oa3pFp5qwAD+heilH7xeq0iAUigfQ7eDuarRivgtWwsBbw6VA0Ij9Tlc/vGxXKxarIGO7WYGC9WoRbggZBZJtxKwbqpJT3nAJrN95JQ4wfW3u6gAAA==",
    "avifSrcSet": "/images/111/mess-internal-0006--w480.avif 480w, /images/111/mess-internal-0006--w768.avif 768w, /images/111/mess-internal-0006--w1200.avif 1200w, /images/111/mess-internal-0006--w1600.avif 1600w",
    "webpSrcSet": "/images/111/mess-internal-0006--w480.webp 480w, /images/111/mess-internal-0006--w768.webp 768w, /images/111/mess-internal-0006--w1200.webp 1200w, /images/111/mess-internal-0006--w1600.webp 1600w"
  },
  "/images/111/mess-internal-0007.jpg": {
    "width": 768,
    "height": 1153,
    "blurDataURL": "data:image/webp;base64,UklGRvAAAABXRUJQVlA4IOQAAABQBACdASoQABgAPu1iqU2ppaOiMAgBMB2JbACdMoAlsRG/DG5YDGTksp6AAP64QOEMvcLyL2G8MNwgKYjhr6/q9CnfF3Gs458S+atUw13IaPMgY3MqsAv+mXGPHAR9cEkQ3yPHJe6Jt8bgn+crMSaZr/Z9p5Av5pw5ByJ+O2ulTRz00Pn7u2jm0H/DiQ+9eREh7KTKn9KRLvoRm3axyvzqN8Inc80Ummyi/49lFffpvoK3GaduRIOnJOzBplzwNfxO58/12B5aC7wuA//qlmq+Q+RuV2wqBDT341ChfpiCxzoAAAA=",
    "avifSrcSet": "/images/111/mess-internal-0007--w480.avif 480w, /images/111/mess-internal-0007--w768.avif 768w",
    "webpSrcSet": "/images/111/mess-internal-0007--w480.webp 480w, /images/111/mess-internal-0007--w768.webp 768w"
  },
  "/images/111/mess-internal-0009.jpg": {
    "width": 1600,
    "height": 1066,
    "blurDataURL": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAADwAQCdASoQAAsAA4BaJbACdAEOua2kQ4AA/sYCctzX0va4JzQgxDDzRIZ59Y83KnaLJ7iOd1yl28vgP9ZbaoAnwK3+lbrZuD++t+LGeCjA+ydTIPTnLDVG2Yy0AA==",
    "avifSrcSet": "/images/111/mess-internal-0009--w480.avif 480w, /images/111/mess-internal-0009--w768.avif 768w, /images/111/mess-internal-0009--w1200.avif 1200w, /images/111/mess-internal-0009--w1600.avif 1600w",
    "webpSrcSet": "/images/111/mess-internal-0009--w480.webp 480w, /images/111/mess-internal-0009--w768.webp 768w, /images/111/mess-internal-0009--w1200.webp 1200w, /images/111/mess-internal-0009--w1600.webp 1600w"
  },
  "/images/111/mess-internal-0016.jpg": {
    "width": 1600,
    "height": 2400,
    "blurDataURL": "data:image/webp;base64,UklGRu4AAABXRUJQVlA4IOIAAAAwBACdASoQABgAPu1iqU2ppaQiMAgBMB2JbACdMoAlsRGs1s3sueVqx3wA/rhA4Qy9wvIvYbww3KQXpOZJNhOr0KZU4R9NL8O0s0M4kObnKK305UM/ZVjMd7NMasr2DLlISPKS8yj/Gbwx2FIJAqITlFHFELigm4z7EWUuP0PiVQBcwovVje8x04Qor25SLMJOwWtjULL1UUP+W1tE+F73DoZ54fmikzTeexLdUVlvj/d+sKIGANjotbERgcf43f4nc+f67A8sxqICL/8pZqvkPkbldsKgQ2xCghBX2pTkC4AA",
    "avifSrcSet": "/images/111/mess-internal-0016--w480.avif 480w, /images/111/mess-internal-0016--w768.avif 768w, /images/111/mess-internal-0016--w1200.avif 1200w, /images/111/mess-internal-0016--w1600.avif 1600w",
    "webpSrcSet": "/images/111/mess-internal-0016--w480.webp 480w, /images/111/mess-internal-0016--w768.webp 768w, /images/111/mess-internal-0016--w1200.webp 1200w, /images/111/mess-internal-0016--w1600.webp 1600w"
  },
  "/images/111/mess-internal-0030.jpg": {
    "width": 1600,
    "height": 2400,
    "blurDataURL": "data:image/webp;base64,UklGRqwAAABXRUJQVlA4IKAAAABQBACdASoQABgAPu1iqU2ppaOiMAgBMB2JZgCdAYxY1f/VYW85DRcSwLuMAP7URKh+dMbcY7tYixXn89iOP+yc47Ay01iO2bXuELj2uC4DY5JgihECo55Vsf1/yMxBk3mHs4bXZLLChZ2AxA6WlMfC6D8sI5ZDR+QWdxIC60TnUBtsUdAXsBFQDSx7RTbmxejonWLjMGyGI9LGkSK9oAAA",
    "avifSrcSet": "/images/111/mess-internal-0030--w480.avif 480w, /images/111/mess-internal-0030--w768.avif 768w, /images/111/mess-internal-0030--w1200.avif 1200w, /images/111/mess-internal-0030--w1600.avif 1600w",
    "webpSrcSet": "/images/111/mess-internal-0030--w480.webp 480w, /images/111/mess-internal-0030--w768.webp 768w, /images/111/mess-internal-0030--w1200.webp 1200w, /images/111/mess-internal-0030--w1600.webp 1600w"
  },
  "/images/111/mess-internal-0034.jpg": {
    "width": 1600,
    "height": 2133,
    "blurDataURL": "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAAAQBACdASoQABUAPu1iqk2ppaQiMAgBMB2JbACdH8ADAp5PJaFe0DTLAAD+3qrTVIZRnflRTJ5Xc3jzlShgD2+WCMSFVOGPWzeEH/Zp6UVRI3B/uFVr3/WfU+GMrWpHUTTcEDCG4IW2HmyJXcymEAAA",
    "avifSrcSet": "/images/111/mess-internal-0034--w480.avif 480w, /images/111/mess-internal-0034--w768.avif 768w, /images/111/mess-internal-0034--w1200.avif 1200w, /images/111/mess-internal-0034--w1600.avif 1600w",
    "webpSrcSet": "/images/111/mess-internal-0034--w480.webp 480w, /images/111/mess-internal-0034--w768.webp 768w, /images/111/mess-internal-0034--w1200.webp 1200w, /images/111/mess-internal-0034--w1600.webp 1600w"
  },
  "/images/about-1.jpg": {
    "width": 1066,
    "height": 1600,
    "blurDataURL": "data:image/webp;base64,UklGRrwAAABXRUJQVlA4ILAAAACQBACdASoQABgAPu1iqU2ppaOiMAgBMB2JaACdIExgvhfuhjPpWi70RN6jogAA/ni24GSgoOOrJ7CctTbB24F26tAPqLtCM5SeIGzUhBdYlb47n+UCc7pzQdHXVUIa441FG2KxmZ5NwpFruv3+3G21V/lv7zdlMJhXU11g3ptKwmhP1QKxtrlJteP2t56MMxSHeK0uv7+OCKJlSAKeoJj7hQPKo5TOJITMNBwyd7AAAA==",
    "avifSrcSet": "/images/about-1--w480.avif 480w, /images/about-1--w768.avif 768w, /images/about-1--w1066.avif 1066w",
    "webpSrcSet": "/images/about-1--w480.webp 480w, /images/about-1--w768.webp 768w, /images/about-1--w1066.webp 1066w"
  },
  "/images/about-2.jpg": {
    "width": 1600,
    "height": 1066,
    "blurDataURL": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAABQAgCdASoQAAsAA4BaJaACdAYt9qvVMfoKOgAA/uzk0kjAyFleEVkT+2sYej+wHp+sCUvFgVpu8R7tfpllOoQRx1276E34qmfme62UzidJ36Gf+uj3AG1MMpBAEAZz+1AAAA==",
    "avifSrcSet": "/images/about-2--w480.avif 480w, /images/about-2--w768.avif 768w, /images/about-2--w1200.avif 1200w, /images/about-2--w1600.avif 1600w",
    "webpSrcSet": "/images/about-2--w480.webp 480w, /images/about-2--w768.webp 768w, /images/about-2--w1200.webp 1200w, /images/about-2--w1600.webp 1600w"
  },
  "/images/about-3.jpg": {
    "width": 1066,
    "height": 1600,
    "blurDataURL": "data:image/webp;base64,UklGRvAAAABXRUJQVlA4IOQAAABwBACdASoQABgAPu1iqU2ppaQiMAgBMB2JbACdMoAlrxG+rmEEBDc5DMCXmAD+uEDhC7xS8iuqMjDYpBek5kjne6Kr+tmHytwGNs6GIgrq13hMatb4xi58I5bBCFR5V9LCdrr5VKeMIyfl1iTblTR/NZZd0dbQVSGfHQxvMCS4/GdFdtEMTpE/Pj0APX6HKwZB0YlraBmOgj2tVrywq6fWemT9pfAnmjrwC41r25nAt6Tt1OWDmhlcnMiwkfOb43f4nc+f67A8sxqICL/8pZqvkPkbldrYmz2UMZw634gw7DmAAAA=",
    "avifSrcSet": "/images/about-3--w480.avif 480w, /images/about-3--w768.avif 768w, /images/about-3--w1066.avif 1066w",
    "webpSrcSet": "/images/about-3--w480.webp 480w, /images/about-3--w768.webp 768w, /images/about-3--w1066.webp 1066w"
  },
  "/images/about-4.jpg": {
    "width": 480,
    "height": 319,
    "blurDataURL": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAAAQAgCdASoQAAoAA4BaJbACdAD5NIwchlwAAP7eAUlvAH2z8pNL1exJra3rnKNKogSt+AjHu/l18OpbvKp43zjXnhrerFUXR7rtia5blnHIzDj975vpyJuPXdSbswsovAAAAA==",
    "avifSrcSet": "/images/about-4--w480.avif 480w",
    "webpSrcSet": "/images/about-4--w480.webp 480w"
  },
  "/images/blog/placeholder.jpg": {
    "width": 1200,
    "height": 900,
    "blurDataURL": "data:image/webp;base64,UklGRioAAABXRUJQVlA4IB4AAABwAQCdASoQAAwAA4BaJYwCdAFAAAD+8bjxdPkQAAA=",
    "avifSrcSet": "/images/blog/placeholder--w480.avif 480w, /images/blog/placeholder--w768.avif 768w, /images/blog/placeholder--w1200.avif 1200w",
    "webpSrcSet": "/images/blog/placeholder--w480.webp 480w, /images/blog/placeholder--w768.webp 768w, /images/blog/placeholder--w1200.webp 1200w"
  },
  "/images/decor/photo/banana-leaf.png": {
    "width": 1280,
    "height": 785,
    "blurDataURL": "data:image/webp;base64,UklGRkgBAABXRUJQVlA4WAoAAAAQAAAADwAACQAAQUxQSJAAAAABgGJt27LoeT9ckrtr+xNOJxOpHJpHmjsbYAGsQGeWYKuY6u7yju4hIiYA/ws5pLs2SPwhZITiGc8BEiTkguBe8geXEIyBQAhML/mV10HZ4tSlj1dWD/z5wgdpLcpvj1cfzJ8vb3yc0xFg6H3w6/PHJ+9LagKEITq64k8+aZkEAYDaL+WrzYINhH+VcgAg/AlWUDggkgAAAHACAJ0BKhAACgADgFolsAJ0MEdIiQlDCWLZneAA/uhPDYhv1i/MW9r3zrIvu6jzmZ5TejB3pmx+lx+XhDOeST0O0qFH2ExY39/ej1gtz8i3aMXXQ6SjDixFC/v/24rYPIxc3KLhTpDAlHMkL7f0j/7z5lO+1TSew09/2PV+1Gkx+d2svj/+CEyUcw8TOBhwAAAA",
    "avifSrcSet": "/images/decor/photo/banana-leaf--w480.avif 480w, /images/decor/photo/banana-leaf--w768.avif 768w, /images/decor/photo/banana-leaf--w1200.avif 1200w, /images/decor/photo/banana-leaf--w1280.avif 1280w",
    "webpSrcSet": "/images/decor/photo/banana-leaf--w480.webp 480w, /images/decor/photo/banana-leaf--w768.webp 768w, /images/decor/photo/banana-leaf--w1200.webp 1200w, /images/decor/photo/banana-leaf--w1280.webp 1280w"
  },
  "/images/decor/photo/fan-palm.png": {
    "width": 1063,
    "height": 1280,
    "blurDataURL": "data:image/webp;base64,UklGRqYBAABXRUJQVlA4WAoAAAAQAAAADwAAEgAAQUxQSP8AAAAFgGVb2/HmeT/8SWrbtm23V7pvJ9gR2LZt29YXJ1OIiAkAyOijBfy/0PvbNxkBuLDM6zjxceN6oh0DxFjhb7gu+H+Fvb5vurwYE69Soz2MKT/zf6IrZvWHWPtok8E7gi18b30d01uk4a5jpZlHeEzeHDwaxcBRXdhuqXuZCllavfq+6eW+jxn1v9H5EXQwezq+V75DCV+iKis252dvbFB5D+3fwT/Ct7ItGaudD9fb39cU4u7i691Y+ni7u3JBFztGIsgwrxd5E+2lpt4J4K5efxc+YStMCaMyAlL/ZoRf2JL4g32m/MIXmXKAjM55xc6T0QFAy5xXcJSMBWsfNgAAVlA4IIAAAAAQBACdASoQABMAPu1iqU2ppaOiMAgBMB2JbACdDiAByezqbHKRfPX3BAD+2YJyn5dXaBMitYP5DPZ3HUWRLK/OknA7R73jIxeMMTUSa7jCZX5MGhfGzaREuEvyqJoFh6W2Dbn0wvRrpW/266o8FKb8CwZRQT5LVvFpzYx8YxrgAA==",
    "avifSrcSet": "/images/decor/photo/fan-palm--w480.avif 480w, /images/decor/photo/fan-palm--w768.avif 768w, /images/decor/photo/fan-palm--w1063.avif 1063w",
    "webpSrcSet": "/images/decor/photo/fan-palm--w480.webp 480w, /images/decor/photo/fan-palm--w768.webp 768w, /images/decor/photo/fan-palm--w1063.webp 1063w"
  },
  "/images/decor/photo/fern.png": {
    "width": 868,
    "height": 1280,
    "blurDataURL": "data:image/webp;base64,UklGRkACAABXRUJQVlA4WAoAAAAQAAAADwAAFwAAQUxQSIEBAAAAAAAAAAAAAwATZgIAAAAAAAAAAQEAAQAHnHoABAAAAAAAAQACBw1LjM57FAAIAQAAAAANLGmUmoaln4lSEwACAAIRNmR/lKyGir29g08hAAADKGyUjpupf5adeoaMRCMGC0V3h4mQqn+Yn52biWcYABk6VnCIlp91pbWgpZx4NAscZ4OUjZKTd6ubkJaejk4WRY6Tm5WUmXqtqb6/sYgvAw4wR2F4o6B/rJqPhHl8PQsndJWnoa2Nbaamoa6bmHEiAUaTsLWnlXzBvpOFcWA6HDJZSV5+kJh4sbG+u7JxHQAAGn2onqOseKuqqLO9n0AHH4VXSZKpr4GLtKaqo4lpJiEWb6XCuqyQgK6or6eTRRYAIkecmpCurXmrqqGsomscAQNahpKzpZd9mcrDv59CDAAJFkKGqHypeoC2lmNfNwYAAAAKamTDnJtxhMNvBwABAAEADiTFXb9hPhQQQicAAQAAAgBINmGKAAICAAAAAAAAAAABCQM+CQACAAECAQAAAFZQOCCYAAAAkAMAnQEqEAAYAD7tYqlNqaWjojAIATAdiWwAnQwVEiETVGA50AD+R+6ttiI2tBPj+vAlmuQXzI+sEsEqeKJWSRi/oDlrTiMRRQz73/xzuf4tvnSZ+qW5VV9Sf3frt/jhT/xbkF+wyz5WVSh2/Jki0OsTi2veDCJyV8oiltyGqGn8Kfe9UihBgwyujE5bBHeW5jEVjjB0QAA=",
    "avifSrcSet": "/images/decor/photo/fern--w480.avif 480w, /images/decor/photo/fern--w768.avif 768w, /images/decor/photo/fern--w868.avif 868w",
    "webpSrcSet": "/images/decor/photo/fern--w480.webp 480w, /images/decor/photo/fern--w768.webp 768w, /images/decor/photo/fern--w868.webp 868w"
  },
  "/images/decor/photo/leaf-cluster-border.png": {
    "width": 1280,
    "height": 640,
    "blurDataURL": "data:image/webp;base64,UklGRgABAABXRUJQVlA4WAoAAAAQAAAADwAABwAAQUxQSIEAAAAAAgABAAEAAwUAAQABAAEAAAQAQp8sAFZjFgEABjVkdhBwuaX/0xZ3inIlAGq9tN9n9PDA5MIlUIuJQRW5wdXDrNGozNLUOD+slXAvu9/uyLw5z7jt3RYWoJ9YFqHg7MpgB1h/6ZMAACRaHQAqRGRYBAIBAgQEAAAABwIAAAIBAAAAVlA4IFgAAAAwAgCdASoQAAgAA4BaJbACdLoAApve4a7zYAD+7Nuo08Y40PtPpxErdS7zrBGcU3OAPIMXGDRlOnSDfR2OLDb/z39gHpKZiT69rXfq0XviSPZzQMRpKegA",
    "avifSrcSet": "/images/decor/photo/leaf-cluster-border--w480.avif 480w, /images/decor/photo/leaf-cluster-border--w768.avif 768w, /images/decor/photo/leaf-cluster-border--w1200.avif 1200w, /images/decor/photo/leaf-cluster-border--w1280.avif 1280w",
    "webpSrcSet": "/images/decor/photo/leaf-cluster-border--w480.webp 480w, /images/decor/photo/leaf-cluster-border--w768.webp 768w, /images/decor/photo/leaf-cluster-border--w1200.webp 1200w, /images/decor/photo/leaf-cluster-border--w1280.webp 1280w"
  },
  "/images/decor/photo/monstera-1.png": {
    "width": 1280,
    "height": 1280,
    "blurDataURL": "data:image/webp;base64,UklGRjQBAABXRUJQVlA4WAoAAAAQAAAADwAADwAAQUxQSIkAAAABgJpt27Lsfl5colaXDUi6gztkWIAVoBHpFt2dRiX97u478HzHP0JETAD+V2MHSSHoyypIszSKWhAn4Hu78kJwclRfS3oQJxDpbDMQHFDsPzXAE4yHz4EXJEG3+FpU7CDOUO6ePYUhOyXg6exuJ16IUwRlc3+sgcAKeOp3f3HIGBDsfrsVxIEIPABWUDgghAAAAHACAJ0BKhAAEAADgFolsAJ0fwPZLIgssc4Q3FAA/tFBkiAlBJV8XjDsuCQcbUKusQGW26VuVENeD8EgO/i+d1vWEYHgW3e1Hk+STR6dsYVxNILh4wcw/0X1XQvVfXTVgfnVm6RWhMipcGu6Jy3EBrBkcyx8C0doAYyPBIq+JVNnXAAAAA==",
    "avifSrcSet": "/images/decor/photo/monstera-1--w480.avif 480w, /images/decor/photo/monstera-1--w768.avif 768w, /images/decor/photo/monstera-1--w1200.avif 1200w, /images/decor/photo/monstera-1--w1280.avif 1280w",
    "webpSrcSet": "/images/decor/photo/monstera-1--w480.webp 480w, /images/decor/photo/monstera-1--w768.webp 768w, /images/decor/photo/monstera-1--w1200.webp 1200w, /images/decor/photo/monstera-1--w1280.webp 1280w"
  },
  "/images/decor/photo/monstera-2.png": {
    "width": 1037,
    "height": 1280,
    "blurDataURL": "data:image/webp;base64,UklGRuABAABXRUJQVlA4WAoAAAAQAAAADwAAEwAAQUxQSAUBAAABkGvb2rFX+0PsVDYrO6lsu3JvVelyBU6VKsfsbJuVbVvv+z776CIiYgIAwHJsWPDfzpsNACwHFmJ6PYepKa2AhYCKqBXefEpRPGnBf+4hP3+jEVL40sUQjfDjUyojmnddjFJpXk+8QaHmuouSD0r4scFn9cZn8yYXdZsOvqXhp+hSb9+kUDQYCilaL/R0pMGyzvOnUbu/UfhA/aiB/U1E8dyeK1SieAb4QuGTY/1LVMbwVQyOUK/VhhQdoNDwYSiCs9MxfubGD5Ka87ABB/NUQgp3B8OybA+UUguFb2NhA7AQ9oFCw1s++NcCjlBTcyfsf+BilpqKM3D+YyFs/3fzYV88bAAAVlA4ILQAAACwBACdASoQABQAPu1iqU2ppaOiMAgBMB2JbACdMoMjkgzyQAehAPhnVt3dhJAAAP04x9OFLl+be1kR77BSGPfTybk2iDtm0jUZ5SEjc61So3eCJsgruFyIgx0qvUYMTpJg7BEMBqgBdQCuS3oeqrfpaFXP5aLoChaIi2XxK2bvHNUtlT1p0d34yPIDnb+q3bjGGaLcRO7L+6sluCBeHUxT9DNuORrv5Lq1tU1uWfyXVsTgAAA=",
    "avifSrcSet": "/images/decor/photo/monstera-2--w480.avif 480w, /images/decor/photo/monstera-2--w768.avif 768w, /images/decor/photo/monstera-2--w1037.avif 1037w",
    "webpSrcSet": "/images/decor/photo/monstera-2--w480.webp 480w, /images/decor/photo/monstera-2--w768.webp 768w, /images/decor/photo/monstera-2--w1037.webp 1037w"
  },
  "/images/decor/photo/monstera-3.png": {
    "width": 1000,
    "height": 780,
    "blurDataURL": "data:image/webp;base64,UklGRmwBAABXRUJQVlA4WAoAAAAQAAAADwAACwAAQUxQSLkAAAABgGrb1rFtn+f9/Kva9iWY8f++/NtMtm3bdrJt28h/MuN3ExGRAIjBJlQAFQUAIMQOVkmDWhxVVtzBAIbkm/Gukfio7hZ/YpB7Zo52Rk9XtPmCEUAcDf3PrT0f/LZm2oDAYP/1fPb28TqQP3ZhCwbZcE7XwcPmzfxyaJQOoLfQUNUYVdh/NLEuAwM8XnZq7ZHSPD9S3mUEAmeqyjjEVflH+2bEc5ATH24LUpiXnAYCIAJBPV4ICCytAABWUDggjAAAADACAJ0BKhAADAADgFolsAJ0ME5Ihkj6qdGAAPwbdlQa93U0s8Ojkz7cXWz7LjTp5y4ozzPkk+Shh++h+ntDsZ3eNqgDb1Ob+2h5wUC5pjE/+djQkFEvfNl/MzCkW5mIc8+2cAfmoJDRcfuyjEQfnWcvnD7vdEnCPy65emPHVNP8k9wJ8/89+NGL+AAA",
    "avifSrcSet": "/images/decor/photo/monstera-3--w480.avif 480w, /images/decor/photo/monstera-3--w768.avif 768w, /images/decor/photo/monstera-3--w1000.avif 1000w",
    "webpSrcSet": "/images/decor/photo/monstera-3--w480.webp 480w, /images/decor/photo/monstera-3--w768.webp 768w, /images/decor/photo/monstera-3--w1000.webp 1000w"
  },
  "/images/decor/photo/monstera-upright.png": {
    "width": 815,
    "height": 1280,
    "blurDataURL": "data:image/webp;base64,UklGRhICAABXRUJQVlA4WAoAAAAQAAAADwAAGAAAQUxQSCwBAAABkHNru2m78t+19kVnVTZidza7VHZSpbLtpHdp204627atfddaT5yImABJ1qjuxuNDU2SNJEWqu/07not1FBkpUpt3eOe+s6K8WMYqe05wARwje52yUvru3o8JEGg6ii7Schosx+G5l3eWnmoZM74+ITg2duNBjtrD85w5uMC1M8QtNYIvnCjahydw6NtKbXi1He5dJXhWteCkzrJ4DQ48xzSEHXrI5xHbcHg2TIjv9WlyEz5NvYQHz7HUJatXEofvX4DADE3i5FBc8BAcH+afgotlnwj8HoBvbNROHI71W3Eu5lm52nofU1tTXhu+86aNrObjWJer/nCjjiIpeej8Ds1KZYZta65IkpFRdV0lSMbqt4RElTWTjSKrPxtVtVWkfzSq7vg/pV1k/wRWUDggwAAAABAFAJ0BKhAAGQA+7WKpTamlo6IwCAEwHYlsAJ0vXUAA3iKuQqC4XdzXNf6EHb1srpgA/qKsZBF7+R043s0petQ+DapEE+DZ0GewciUSUHe8UCom+vlqHhEQ6vkYJ7e9Vgg2/EetYgF8CdXo/Av073n3AxKooOFwGXZpHjVc4zXT7iSixjutXJP7ceuP9ueVPtOqDzOQgWR29P3R5btcMwG9LZ8+JOmsgp9pI+LFw1v2JQ5TuH+R8GeQ7X5GT90AAA==",
    "avifSrcSet": "/images/decor/photo/monstera-upright--w480.avif 480w, /images/decor/photo/monstera-upright--w768.avif 768w, /images/decor/photo/monstera-upright--w815.avif 815w",
    "webpSrcSet": "/images/decor/photo/monstera-upright--w480.webp 480w, /images/decor/photo/monstera-upright--w768.webp 768w, /images/decor/photo/monstera-upright--w815.webp 815w"
  },
  "/images/decor/photo/monstera-vine.png": {
    "width": 1273,
    "height": 1280,
    "blurDataURL": "data:image/webp;base64,UklGRnQBAABXRUJQVlA4WAoAAAAQAAAADwAADwAAQUxQSOMAAAABkGvb1rFn+0VwA7ZZ2eqSLqVR2qlso3JKqzMrJ5Vt207e73ve8/MeImIC8G8Oxg3JEHn8m0cAI5Yjgv+fl1KhpGkdADwHDlHqhaSQ3/o0wHHg1NA5pN9L7yk3ixCN1CEg8vRoSn5cv3+G3e1+X3N65mT5FCkZPWutESMiSf6WaMN76rOCJKZUSIzGqmv9YHW+TTIRMYlqIAjwe38iRiQziYpgZYxciiYm0UvGFdnn0Zn/xDvC3ojO1JwD0UiPGfKDANeO+Vjw4CyaPxY+HyHgb0FEUMsh7ScBPA8eAMTk1dc8DgBWUDggagAAADACAJ0BKhAAEAADgFolsAJ0BiyNrfZvs3sAAP7xSd7f0ZYi9QGyANXcdQROfCWF6Qe5lA4jE9qvY2IbvqIL0W36WXowGfIERirIEmtslp/t18L3IBPtFlylj0gta7ZvtcMf7MM3HXWgAAA=",
    "avifSrcSet": "/images/decor/photo/monstera-vine--w480.avif 480w, /images/decor/photo/monstera-vine--w768.avif 768w, /images/decor/photo/monstera-vine--w1200.avif 1200w, /images/decor/photo/monstera-vine--w1273.avif 1273w",
    "webpSrcSet": "/images/decor/photo/monstera-vine--w480.webp 480w, /images/decor/photo/monstera-vine--w768.webp 768w, /images/decor/photo/monstera-vine--w1200.webp 1200w, /images/decor/photo/monstera-vine--w1273.webp 1273w"
  },
  "/images/decor/photo/palm-cluster.png": {
    "width": 1280,
    "height": 641,
    "blurDataURL": "data:image/webp;base64,UklGRigBAABXRUJQVlA4WAoAAAAQAAAADwAABwAAQUxQSHgAAAABgJtt2/HsfhGzstGZnbNABrAGyARpkz2MATSJe3b87X+HiEj8Y4QIlTL8IQTgGlc4mYqaAELAzNnWdHd/3ndiIATe9vLz4/OyaGaUIBA1Dp+fp0k9YDaZGIV+8XkelM1iodpsUwOa8TxnZCCccYmMAW4/Bygl+AdWUDggigAAADACAJ0BKhAACAADgFolsAJ0BiomYAXSkrAAAP7U67t20NvTcRdecdMeYkZWQhUuHoJz38t+HVXaBkjx5hMXCKHY7u3mfHZNqY0Folyh2nHrwaf8QNe6tws5hKB9HtRxD642sEhx2TBWPfo5ea3ph2xXvVdcczWTgvThuXnd8tcTd+W7T+J9vgAAAA==",
    "avifSrcSet": "/images/decor/photo/palm-cluster--w480.avif 480w, /images/decor/photo/palm-cluster--w768.avif 768w, /images/decor/photo/palm-cluster--w1200.avif 1200w, /images/decor/photo/palm-cluster--w1280.avif 1280w",
    "webpSrcSet": "/images/decor/photo/palm-cluster--w480.webp 480w, /images/decor/photo/palm-cluster--w768.webp 768w, /images/decor/photo/palm-cluster--w1200.webp 1200w, /images/decor/photo/palm-cluster--w1280.webp 1280w"
  },
  "/images/decor/photo/palm-frond.png": {
    "width": 1280,
    "height": 914,
    "blurDataURL": "data:image/webp;base64,UklGRvYAAABXRUJQVlA4WAoAAAAQAAAADwAACgAAQUxQSJQAAAABgJpt27Ll/q1p/PdQksMEMAAHCWawCTTy07S6pb/h7s2Tu8P7Phe6Q0RMgBQIKtx3ekPvzEahNqWAkkONs3ieHcZ+QPEiz9cY5t0Hi0GVPJvj708KShc38PbPS716+OBv84xGw8u4f3BMqeIAM8CMhzNq1M6H/ca5z7a6iJbg7hX87ofRrJAGly9HunmhqWG4VGEJVlA4IDwAAACwAQCdASoQAAsAA4BaJbAAAp2fuvloAP7zMGUJKxfQGf3CRJdpJsLKwq5Vw/tp6EF//taU93Z50hQkAAA=",
    "avifSrcSet": "/images/decor/photo/palm-frond--w480.avif 480w, /images/decor/photo/palm-frond--w768.avif 768w, /images/decor/photo/palm-frond--w1200.avif 1200w, /images/decor/photo/palm-frond--w1280.avif 1280w",
    "webpSrcSet": "/images/decor/photo/palm-frond--w480.webp 480w, /images/decor/photo/palm-frond--w768.webp 768w, /images/decor/photo/palm-frond--w1200.webp 1200w, /images/decor/photo/palm-frond--w1280.webp 1280w"
  },
  "/images/decor/photo/split-leaf-1.png": {
    "width": 1280,
    "height": 1186,
    "blurDataURL": "data:image/webp;base64,UklGRlABAABXRUJQVlA4WAoAAAAQAAAADwAADgAAQUxQSNUAAAABgLNt2/lV/vPPrpGTNv2a2mxMNdr21n/LrtmuSd/Atm3b7vd73nv6R0SSSofMGypJ8vD2syAVqbTJ6wpSOBRGFGkTmajP8GVcDpmxaEwq2+WvKfxZFOFfyCglrVnc9wEekVAg8OlEv/gvuEFbMADIqKcfRnILvk8AKP+opn2gW1IgwCzQb2CcCfHr2AgZwGwIOTRbDgHdhZAxK5Fd0ePzlPseFIAxpV5g4BczDWABDa7/wJ/CzCxfr0+0xruFVEEAYOylRIQl1q5NDh9o7OxePt3/5AEAVlA4IFQAAABQAgCdASoQAA8AA4BaJbACdLoAAzqVjtnrUIAA88z0Po83jfz5YnZO5jRz6ndJz7p62982X3RKM2xJ8VXh7K3jyXU5g8DRr8yOLRpfN1OQKrJaAAA=",
    "avifSrcSet": "/images/decor/photo/split-leaf-1--w480.avif 480w, /images/decor/photo/split-leaf-1--w768.avif 768w, /images/decor/photo/split-leaf-1--w1200.avif 1200w, /images/decor/photo/split-leaf-1--w1280.avif 1280w",
    "webpSrcSet": "/images/decor/photo/split-leaf-1--w480.webp 480w, /images/decor/photo/split-leaf-1--w768.webp 768w, /images/decor/photo/split-leaf-1--w1200.webp 1200w, /images/decor/photo/split-leaf-1--w1280.webp 1280w"
  },
  "/images/decor/photo/split-leaf-2.png": {
    "width": 1179,
    "height": 1280,
    "blurDataURL": "data:image/webp;base64,UklGRowBAABXRUJQVlA4WAoAAAAQAAAADwAAEAAAQUxQSO4AAAABkKNt27FHb2xtIJV62046Ox0rGwuwbY9t29PZtq3ve59rsImImAALaytl6VMabrHM57KC0RBloUL2/ORHpMdzXkS9epfUuvUH8ptrqhMK537kobUJBjlhMFf5q4xfApgc9HjE9YxHPfwGEUF7zfAr/dw8vwxTQLN2HEo21pki/C+C5uBBH+eotHjfNrQ2BOHlsYkk//iOWxgAwosqTADh7llEeOl2A41wOV9VYgovVcyubSutcW5+G7T8Z6H690yNrdwFQ35/56WligMB8ycfGq7wTFmqYQwQzoQvwktloew3/v74+WGD504+fL8LVlA4IHgAAAAwBACdASoQABEAPu1iqU2ppaOiMAgBMB2JagCdLwABZzQEGU63cXDbeIAA/r3BoQzr88R8ZoTk5gmcjFf1mZsuhjMOe0q6ICythZ9Lykj5sfUonGW3Uoj7hnhDfdhMK0eZWMm2vl9f/oIvFfL6//QRoX8e4coAAAA=",
    "avifSrcSet": "/images/decor/photo/split-leaf-2--w480.avif 480w, /images/decor/photo/split-leaf-2--w768.avif 768w, /images/decor/photo/split-leaf-2--w1179.avif 1179w",
    "webpSrcSet": "/images/decor/photo/split-leaf-2--w480.webp 480w, /images/decor/photo/split-leaf-2--w768.webp 768w, /images/decor/photo/split-leaf-2--w1179.webp 1179w"
  },
  "/images/decor/tropical-leaves.png": {
    "width": 74,
    "height": 441,
    "blurDataURL": "data:image/webp;base64,UklGRvwBAABXRUJQVlA4IPABAADwCQCdASoQAF8APt1cpE2opSOiNUgBEBuJZQDBl6r+7mkJwBbGZWLB3S7swj5jf+Gi9W1wOMWGuTlcv5/ZxINYguHWrHXkAA3dNeINBse9g1vi5OW88UZgAP7sr6VBf55QPYZDc5vxmzcBmgccQ+jC6FLjSPop1M7fh/94VEVWLbNwouH31Gi5ms8WXNYlcPKfBYkYVbSxQfluHH9Kw+9MyzB5GwBAUtmhIPdMf5yJ7RtoyuqUuPWfOJ3c7jbDimfo8o2tKu/FNhzZH8UcSw9wKmT32dg3sQhIhy7fenXFTpm5coJPDK3+K5z1Wf4ONRH4/PoxFtO/Z6MgrwXS5poMg4zEV4r3fX0UV731UdwKUbOv7eh86rNqxR5N0G1gnLNyHTBrOg7zBR8+2aPKP3rzhgVatc07cf9G/GVE6dyTBESkud9ehoFmKG1h3GL1X2bgceogwIDpzpzc6p5fFDNlO2qVTATPIFxAQRfKmJ8g+VlFV4eN8LOGduEuf0D88HqQplhYrOd3lxXTZymErYuJUWywJ/2/7pdGfnMqIn0WI7bz+sDxHAq1Lfdca0b3DrN8V58npxgvfNK2SmKyjD0r7RmMHNRMF01dkM9LwohLxUs1m2ecDrp0M3JmDvgZxbQpSCIxZoCKuO7MUY7BrgAA",
    "avifSrcSet": "/images/decor/tropical-leaves--w74.avif 74w",
    "webpSrcSet": "/images/decor/tropical-leaves--w74.webp 74w"
  },
  "/images/gallery-1.jpg": {
    "width": 1066,
    "height": 1600,
    "blurDataURL": "data:image/webp;base64,UklGRsQAAABXRUJQVlA4ILgAAADwBACdASoQABgAPu1kqU2ppaOiMAgBMB2JbACdMoR3AdDpBwJvrdCJOyQBPAX3goAA/q7F3q8mtlnJOeW1shG8xbPeZ6EAOd3/biZSOX9mB5bXcjeppCAUdwP1zMyYiY4c/uLTS5eomU+r07UiLzWeyb7LE8yfDCbnsr3i07oKZPW4/r22OUsah2HxU5HRJMXSV/z899irkADb+tZQ5b7KJbWLa9rVdq+AH6qkc5obSD5GNPzk8AAA",
    "avifSrcSet": "/images/gallery-1--w480.avif 480w, /images/gallery-1--w768.avif 768w, /images/gallery-1--w1066.avif 1066w",
    "webpSrcSet": "/images/gallery-1--w480.webp 480w, /images/gallery-1--w768.webp 768w, /images/gallery-1--w1066.webp 1066w"
  },
  "/images/gallery-2.jpg": {
    "width": 1066,
    "height": 1600,
    "blurDataURL": "data:image/webp;base64,UklGRrwAAABXRUJQVlA4ILAAAABQBACdASoQABgAPu1iqU2ppaOiMAgBMB2JaACdAYx23vQRwwL3yYwgG95sAP54tuBk7x0RyNg2mWZFZZpcg67BzTcm70GsClLaRZSlX1ESoQVj0n1t5KiAQQXYSl+S0THo+kz/fMd5jc/CheXLYlzJd/TjxYd3t40ADRvmYvssWH2dMZbc3bpU43YT+ZTIAmSdjsir+uJesuxW5SzHba+8kDc9QITEkPNYkZiwr0hkAA==",
    "avifSrcSet": "/images/gallery-2--w480.avif 480w, /images/gallery-2--w768.avif 768w, /images/gallery-2--w1066.avif 1066w",
    "webpSrcSet": "/images/gallery-2--w480.webp 480w, /images/gallery-2--w768.webp 768w, /images/gallery-2--w1066.webp 1066w"
  },
  "/images/gallery-3.jpg": {
    "width": 1199,
    "height": 1600,
    "blurDataURL": "data:image/webp;base64,UklGRpwAAABXRUJQVlA4IJAAAABQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JbACdMoAluxFilQm82nPiefCAAPliJzBg1LDxLxW7rSPyKrgjHomckE/Y9uZbx4g5EMtVndtnxwTN+sSwnAD7F8d0wQ2jYES+ITorKzT7Gpm2GF/hh6Y1dYoiL20ZrwuxuNVhtuGxKpFfpN7rybu8x7Jp1/wkAAA=",
    "avifSrcSet": "/images/gallery-3--w480.avif 480w, /images/gallery-3--w768.avif 768w, /images/gallery-3--w1199.avif 1199w",
    "webpSrcSet": "/images/gallery-3--w480.webp 480w, /images/gallery-3--w768.webp 768w, /images/gallery-3--w1199.webp 1199w"
  },
  "/images/gallery-4.jpg": {
    "width": 1600,
    "height": 1066,
    "blurDataURL": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAAAwAgCdASoQAAsAA4BaJaACdAEDW7UzdI1fSAD+7OTVV3o5zoUtcsJFouNh3WFwdRBt2CecVEJ55pY/Ll8txbh43UahBOq/sfy8Dgc/43PtRjvx8KABMfRUIIAt7MZWuAA=",
    "avifSrcSet": "/images/gallery-4--w480.avif 480w, /images/gallery-4--w768.avif 768w, /images/gallery-4--w1200.avif 1200w, /images/gallery-4--w1600.avif 1600w",
    "webpSrcSet": "/images/gallery-4--w480.webp 480w, /images/gallery-4--w768.webp 768w, /images/gallery-4--w1200.webp 1200w, /images/gallery-4--w1600.webp 1600w"
  },
  "/images/gallery-5.jpg": {
    "width": 1066,
    "height": 1600,
    "blurDataURL": "data:image/webp;base64,UklGRrAAAABXRUJQVlA4IKQAAACQBACdASoQABgAPu1iqU2ppaQiMAgBMB2JZgCdAYxs1Zds7upW+FjIGFm16QAA/tREqKhVRtx1HM63gaa5TvVC6+Q9PQ0yB/mCw8ktWdn/WSpk6buN4cxCY/CkCfbEmTcHvY+v8GiK9CQN0L1UNfoqSkz5YRyyGkVQTfZcwNrSvGgV628NUvqD/PaAPLW8HoDz1m3ffCT4l9igyxfwmiWO/kAAAA==",
    "avifSrcSet": "/images/gallery-5--w480.avif 480w, /images/gallery-5--w768.avif 768w, /images/gallery-5--w1066.avif 1066w",
    "webpSrcSet": "/images/gallery-5--w480.webp 480w, /images/gallery-5--w768.webp 768w, /images/gallery-5--w1066.webp 1066w"
  },
  "/images/gallery-7.jpg": {
    "width": 1199,
    "height": 1600,
    "blurDataURL": "data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAABQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JYgBWAQ/4DzZaTv3PfzHuVhngAP7g2kvI3ZrH+o51VTGOMG9AXhp5y+bLob7EX/EnwQ9Hi+NPk9DUPVgDA61cd6JzDnQYiDMbGr+9LRXcOur7l1mFeWYLC0dzG2wK9V/DiG+Ktrw/xTuMckzXvupnzwAAAA==",
    "avifSrcSet": "/images/gallery-7--w480.avif 480w, /images/gallery-7--w768.avif 768w, /images/gallery-7--w1199.avif 1199w",
    "webpSrcSet": "/images/gallery-7--w480.webp 480w, /images/gallery-7--w768.webp 768w, /images/gallery-7--w1199.webp 1199w"
  },
  "/images/gallery-8.jpg": {
    "width": 1066,
    "height": 1600,
    "blurDataURL": "data:image/webp;base64,UklGRrIAAABXRUJQVlA4IKYAAABwBACdASoQABgAPu1iqU2ppaOiMAgBMB2JbACdAYv+yUo3Q1AEKTyAFdhPAAD+3I6RDLp+0BFhP+RKerMqcXiDATuF9B3wllCGkwrjVdYK1lAdHjTcDT6OGQN0QYhoeoO8KKnJFr+u1N1aUoWTNcKtk0k3gpXYIgPY13aSXWXviuLBHRVdW9TjeTRJBeVbu8tNWPAjIC3+S2RfgLAVdVBOxaW7GmAA",
    "avifSrcSet": "/images/gallery-8--w480.avif 480w, /images/gallery-8--w768.avif 768w, /images/gallery-8--w1066.avif 1066w",
    "webpSrcSet": "/images/gallery-8--w480.webp 480w, /images/gallery-8--w768.webp 768w, /images/gallery-8--w1066.webp 1066w"
  },
  "/images/hero-bowl.jpg": {
    "width": 1024,
    "height": 1024,
    "blurDataURL": "data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAABwAgCdASoQABAAA4BaJbACdAYuHjYFT5R4FI0AAP703xPiHrdgwIfX+8/BiLahi/1ooHvfZ/b09xL3ve1vMpdYu6833c7YgVG4CiyUDOF521zkOhRdLUwv/wBemrVBoZWK2Hn1opgXuyPBL63KfTjTHe0pndeZ1yDgAA==",
    "avifSrcSet": "/images/hero-bowl--w480.avif 480w, /images/hero-bowl--w768.avif 768w, /images/hero-bowl--w1024.avif 1024w",
    "webpSrcSet": "/images/hero-bowl--w480.webp 480w, /images/hero-bowl--w768.webp 768w, /images/hero-bowl--w1024.webp 1024w"
  },
  "/images/hero-coffee.jpg": {
    "width": 1024,
    "height": 1024,
    "blurDataURL": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAADwAQCdASoQABAAA4BaJYgCdAEVJu/sggAA/uybEmsnL0TLYk+yk9f3BwGm3dslzNfSCkUz1TZ070pkcnbdKgJ7T+2vQ3tf29ceIHTRiFUiydTEPKBSdsFWqtJ42ebifgAAAA==",
    "avifSrcSet": "/images/hero-coffee--w480.avif 480w, /images/hero-coffee--w768.avif 768w, /images/hero-coffee--w1024.avif 1024w",
    "webpSrcSet": "/images/hero-coffee--w480.webp 480w, /images/hero-coffee--w768.webp 768w, /images/hero-coffee--w1024.webp 1024w"
  },
  "/images/hero-interior.jpg": {
    "width": 1199,
    "height": 1600,
    "blurDataURL": "data:image/webp;base64,UklGRqQAAABXRUJQVlA4IJgAAABwBACdASoQABUAPu1iqU2ppaOiMAgBMB2JbACdMoMYAEI8xjh+12jxK56cAAD88Z6uEjs+8Rwg+YRPbsAmY74LVjUk1zwFLnXvlUS2xls4soFXwr7VrgBydNGIKrL1adCO4KbvwRJNoflojg/6US//m2ZB6y4C2dF7MM7FGz+ahLewhBaZ9FNVA33ERIxs0mlhsh2uNMAAAA==",
    "avifSrcSet": "/images/hero-interior--w480.avif 480w, /images/hero-interior--w768.avif 768w, /images/hero-interior--w1199.avif 1199w",
    "webpSrcSet": "/images/hero-interior--w480.webp 480w, /images/hero-interior--w768.webp 768w, /images/hero-interior--w1199.webp 1199w"
  },
  "/images/ingredients/free-range-eggs.jpg": {
    "width": 600,
    "height": 600,
    "blurDataURL": "data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAABQAgCdASoQABAAA4BaJaACdAYu5QzcLE4dMAAA/k157ygX/YRuzlL8GOTyIn1vduww+r/FSEpOBNMf0wjL4MuYdfODwyXy5UbEVi/3yews9UNXONHDRm68oOhdVrlznjpMgOvCvYp8qp9jK1jgIR089utcRhkNWk0eXIAA",
    "avifSrcSet": "/images/ingredients/free-range-eggs--w480.avif 480w, /images/ingredients/free-range-eggs--w600.avif 600w",
    "webpSrcSet": "/images/ingredients/free-range-eggs--w480.webp 480w, /images/ingredients/free-range-eggs--w600.webp 600w"
  },
  "/images/ingredients/natural-sweetness.jpg": {
    "width": 600,
    "height": 600,
    "blurDataURL": "data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAABwAgCdASoQABAAA4BaJbACdAYulqicFIGRZ6wAAP7qTbEE0fxn3eTGwK5uV2Wjk3e3kFMeEiSAHRFXpczEW8e00xdFgXuMyQDROj77JZ6RTZGypf1v+1Auj2S3ScO8/vJ4lx3d3KGK8qHr9KKtExZXm577T2inyuAAAA==",
    "avifSrcSet": "/images/ingredients/natural-sweetness--w480.avif 480w, /images/ingredients/natural-sweetness--w600.avif 600w",
    "webpSrcSet": "/images/ingredients/natural-sweetness--w480.webp 480w, /images/ingredients/natural-sweetness--w600.webp 600w"
  },
  "/images/ingredients/no-frying.jpg": {
    "width": 600,
    "height": 600,
    "blurDataURL": "data:image/webp;base64,UklGRpwAAABXRUJQVlA4IJAAAACwAgCdASoQABAAA4BaJbACdH8GJ/i1m4hJrTmjUcAA/urbl76ZYZJragfRzHecaRo3Xt5IndQAiF8AkyUQdENe4aHwQFf83xGwmlXTd8WS8GdzwaZWwaowWrcBjFugSJeaUO5iqhwg48yFD8p57qwnsWUv0SkbCeVTT3EUYD7AK7mRRa7vgScE/Z0HxsOAAAA=",
    "avifSrcSet": "/images/ingredients/no-frying--w480.avif 480w, /images/ingredients/no-frying--w600.avif 600w",
    "webpSrcSet": "/images/ingredients/no-frying--w480.webp 480w, /images/ingredients/no-frying--w600.webp 600w"
  },
  "/images/ingredients/olive-oil.jpg": {
    "width": 600,
    "height": 600,
    "blurDataURL": "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAADQAQCdASoQABAAA4BaJagCdADGvn7hgAD+67o9+dV/pqesZRvtPQCOr0GqpzGWxmKgny0EpZsZqJhRF+wfrEnvAgo6rdud1A/r4OnvQ80WVnPXPk1xKLSzqaOSjlrJTo/ynd4ekOr2QAAA",
    "avifSrcSet": "/images/ingredients/olive-oil--w480.avif 480w, /images/ingredients/olive-oil--w600.avif 600w",
    "webpSrcSet": "/images/ingredients/olive-oil--w480.webp 480w, /images/ingredients/olive-oil--w600.webp 600w"
  },
  "/images/ingredients/sourdough.jpg": {
    "width": 600,
    "height": 600,
    "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAAAQAgCdASoQABAAA4BaJYgC7AEO/vBv/ijQAP75DkOsNb7Xc0DGlcKQzLBOmg6W1tG+ZTifvas2FcmzWWK3gwsSqLtLeHNc+X7IAA==",
    "avifSrcSet": "/images/ingredients/sourdough--w480.avif 480w, /images/ingredients/sourdough--w600.avif 600w",
    "webpSrcSet": "/images/ingredients/sourdough--w480.webp 480w, /images/ingredients/sourdough--w600.webp 600w"
  },
  "/images/ingredients/whole-grains.jpg": {
    "width": 600,
    "height": 600,
    "blurDataURL": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAABQAgCdASoQABAAA4BaJZgCdH8AF77/bdJ/5YAA/vQrY+mZtxPE1Z1ya/lgRSOo1aQSr8c7turkq8xMl6MxSJRK1bxawF8yMO/iGppGZVz9glpxCvkAhyuLB6O6w1jyGArQAA==",
    "avifSrcSet": "/images/ingredients/whole-grains--w480.avif 480w, /images/ingredients/whole-grains--w600.avif 600w",
    "webpSrcSet": "/images/ingredients/whole-grains--w480.webp 480w, /images/ingredients/whole-grains--w600.webp 600w"
  },
  "/images/keep-rising-2.jpg": {
    "width": 1080,
    "height": 1439,
    "blurDataURL": "data:image/webp;base64,UklGRqgAAABXRUJQVlA4IJwAAACwBACdASoQABUAPu1iqU2ppaOiMAgBMB2JZAC2yywTnAnN05mFHUUJbEh4Un4AAP6iElADtG670rKEraC6PepbZmkvDUhxZtWrTQyRkDf0223yVNNgQ6ef4Rs3uSSz2GCMTgKu1c24Arh2dyOxWFt2y/Ad7oi8+4467Q7EMHMnqgRChiw57Q9KdkGDMqccEtbgkyPG7GelBdS1MAA=",
    "avifSrcSet": "/images/keep-rising-2--w480.avif 480w, /images/keep-rising-2--w768.avif 768w, /images/keep-rising-2--w1080.avif 1080w",
    "webpSrcSet": "/images/keep-rising-2--w480.webp 480w, /images/keep-rising-2--w768.webp 768w, /images/keep-rising-2--w1080.webp 1080w"
  },
  "/images/keep-rising-team.jpg": {
    "width": 1080,
    "height": 1440,
    "blurDataURL": "data:image/webp;base64,UklGRpYAAABXRUJQVlA4IIoAAAAwBACdASoQABUAPu1iqU2ppaOiMAgBMB2JYwCdAYvq1fCHVHEyba8o+QAA2/jzhFOuXNCjjSBmbD0OPqKsAgVDxyXu/IFAnJdQiO6A71GTfYSY92wUYNF46eW8dDfPXRBCC/CH16cubq43ajSBvFpiea5OwyDbJpkB32pbSG7cpbyxlbJcRDjwAAA=",
    "avifSrcSet": "/images/keep-rising-team--w480.avif 480w, /images/keep-rising-team--w768.avif 768w, /images/keep-rising-team--w1080.avif 1080w",
    "webpSrcSet": "/images/keep-rising-team--w480.webp 480w, /images/keep-rising-team--w768.webp 768w, /images/keep-rising-team--w1080.webp 1080w"
  },
  "/images/keep-rising.jpg": {
    "width": 841,
    "height": 1115,
    "blurDataURL": "data:image/webp;base64,UklGRo4AAABXRUJQVlA4IIIAAACwAwCdASoQABUAPu1kq04ppaQiMAgBMB2JaAAAUvzYkJc5U832AAD+vhUT36eLtXu3X7zFoeeFXw+pjTN535QntUnloAsyYfxGxG0o1kD8XHHUyWr5JoTTjJdxrW37Yq1F+4PSYa93/UwRQEqh0X45w2UPi0jgM+eWf9PrzykaAAAA",
    "avifSrcSet": "/images/keep-rising--w480.avif 480w, /images/keep-rising--w768.avif 768w, /images/keep-rising--w841.avif 841w",
    "webpSrcSet": "/images/keep-rising--w480.webp 480w, /images/keep-rising--w768.webp 768w, /images/keep-rising--w841.webp 841w"
  },
  "/images/leaves/fan-palm.png": {
    "width": 5000,
    "height": 3333,
    "blurDataURL": "data:image/webp;base64,UklGRs4AAABXRUJQVlA4WAoAAAAQAAAADwAACgAAQUxQSFoAAAABcFtr25q8X9xK96QL7jIAFR0TuDMFNdNQMZBNQr7DCBExAfgzERFPsiSRReVimEqceH6/TSOG1L8+H8u6WCXmp9f30JGrYBbr/SwBk0TVBrFgBBA4gOqCfgBWUDggTgAAADACAJ0BKhAACwADgFolqAJ0fwCCcMFOd3gAAP7jQbepuMW+j34hWyixwUaUxhk5EVoYFj9E/rqHw88gAKLXtlqLn9uYGfAofqupJkAAAA==",
    "avifSrcSet": "/images/leaves/fan-palm--w480.avif 480w, /images/leaves/fan-palm--w768.avif 768w, /images/leaves/fan-palm--w1200.avif 1200w, /images/leaves/fan-palm--w1600.avif 1600w, /images/leaves/fan-palm--w2048.avif 2048w",
    "webpSrcSet": "/images/leaves/fan-palm--w480.webp 480w, /images/leaves/fan-palm--w768.webp 768w, /images/leaves/fan-palm--w1200.webp 1200w, /images/leaves/fan-palm--w1600.webp 1600w, /images/leaves/fan-palm--w2048.webp 2048w"
  },
  "/images/leaves/monstera-cluster.png": {
    "width": 4000,
    "height": 6000,
    "blurDataURL": "data:image/webp;base64,UklGRq4BAABXRUJQVlA4WAoAAAAQAAAADwAAFwAAQUxQSOYAAAABgLJt2/lX+/28v/9sW9FGXt2xqKQPsuOfZm/Ja2ZTs9WWbNv63TMjYgLwD0W+JgqivqRgawF5J/LOUH7cmwgBBFAACrc4nxMIE4GZAUrwcDx4VmADDck7C1lQuF8xkglR1Y7dfGSJAivDBpr8Bji2wscH5oJpMMDpjLpOPnFcjj3g7BO9yfsnXX9kFa7SzKZ5d02SOm/i8XC9yJu20dme5dMnpkPdHF7op3PzNaYGp/hUE+BsyciTzJwNRwiggLDhXXLNLisASmkAELnKO7ZA4WMNdo1kB76oYJKdJF+BKHxb077zdVZQOCCiAAAA8AQAnQEqEAAYAD7tYqlNqaWjojAIATAdiWwAnQ4gDeDCIU3VYtfv39McnlSt/v5AAPqDr9fN4pRR6lrUe4K7Y79KRBGmctcY3G/F7oK1X+VWT1SPdYJpRmqruHgn4jdaNWIiGNYfdfDYOr8VXiInRG/J232KwtLCGjSy6sxQbQY22G8jQpWZVHT+AwuxbyW4z251u+r7+5/4vmtMStrI+aAA",
    "avifSrcSet": "/images/leaves/monstera-cluster--w480.avif 480w, /images/leaves/monstera-cluster--w768.avif 768w, /images/leaves/monstera-cluster--w1200.avif 1200w, /images/leaves/monstera-cluster--w1600.avif 1600w, /images/leaves/monstera-cluster--w2048.avif 2048w",
    "webpSrcSet": "/images/leaves/monstera-cluster--w480.webp 480w, /images/leaves/monstera-cluster--w768.webp 768w, /images/leaves/monstera-cluster--w1200.webp 1200w, /images/leaves/monstera-cluster--w1600.webp 1600w, /images/leaves/monstera-cluster--w2048.webp 2048w"
  },
  "/images/leaves/monstera-full.png": {
    "width": 6676,
    "height": 7038,
    "blurDataURL": "data:image/webp;base64,UklGRmwBAABXRUJQVlA4WAoAAAAQAAAADwAAEAAAQUxQSL8AAAABgHLbtqpV/z7ne1/8cHeJ3hgkTa6N6m7R9ScwaA7RM8md5O7uDp+e8t6LiAmAOjN0GwhgPQSK8waTBiN+xv6YDw1C8K6YZbjQAwSAENY3JGap3kwBA1DQZs+6lZehjxAQAEaPTPeK3B2XQQEIvDp7bbZLwWy7mvHwdfRPftcHGkwAQBiTD7NdxhrfwsGAglox2/9sr3LmBgII/tfyl78lH6lgAGDkLHYbE7aTwVAlgnswmBiaDNcIMEOvSywYqgBWUDgghgAAADAEAJ0BKhAAEQA+7WKpTamlo6IwCAEwHYlsAKwR+qLWWcI6v2OUnOrtwAD+y2YIaVYihHaiiBu9HfxNbgo2YJi2zOF/saNikp0NWs3UJPorLXaJLDGRRvKQKHE7AKwOi9/EKFbNze0QHGVmHOckr+4oHa0M6KUcllAjmEg/Rr/tHbd4AAAA",
    "avifSrcSet": "/images/leaves/monstera-full--w480.avif 480w, /images/leaves/monstera-full--w768.avif 768w, /images/leaves/monstera-full--w1200.avif 1200w, /images/leaves/monstera-full--w1600.avif 1600w, /images/leaves/monstera-full--w2048.avif 2048w",
    "webpSrcSet": "/images/leaves/monstera-full--w480.webp 480w, /images/leaves/monstera-full--w768.webp 768w, /images/leaves/monstera-full--w1200.webp 1200w, /images/leaves/monstera-full--w1600.webp 1600w, /images/leaves/monstera-full--w2048.webp 2048w"
  },
  "/images/leaves/monstera-large-1.png": {
    "width": 2400,
    "height": 2400,
    "blurDataURL": "data:image/webp;base64,UklGRmYBAABXRUJQVlA4WAoAAAAQAAAADwAADwAAQUxQSMUAAAABgCrJtmpnX/yDB2FSaEmiQpW4VBSTTUWxevLaKGbJzMycSGZmOPcscR7+QUQobNsGKYz3CPlCSXILRZVFoTpBViUiJdii6a5ZS3dE1MJR1uB0Fpu7AKyE3DxX/ogZdYDxX+QbqN5xmg3hm/2jPwfNfUQSqbswAbw1YdZwGhcMzPfs4I/jfV8Ea01aYvYcTA78kVAvGMebsQ3z1+ktcu1ksj4u70IEJxXNNXeeAnefjJzagAuYHGONv4ycU9Lj/11V4RP/AABWUDggegAAAFACAJ0BKhAAEAADgFolsAJ0OIA3iAiGCG/iUAD+y/1dNrxPKo6fF161bzyx/ZRh7si1WU8bLMeTNErKgl/YFIUB7q5H5zVLaZNT24Mk/c03JCWui9v4rponfaszkIrO133xIYTc1d3njst6Mc8kpXYcGCrNvWUKAAAA",
    "avifSrcSet": "/images/leaves/monstera-large-1--w480.avif 480w, /images/leaves/monstera-large-1--w768.avif 768w, /images/leaves/monstera-large-1--w1200.avif 1200w, /images/leaves/monstera-large-1--w1600.avif 1600w, /images/leaves/monstera-large-1--w2048.avif 2048w",
    "webpSrcSet": "/images/leaves/monstera-large-1--w480.webp 480w, /images/leaves/monstera-large-1--w768.webp 768w, /images/leaves/monstera-large-1--w1200.webp 1200w, /images/leaves/monstera-large-1--w1600.webp 1600w, /images/leaves/monstera-large-1--w2048.webp 2048w"
  },
  "/images/leaves/monstera-large-2.png": {
    "width": 2400,
    "height": 2400,
    "blurDataURL": "data:image/webp;base64,UklGRlQBAABXRUJQVlA4WAoAAAAQAAAADwAADwAAQUxQSMAAAAABgLpt2/FX+f1+37x1s27ZtlHtRSR768tKRrVtJdu2je+e0iJiAqCCbF4u9Ey+vL+9vXyMAkhLDklMLX8hqXAIAkGDt/ytcGeEAhgil4tmqbwrTKkG0NlpqRu7SxaX8NQKEA7qMUdUPjlje89GQEIBPz+U9xemtPDhVwPfPtmXxPEKPgMyXBV+ct3o8rqHrQAklPCVd4Yz3KnSASCgf0zu6O49+kHGb+EZGWphU2IOWfwlAKhJkAT+lmVZgizhPwJWUDggbgAAAFACAJ0BKhAAEAADgFolsAJ0BiqGTOGvgeMJgAD+8XnHujD6unjCMeEv8chDQJJ4k2DxJtIpjLFzstpA9BaF8FkNEbXNIEzdT0+O2mTfMVXHRKaaPPsnNTDkJEfdvgk33FjyRA1zFTDx3t3laHAA",
    "avifSrcSet": "/images/leaves/monstera-large-2--w480.avif 480w, /images/leaves/monstera-large-2--w768.avif 768w, /images/leaves/monstera-large-2--w1200.avif 1200w, /images/leaves/monstera-large-2--w1600.avif 1600w, /images/leaves/monstera-large-2--w2048.avif 2048w",
    "webpSrcSet": "/images/leaves/monstera-large-2--w480.webp 480w, /images/leaves/monstera-large-2--w768.webp 768w, /images/leaves/monstera-large-2--w1200.webp 1200w, /images/leaves/monstera-large-2--w1600.webp 1600w, /images/leaves/monstera-large-2--w2048.webp 2048w"
  },
  "/images/menu-acai.jpg": {
    "width": 1024,
    "height": 1024,
    "blurDataURL": "data:image/webp;base64,UklGRpYAAABXRUJQVlA4IIoAAACQAgCdASoQABAAA4BaJbACdAYtB20tMBFpT1FoAAD9/AYPE3jOJ4x65fRbPoObXlv1RIX4yv+FuccoulC1YlWfyyR3wNvGqxfPGSVMLiA3bEmSFxeW1fr1Jaur4clJ4fhSkCOH8xGv8F/A+a6wXd+NSI/G2OiuII3W2zXqKaqZ/4Sm2Tny/yvQAAA=",
    "avifSrcSet": "/images/menu-acai--w480.avif 480w, /images/menu-acai--w768.avif 768w, /images/menu-acai--w1024.avif 1024w",
    "webpSrcSet": "/images/menu-acai--w480.webp 480w, /images/menu-acai--w768.webp 768w, /images/menu-acai--w1024.webp 1024w"
  },
  "/images/menu-avocado-toast.jpg": {
    "width": 1024,
    "height": 1024,
    "blurDataURL": "data:image/webp;base64,UklGRpIAAABXRUJQVlA4IIYAAABwAgCdASoQABAAA4BaJbACdAYuv21Oijx3NAWkAP5PJJfkYY3NxtQNGf3WCM3Q+HGn4SRxCn7aXGX83sXaY3nGD3vRsuB757NZHXnMisEK/22jjXiGXHk0sIO1zKfCpvQ0P6TJ2xH3XtMLURhJHm0QkfokF1+b+IzRJaEziYC31e5RPoAAAA==",
    "avifSrcSet": "/images/menu-avocado-toast--w480.avif 480w, /images/menu-avocado-toast--w768.avif 768w, /images/menu-avocado-toast--w1024.avif 1024w",
    "webpSrcSet": "/images/menu-avocado-toast--w480.webp 480w, /images/menu-avocado-toast--w768.webp 768w, /images/menu-avocado-toast--w1024.webp 1024w"
  },
  "/images/menu-freddo.jpg": {
    "width": 1024,
    "height": 1024,
    "blurDataURL": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAAAwAgCdASoQABAAA4BaJbACdAELZGUyOJxwAAD+0fkaG83quZSiO/yn6EXYGmHVaY6+T2L0eGeRvIOtkFyz4wcbzzW8G2w2RJCZ94VOz/LJPUHLjDDJb3qpQlFDhWKdgPAL3LAA",
    "avifSrcSet": "/images/menu-freddo--w480.avif 480w, /images/menu-freddo--w768.avif 768w, /images/menu-freddo--w1024.avif 1024w",
    "webpSrcSet": "/images/menu-freddo--w480.webp 480w, /images/menu-freddo--w768.webp 768w, /images/menu-freddo--w1024.webp 1024w"
  },
  "/images/menu-poke-teriyaki.jpg": {
    "width": 1024,
    "height": 1024,
    "blurDataURL": "data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAACwAgCdASoQABAAA4BaJbACdH8AqQDDpTEl+I06I8AA/vUeQZb96v8yVSxMBZTJEfWRkw66Cvc0/xX8+kT1f4clsvxp9mDUblgZeSvAsl2fjXpbbBSuV5ER6Ik5mw5CNMll6nqyU2fubip0dtb4xapnhR0fgrtdHe/wfucKrfCAAA==",
    "avifSrcSet": "/images/menu-poke-teriyaki--w480.avif 480w, /images/menu-poke-teriyaki--w768.avif 768w, /images/menu-poke-teriyaki--w1024.avif 1024w",
    "webpSrcSet": "/images/menu-poke-teriyaki--w480.webp 480w, /images/menu-poke-teriyaki--w768.webp 768w, /images/menu-poke-teriyaki--w1024.webp 1024w"
  },
  "/images/menu-smoothie.jpg": {
    "width": 1024,
    "height": 1024,
    "blurDataURL": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAAAwAgCdASoQABAAA4BaJbACdADHY0ji2vyGeAD+8N77XRlvoM7iijRe9beXMuQu5k6wuRcppnIbRPtVyH1ai9Y7C+BHNMjypeNoOgrcRz1iPt4vLh3FCVMngEJUW4Udq9NrqMZjhAA=",
    "avifSrcSet": "/images/menu-smoothie--w480.avif 480w, /images/menu-smoothie--w768.avif 768w, /images/menu-smoothie--w1024.avif 1024w",
    "webpSrcSet": "/images/menu-smoothie--w480.webp 480w, /images/menu-smoothie--w768.webp 768w, /images/menu-smoothie--w1024.webp 1024w"
  },
  "/images/menu-vegan-poke.jpg": {
    "width": 1024,
    "height": 1024,
    "blurDataURL": "data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAADQAgCdASoQABAAA4BaJbACdH8EwADk/RaDVjx0VS6AAP7c27S0Go16tMe1j/+whrTlwrUvEPefvHdCAJvKysdqZjskXWImFABlO/omkQi7hwOfrq4zosYPRJgvAfcGkHhVy4Hnel2SIQZv9OvEKLv85hdc8bwefuhtn/3R/RV5kYphyWoJBiKXEoAAAA==",
    "avifSrcSet": "/images/menu-vegan-poke--w480.avif 480w, /images/menu-vegan-poke--w768.avif 768w, /images/menu-vegan-poke--w1024.avif 1024w",
    "webpSrcSet": "/images/menu-vegan-poke--w480.webp 480w, /images/menu-vegan-poke--w768.webp 768w, /images/menu-vegan-poke--w1024.webp 1024w"
  },
  "/images/menu/drink-cucumber-2-poster.jpg": {
    "width": 720,
    "height": 966,
    "blurDataURL": "data:image/webp;base64,UklGRpIAAABXRUJQVlA4IIYAAABQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JbACxG1yB032BVsJRUfbC7XYAAP7wy0hEGYZqVWw6feQ8EnSNVSJJC6/GTjh1KaKsf3re+LoVqDNfbvrGMWI2UEKyTbngamjU7zq+qm/yteEZOj8DqK4VyYm9rCy3d/3rkpgbOrtR8Zn+zuAAAA==",
    "avifSrcSet": "/images/menu/drink-cucumber-2-poster--w480.avif 480w, /images/menu/drink-cucumber-2-poster--w720.avif 720w",
    "webpSrcSet": "/images/menu/drink-cucumber-2-poster--w480.webp 480w, /images/menu/drink-cucumber-2-poster--w720.webp 720w"
  },
  "/images/menu/drink-cucumber-herbs-poster.jpg": {
    "width": 720,
    "height": 966,
    "blurDataURL": "data:image/webp;base64,UklGRpIAAABXRUJQVlA4IIYAAAAwBACdASoQABUAPu1iqU2ppaOiMAgBMB2JbACdL1yB032BV0s4BOj5X8AA/vDLSEQZhmpVbDp95DwSdI1VIkkLr8ZOOSIeHNBVhi9e7citnm+pZXhzJkAJgi1lhbeKhmOZJWpU0SPgt49MCQ6VPDJCeZeX6F7UrLPTWG9OEO2Lf3tX4WFgAA==",
    "avifSrcSet": "/images/menu/drink-cucumber-herbs-poster--w480.avif 480w, /images/menu/drink-cucumber-herbs-poster--w720.avif 720w",
    "webpSrcSet": "/images/menu/drink-cucumber-herbs-poster--w480.webp 480w, /images/menu/drink-cucumber-herbs-poster--w720.webp 720w"
  },
  "/images/menu/drink-lillet-spritz-poster.jpg": {
    "width": 720,
    "height": 966,
    "blurDataURL": "data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAABQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JbACdL1yB033didya80fMZWgAAP7wy0hEGYZqVWxSbtJ7lRGnPiyVd82iZsOc/M3tFfwt5lEbR9XjPJ8q0o76cSwlHQ4Ov8ltoTAJxkJPtykm8edm4qVjYAr0wybHWKeI7NNDx+IN87PmQIl1AAAA",
    "avifSrcSet": "/images/menu/drink-lillet-spritz-poster--w480.avif 480w, /images/menu/drink-lillet-spritz-poster--w720.avif 720w",
    "webpSrcSet": "/images/menu/drink-lillet-spritz-poster--w480.webp 480w, /images/menu/drink-lillet-spritz-poster--w720.webp 720w"
  },
  "/images/menu/drink-lillet-strawberry-poster.jpg": {
    "width": 720,
    "height": 966,
    "blurDataURL": "data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAABwBACdASoQABUAPu1iqU2ppaOiMAgBMB2JbACdL1yCFKNZq5Yfq1m/Q5MgAAD+8MtIRBmGalVsOn3id9Wyl8SDodCWEzONX0tBm+TFEIvm/rPS/S99E6m3gGD975zizZ6KQmAR+MWqoPALiB42HblJlIXFoRLlBw9NYb04Q9qSh57du5NowAAA",
    "avifSrcSet": "/images/menu/drink-lillet-strawberry-poster--w480.avif 480w, /images/menu/drink-lillet-strawberry-poster--w720.avif 720w",
    "webpSrcSet": "/images/menu/drink-lillet-strawberry-poster--w480.webp 480w, /images/menu/drink-lillet-strawberry-poster--w720.webp 720w"
  },
  "/images/menu/drink-pink-low-poster.jpg": {
    "width": 720,
    "height": 966,
    "blurDataURL": "data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAACQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JbACdMoC2AAjwhmR0WFCgIvLdCgAA/u6xZPloch9YgGklHSFoVp95++tMLCzQSVVOailcGY99q6LfwqzrJpOX5Xe273LpENN4PNHO/IaJ7l0LAi4rzFk5A6xJJ3B12WraMDohFKWY08SApJJOt59mBRl8YtAA",
    "avifSrcSet": "/images/menu/drink-pink-low-poster--w480.avif 480w, /images/menu/drink-pink-low-poster--w720.avif 720w",
    "webpSrcSet": "/images/menu/drink-pink-low-poster--w480.webp 480w, /images/menu/drink-pink-low-poster--w720.webp 720w"
  },
  "/images/menu/drink-red-low-poster.jpg": {
    "width": 720,
    "height": 966,
    "blurDataURL": "data:image/webp;base64,UklGRo4AAABXRUJQVlA4IIIAAADQAwCdASoQABUAPu1iqU2ppaOiMAgBMB2JbACdABwbTrXrKWxjAHAA/ux9EFs7a9HZ43UKsTS0IE8T4ft2NKwY2Djv52FgJv+oYUGJ9RlE7ozT5Q5odcuz8RbIKgIAyZqck3KNNnBYYQGbNUaAo8Afbo3sMFQx2YkG5mlsinPvWPAA",
    "avifSrcSet": "/images/menu/drink-red-low-poster--w480.avif 480w, /images/menu/drink-red-low-poster--w720.avif 720w",
    "webpSrcSet": "/images/menu/drink-red-low-poster--w480.webp 480w, /images/menu/drink-red-low-poster--w720.webp 720w"
  },
  "/images/menu/drink-white-lemon-poster.jpg": {
    "width": 720,
    "height": 966,
    "blurDataURL": "data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAABQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JbACdMoADT5WSCiaE67Jp09oAAP7sEUW87chKN/843GhM+TDOdGkrmOcyB8Bmce3i9KcdyfYZHq5s3qqENOsU2ys9rgHDA6HAbnrB1USQI8iuqKL2+fZ4Agqp7A7ozCpvEGmJZRi3lrrofwDXcAAA",
    "avifSrcSet": "/images/menu/drink-white-lemon-poster--w480.avif 480w, /images/menu/drink-white-lemon-poster--w720.avif 720w",
    "webpSrcSet": "/images/menu/drink-white-lemon-poster--w480.webp 480w, /images/menu/drink-white-lemon-poster--w720.webp 720w"
  },
  "/images/menu/drink-yellow-lemon-poster.jpg": {
    "width": 720,
    "height": 966,
    "blurDataURL": "data:image/webp;base64,UklGRpwAAABXRUJQVlA4IJAAAAAQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JbACdMoADYjTy1czSmaL6AAD+7GwK8qG+09a3HowThCREXOu46Yj/KOw6ydXflY3R993r9W7sDmOZBsyHoGhgAXigMam3gFxuFt43UfLq2vxBizr06G2zk5sgqn+xaxRjzyoIDpHcSVB9Dmu9OC5L6HO0BETIAAA=",
    "avifSrcSet": "/images/menu/drink-yellow-lemon-poster--w480.avif 480w, /images/menu/drink-yellow-lemon-poster--w720.avif 720w",
    "webpSrcSet": "/images/menu/drink-yellow-lemon-poster--w480.webp 480w, /images/menu/drink-yellow-lemon-poster--w720.webp 720w"
  },
  "/images/menu/glyka-0001.jpg": {
    "width": 1600,
    "height": 1200,
    "blurDataURL": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAAAQAgCdASoQAAwAA4BaJZACdAEQN5g1DbwAAP73mYQAO9CNQ42HIl7N3yFP4s8eG4gDhMbnBxhJPzPblLyHhFH0wi5U2kzzyeJsqd8/L/EuTN9gyOZelNfqsX3N6AAA",
    "avifSrcSet": "/images/menu/glyka-0001--w480.avif 480w, /images/menu/glyka-0001--w768.avif 768w, /images/menu/glyka-0001--w1200.avif 1200w, /images/menu/glyka-0001--w1600.avif 1600w",
    "webpSrcSet": "/images/menu/glyka-0001--w480.webp 480w, /images/menu/glyka-0001--w768.webp 768w, /images/menu/glyka-0001--w1200.webp 1200w, /images/menu/glyka-0001--w1600.webp 1600w"
  },
  "/images/menu/glyka-0002.jpg": {
    "width": 1600,
    "height": 1200,
    "blurDataURL": "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAABwAgCdASoQAAwAA4BaJbACdH8AgoC/UIxA7+IAAP7y2Axt/QT62qHuxon6sQ4j47ayqetEIDawY2nU7e/wZSprm7P7XQjdbeI9W15khqaMYZyLq26UBKq04qk8jhBr8F2mS23GpUgtHqAA",
    "avifSrcSet": "/images/menu/glyka-0002--w480.avif 480w, /images/menu/glyka-0002--w768.avif 768w, /images/menu/glyka-0002--w1200.avif 1200w, /images/menu/glyka-0002--w1600.avif 1600w",
    "webpSrcSet": "/images/menu/glyka-0002--w480.webp 480w, /images/menu/glyka-0002--w768.webp 768w, /images/menu/glyka-0002--w1200.webp 1200w, /images/menu/glyka-0002--w1600.webp 1600w"
  },
  "/images/menu/glyka-0003.jpg": {
    "width": 1600,
    "height": 1200,
    "blurDataURL": "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAACQAgCdASoQAAwAA4BaJbACdGaA2wAp8SpzTOHxgAD+72hgNeD6gJxBDzVIyHUp3VUJpeLfR7oUMqc9io5BXZ7FRyhIng6t1u3c0xHr8G50qdPcD4MgJ4QQpqe2eeT8kQ9boxmz1kmCjerOqjUXX0AA",
    "avifSrcSet": "/images/menu/glyka-0003--w480.avif 480w, /images/menu/glyka-0003--w768.avif 768w, /images/menu/glyka-0003--w1200.avif 1200w, /images/menu/glyka-0003--w1600.avif 1600w",
    "webpSrcSet": "/images/menu/glyka-0003--w480.webp 480w, /images/menu/glyka-0003--w768.webp 768w, /images/menu/glyka-0003--w1200.webp 1200w, /images/menu/glyka-0003--w1600.webp 1600w"
  },
  "/images/menu/glyka-0004.jpg": {
    "width": 1600,
    "height": 1200,
    "blurDataURL": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAABQAgCdASoQAAwAA4BaJZACdAEN+hXfK0A7wGAA/vRd/ECuL725q7XH5pXO/B881zQ1kwAA9VyVbg9uIJ2HKG3N3XD6rRF06ycA5DDw9bNWNe64/k5ybQEPtM4yzACEQCpdAAAA",
    "avifSrcSet": "/images/menu/glyka-0004--w480.avif 480w, /images/menu/glyka-0004--w768.avif 768w, /images/menu/glyka-0004--w1200.avif 1200w, /images/menu/glyka-0004--w1600.avif 1600w",
    "webpSrcSet": "/images/menu/glyka-0004--w480.webp 480w, /images/menu/glyka-0004--w768.webp 768w, /images/menu/glyka-0004--w1200.webp 1200w, /images/menu/glyka-0004--w1600.webp 1600w"
  },
  "/images/menu/glyka-0005.jpg": {
    "width": 1600,
    "height": 1200,
    "blurDataURL": "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAABwAgCdASoQAAwAA4BaJZgC7AYuH25P8i32FgYAAP7tK3IdblZ0lzFdMgzdlvEMBMOP4Xl9ILlLLQBV9HAzR71Jw9P19JqH4hl0eIEI5fKjGIsGuh4XB08m+QBkx6KJkX5kGtMUpWfI5bIX3zkMsBluSJcAAA==",
    "avifSrcSet": "/images/menu/glyka-0005--w480.avif 480w, /images/menu/glyka-0005--w768.avif 768w, /images/menu/glyka-0005--w1200.avif 1200w, /images/menu/glyka-0005--w1600.avif 1600w",
    "webpSrcSet": "/images/menu/glyka-0005--w480.webp 480w, /images/menu/glyka-0005--w768.webp 768w, /images/menu/glyka-0005--w1200.webp 1200w, /images/menu/glyka-0005--w1600.webp 1600w"
  },
  "/images/menu/glyka-0006.jpg": {
    "width": 1600,
    "height": 1200,
    "blurDataURL": "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAAAwAgCdASoQAAwAA4BaJYgCdAD6PYGkoBbwAAD+7R7t/VCuh5BzsQ2quNxhDbbuU1QvtrMZmp4jG3XOlcml6RgBRC8mIUDfE293uw0j2atftM+hRRz3AoB8z4m7DMYojN/8OsogL9lhisWyCCig4wAA",
    "avifSrcSet": "/images/menu/glyka-0006--w480.avif 480w, /images/menu/glyka-0006--w768.avif 768w, /images/menu/glyka-0006--w1200.avif 1200w, /images/menu/glyka-0006--w1600.avif 1600w",
    "webpSrcSet": "/images/menu/glyka-0006--w480.webp 480w, /images/menu/glyka-0006--w768.webp 768w, /images/menu/glyka-0006--w1200.webp 1200w, /images/menu/glyka-0006--w1600.webp 1600w"
  },
  "/images/menu/glyka-0007.jpg": {
    "width": 1600,
    "height": 1200,
    "blurDataURL": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAABwAgCdASoQAAwAA4BaJbACdAYtzqwFZ87DtsgAAP7zULjiAFH0q5fVkP7xDb/qvkpFa3RRjMHSDYD/uqAeXzn4Hmqq7FjSQLvViDhn4D/vfAF0uFP24qkjnIm4ZPC5lbwHK8W4QAA=",
    "avifSrcSet": "/images/menu/glyka-0007--w480.avif 480w, /images/menu/glyka-0007--w768.avif 768w, /images/menu/glyka-0007--w1200.avif 1200w, /images/menu/glyka-0007--w1600.avif 1600w",
    "webpSrcSet": "/images/menu/glyka-0007--w480.webp 480w, /images/menu/glyka-0007--w768.webp 768w, /images/menu/glyka-0007--w1200.webp 1200w, /images/menu/glyka-0007--w1600.webp 1600w"
  },
  "/images/menu/glyka-0008.jpg": {
    "width": 1600,
    "height": 1200,
    "blurDataURL": "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAAAwAgCdASoQAAwAA4BaJZACdAYuRSXXZCXqAAD+9e7pIvB8H6Oaj8xcN2TXtywsZTBPhsKTVD3CV9RCsqmBBK7/gm1B3OB5m3IXyjCY9uEXCsIFmpf1FsNdD3/61vuSbe7XnWF9hj5fdPgfjblAAA==",
    "avifSrcSet": "/images/menu/glyka-0008--w480.avif 480w, /images/menu/glyka-0008--w768.avif 768w, /images/menu/glyka-0008--w1200.avif 1200w, /images/menu/glyka-0008--w1600.avif 1600w",
    "webpSrcSet": "/images/menu/glyka-0008--w480.webp 480w, /images/menu/glyka-0008--w768.webp 768w, /images/menu/glyka-0008--w1200.webp 1200w, /images/menu/glyka-0008--w1600.webp 1600w"
  },
  "/images/menu/kokteil-0001.jpg": {
    "width": 1600,
    "height": 2134,
    "blurDataURL": "data:image/webp;base64,UklGRpwAAABXRUJQVlA4IJAAAADwAwCdASoQABUAPu1iqU2ppaOiMAgBMB2JbACdABxN5eaUHhbkeMbQAP7usWT62FwC7EPL5btIhkAjUJB06QL2F5SqveFtHXj1wApCTr/032k6oofLAVNQHiZX5nrXIgMUsMc5pjNLhj82slVc7/A+eNcZkxw5icR+m+sCSuXkMx7us7tDNfuw8U21k5ygAAA=",
    "avifSrcSet": "/images/menu/kokteil-0001--w480.avif 480w, /images/menu/kokteil-0001--w768.avif 768w, /images/menu/kokteil-0001--w1200.avif 1200w, /images/menu/kokteil-0001--w1600.avif 1600w",
    "webpSrcSet": "/images/menu/kokteil-0001--w480.webp 480w, /images/menu/kokteil-0001--w768.webp 768w, /images/menu/kokteil-0001--w1200.webp 1200w, /images/menu/kokteil-0001--w1600.webp 1600w"
  },
  "/images/menu/kokteil-0003.jpg": {
    "width": 1600,
    "height": 2133,
    "blurDataURL": "data:image/webp;base64,UklGRpwAAABXRUJQVlA4IJAAAABQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JbACdMoAvQBrCztWP1XuAP2cAAP7wy97EXq8PTp+JSL0x0UjGlfSCb7+uFL4GQdDomtU7UBXgIrYh0zt/mM2qEiuG7a0o76cR3xS2hbV05CPgngFvOFIb897loJ14jCyeGQfH0nFyBVxsprvJmAck57sNMXpDAAA=",
    "avifSrcSet": "/images/menu/kokteil-0003--w480.avif 480w, /images/menu/kokteil-0003--w768.avif 768w, /images/menu/kokteil-0003--w1200.avif 1200w, /images/menu/kokteil-0003--w1600.avif 1600w",
    "webpSrcSet": "/images/menu/kokteil-0003--w480.webp 480w, /images/menu/kokteil-0003--w768.webp 768w, /images/menu/kokteil-0003--w1200.webp 1200w, /images/menu/kokteil-0003--w1600.webp 1600w"
  },
  "/images/menu/kokteil-0004.jpg": {
    "width": 1600,
    "height": 2133,
    "blurDataURL": "data:image/webp;base64,UklGRpYAAABXRUJQVlA4IIoAAACQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JbACdMoCGACQL1Uyc++LTO3JQMoAA/vDJcZHSM7e83QBhRL8ru0Ik88eLDDNbdt5gu7E54xqFVDfdZ4EsH0281AxkzwQLXB0O6SXJgqcqgMNo5d9gzT3UBKsAsVKByXiqyytp/FoeNF/iC4vDYT6EAAA=",
    "avifSrcSet": "/images/menu/kokteil-0004--w480.avif 480w, /images/menu/kokteil-0004--w768.avif 768w, /images/menu/kokteil-0004--w1200.avif 1200w, /images/menu/kokteil-0004--w1600.avif 1600w",
    "webpSrcSet": "/images/menu/kokteil-0004--w480.webp 480w, /images/menu/kokteil-0004--w768.webp 768w, /images/menu/kokteil-0004--w1200.webp 1200w, /images/menu/kokteil-0004--w1600.webp 1600w"
  },
  "/images/menu/kokteil-0005.jpg": {
    "width": 1600,
    "height": 2133,
    "blurDataURL": "data:image/webp;base64,UklGRqAAAABXRUJQVlA4IJQAAAAQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JbACdMoADQMEpbbocOjJ9AAD+7BEiEAsvA0Vv01Bg+DSuHKjddRLW6LFXRgbT1S/RLcixGijASyBPcHGZILay1EgGywQ+s2h0xUNUMzeDzRzwM1D3/+p6JoNnD9EZu93BvGs/zFFZ/Ux/S2U90vy3zF2yDPxR3fcGHqwA",
    "avifSrcSet": "/images/menu/kokteil-0005--w480.avif 480w, /images/menu/kokteil-0005--w768.avif 768w, /images/menu/kokteil-0005--w1200.avif 1200w, /images/menu/kokteil-0005--w1600.avif 1600w",
    "webpSrcSet": "/images/menu/kokteil-0005--w480.webp 480w, /images/menu/kokteil-0005--w768.webp 768w, /images/menu/kokteil-0005--w1200.webp 1200w, /images/menu/kokteil-0005--w1600.webp 1600w"
  },
  "/images/menu/kokteil-0006.jpg": {
    "width": 1600,
    "height": 2133,
    "blurDataURL": "data:image/webp;base64,UklGRqoAAABXRUJQVlA4IJ4AAABQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JbACsLwAB058zNrGESy8xEfRAAP7sbAr7jGoQfxi49GCpOZBv1etYG9XpxeSPfMFutmOE5tilKLSKb1+37HSy2NWbts1LlHw5k6ZdOHrzMginzlHONYe0/EP0Y2pbREXhYNZGBaaj+I9/uYlbDB/ghkuxb7lw8FV+xXJaSfFbEP1htKAAAA==",
    "avifSrcSet": "/images/menu/kokteil-0006--w480.avif 480w, /images/menu/kokteil-0006--w768.avif 768w, /images/menu/kokteil-0006--w1200.avif 1200w, /images/menu/kokteil-0006--w1600.avif 1600w",
    "webpSrcSet": "/images/menu/kokteil-0006--w480.webp 480w, /images/menu/kokteil-0006--w768.webp 768w, /images/menu/kokteil-0006--w1200.webp 1200w, /images/menu/kokteil-0006--w1600.webp 1600w"
  },
  "/images/menu/kokteil-0007.jpg": {
    "width": 1600,
    "height": 2134,
    "blurDataURL": "data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAACQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JbACdMoRwACaMuPfvLJACys7HhoAA/u6vMmlQcsuElDbKbd8pKREA0dvDmOBYSqm+y9FxX7ryOoowpkXOb/Wfvt7M37BMC9ph/eMyXOeVqxanfWavLm3lFl2hs+EZC116NUVcy/98pDBs+BWIOGF3t6A/RCAA",
    "avifSrcSet": "/images/menu/kokteil-0007--w480.avif 480w, /images/menu/kokteil-0007--w768.avif 768w, /images/menu/kokteil-0007--w1200.avif 1200w, /images/menu/kokteil-0007--w1600.avif 1600w",
    "webpSrcSet": "/images/menu/kokteil-0007--w480.webp 480w, /images/menu/kokteil-0007--w768.webp 768w, /images/menu/kokteil-0007--w1200.webp 1200w, /images/menu/kokteil-0007--w1600.webp 1600w"
  },
  "/images/menu/kokteil-0008.jpg": {
    "width": 1600,
    "height": 2133,
    "blurDataURL": "data:image/webp;base64,UklGRqoAAABXRUJQVlA4IJ4AAACwBACdASoQABUAPu1iqU2ppaOiMAgBMB2JbACdMoR4GCXf7sehR9E6/cPXjVFYAP7uq/oxihyuQBz/fb4UCN8wgqhWh8jwargLQzXuK1EVeYksoMAh6d+s6RQ5a7QIHkygFbWRig/+O58hixKg9cVxnz0Gt8nS42+cNRx/84O+pjygUKOCo31U5pj1riYaIDKAyyigcXq81+BrqGaAAA==",
    "avifSrcSet": "/images/menu/kokteil-0008--w480.avif 480w, /images/menu/kokteil-0008--w768.avif 768w, /images/menu/kokteil-0008--w1200.avif 1200w, /images/menu/kokteil-0008--w1600.avif 1600w",
    "webpSrcSet": "/images/menu/kokteil-0008--w480.webp 480w, /images/menu/kokteil-0008--w768.webp 768w, /images/menu/kokteil-0008--w1200.webp 1200w, /images/menu/kokteil-0008--w1600.webp 1600w"
  },
  "/images/menu/piata-0009.jpg": {
    "width": 1600,
    "height": 1200,
    "blurDataURL": "data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAADQAgCdASoQAAwAA4BaJbACdDiAN5AIjgoG8azbmiykAP7xs16Z9zmaiT1dqz/ed+kA4oAYpuH6dipDAURRE1SEKPWbgUD3qYuaDyU6/NuuKridtr8yTr3h1mL/27qaH0Gb7uXpsya0v6QBIdN9F4PfavkX9pjyK+gAAA==",
    "avifSrcSet": "/images/menu/piata-0009--w480.avif 480w, /images/menu/piata-0009--w768.avif 768w, /images/menu/piata-0009--w1200.avif 1200w, /images/menu/piata-0009--w1600.avif 1600w",
    "webpSrcSet": "/images/menu/piata-0009--w480.webp 480w, /images/menu/piata-0009--w768.webp 768w, /images/menu/piata-0009--w1200.webp 1200w, /images/menu/piata-0009--w1600.webp 1600w"
  },
  "/images/menu/piata-0013.jpg": {
    "width": 1600,
    "height": 1200,
    "blurDataURL": "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAABwAgCdASoQAAwAA4BaJbACdH8AGTrdhopg7vRAAP70tprbz34HPZGPUAummnpar2ejSHI2ZiBEQjkkt4Vf6/DB5FUMm4NlVp2qUbrXxzpDyq2XKQPqhZ4RER0ff42G4SArZv9q6XhwbAAA",
    "avifSrcSet": "/images/menu/piata-0013--w480.avif 480w, /images/menu/piata-0013--w768.avif 768w, /images/menu/piata-0013--w1200.avif 1200w, /images/menu/piata-0013--w1600.avif 1600w",
    "webpSrcSet": "/images/menu/piata-0013--w480.webp 480w, /images/menu/piata-0013--w768.webp 768w, /images/menu/piata-0013--w1200.webp 1200w, /images/menu/piata-0013--w1600.webp 1600w"
  },
  "/images/menu/piata-0015.jpg": {
    "width": 1600,
    "height": 1200,
    "blurDataURL": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAABwAgCdASoQAAwAA4BaJbACdAYv1d0XexZgraGAAP7zXum0E1JvR/uRV9jr7NHwJZThYkngQ8uAu3eVCrTVMuKK6fYwMIBoK2F7zQMS8CkglJ12/dly8hv/4RgZWvUc5PYjhazcDhKAAA==",
    "avifSrcSet": "/images/menu/piata-0015--w480.avif 480w, /images/menu/piata-0015--w768.avif 768w, /images/menu/piata-0015--w1200.avif 1200w, /images/menu/piata-0015--w1600.avif 1600w",
    "webpSrcSet": "/images/menu/piata-0015--w480.webp 480w, /images/menu/piata-0015--w768.webp 768w, /images/menu/piata-0015--w1200.webp 1200w, /images/menu/piata-0015--w1600.webp 1600w"
  },
  "/images/menu/piata-0016.jpg": {
    "width": 1600,
    "height": 1200,
    "blurDataURL": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAABwAgCdASoQAAwAA4BaJbACdH8AGZaPcbQ5M5sAAP7zY0zhBQjdJefmsWT5oJxnR4sRbO1KjMklH3g1+6d/M9mwrIET+PEtMevG9Noq0pqjDtm4eCPKfUKxn4if2NgYLt3WLRQtVsIAAA==",
    "avifSrcSet": "/images/menu/piata-0016--w480.avif 480w, /images/menu/piata-0016--w768.avif 768w, /images/menu/piata-0016--w1200.avif 1200w, /images/menu/piata-0016--w1600.avif 1600w",
    "webpSrcSet": "/images/menu/piata-0016--w480.webp 480w, /images/menu/piata-0016--w768.webp 768w, /images/menu/piata-0016--w1200.webp 1200w, /images/menu/piata-0016--w1600.webp 1600w"
  },
  "/images/menu/piata-0018.jpg": {
    "width": 1600,
    "height": 1200,
    "blurDataURL": "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAABQAgCdASoQAAwAA4BaJbACdH8AgqSlMzuQpEAA/vG6B1vMs9Bty/oUA0Pi7tyxE7o9GmreilMe6CKYQA+Oo3dQmM1qNLmZbmMH28ukjwRq3g84X3tXaZgJlHuJ5abJuRKt+QN4/ne1zCoiZWYodF1+95OgAA==",
    "avifSrcSet": "/images/menu/piata-0018--w480.avif 480w, /images/menu/piata-0018--w768.avif 768w, /images/menu/piata-0018--w1200.avif 1200w, /images/menu/piata-0018--w1600.avif 1600w",
    "webpSrcSet": "/images/menu/piata-0018--w480.webp 480w, /images/menu/piata-0018--w768.webp 768w, /images/menu/piata-0018--w1200.webp 1200w, /images/menu/piata-0018--w1600.webp 1600w"
  },
  "/images/menu/piata-0020.jpg": {
    "width": 1600,
    "height": 1200,
    "blurDataURL": "data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAADwAgCdASoQAAwAA4BaJbACdH8KsBXALszHKKbbB0qbIAD+7SAH43YTJce4ERNTXAAeT7ENwXeFTnqRvYwLkNxHMnByGmdnWttWFl79UD2MDByVNoC30PqDrhzgedTRsy6DJtonf+15UHDaDWAWvHYWUY/x2ArSDxOlQAAA",
    "avifSrcSet": "/images/menu/piata-0020--w480.avif 480w, /images/menu/piata-0020--w768.avif 768w, /images/menu/piata-0020--w1200.avif 1200w, /images/menu/piata-0020--w1600.avif 1600w",
    "webpSrcSet": "/images/menu/piata-0020--w480.webp 480w, /images/menu/piata-0020--w768.webp 768w, /images/menu/piata-0020--w1200.webp 1200w, /images/menu/piata-0020--w1600.webp 1600w"
  },
  "/images/menu/piata-0022.jpg": {
    "width": 1600,
    "height": 1200,
    "blurDataURL": "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAAAwAgCdASoQAAwAA4BaJbACdH8AEWTD6n/wAAD+9uDvJnslDp1w3evtzzWkhxQkqtRgbhiX+w4wsjhEAcaFkHDd9C1+Ke9HI/ZAHmRSv1+XUVnLU5SaVkjRR2Dw/OpDcB6K0L7vwf5EAwKgAAA=",
    "avifSrcSet": "/images/menu/piata-0022--w480.avif 480w, /images/menu/piata-0022--w768.avif 768w, /images/menu/piata-0022--w1200.avif 1200w, /images/menu/piata-0022--w1600.avif 1600w",
    "webpSrcSet": "/images/menu/piata-0022--w480.webp 480w, /images/menu/piata-0022--w768.webp 768w, /images/menu/piata-0022--w1200.webp 1200w, /images/menu/piata-0022--w1600.webp 1600w"
  },
  "/images/menu/piata-0025.jpg": {
    "width": 1600,
    "height": 1200,
    "blurDataURL": "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAADwAgCdASoQAAwAA4BaJbACdH8EwAbyIRD5WrAfErgOAAD+9uDvFMYiu+MDtgSpXawT3SOuoe81UP+RYcr21nmPfCzrbE+8fofQQ0ERCy/cQj7bjYrv5Spk0t0J9V/5286DnF/aZuB0+fbud2xZQk4AAAA=",
    "avifSrcSet": "/images/menu/piata-0025--w480.avif 480w, /images/menu/piata-0025--w768.avif 768w, /images/menu/piata-0025--w1200.avif 1200w, /images/menu/piata-0025--w1600.avif 1600w",
    "webpSrcSet": "/images/menu/piata-0025--w480.webp 480w, /images/menu/piata-0025--w768.webp 768w, /images/menu/piata-0025--w1200.webp 1200w, /images/menu/piata-0025--w1600.webp 1600w"
  },
  "/images/menu/piata-0028.jpg": {
    "width": 1600,
    "height": 1200,
    "blurDataURL": "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAABQAgCdASoQAAwAA4BaJbACdAYtfdYyeIDnU/gA/vNREwTz2LPBpOhpKYSYk+5qrvx1hcrH4CzzbmoZ++Lc85Na9HHD8sguyvFe5XgjQ2e/0/FSjv6tiQ1E1h6FidanhR/hI5Ti+qe6nvWMEzs22lo0Mx2H8AAA",
    "avifSrcSet": "/images/menu/piata-0028--w480.avif 480w, /images/menu/piata-0028--w768.avif 768w, /images/menu/piata-0028--w1200.avif 1200w, /images/menu/piata-0028--w1600.avif 1600w",
    "webpSrcSet": "/images/menu/piata-0028--w480.webp 480w, /images/menu/piata-0028--w768.webp 768w, /images/menu/piata-0028--w1200.webp 1200w, /images/menu/piata-0028--w1600.webp 1600w"
  },
  "/images/menu/piata-0031.jpg": {
    "width": 1600,
    "height": 1200,
    "blurDataURL": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAABQAgCdASoQAAwAA4BaJbACdH8AFwD2/+eMLgAA/vaTRAqk16D4T+c+P3zHvKyTbgsDeMIKFpDtvUcL4Viu6O/LXtCQnSnzxFgEBtC//DfNfNhKIAAAAA==",
    "avifSrcSet": "/images/menu/piata-0031--w480.avif 480w, /images/menu/piata-0031--w768.avif 768w, /images/menu/piata-0031--w1200.avif 1200w, /images/menu/piata-0031--w1600.avif 1600w",
    "webpSrcSet": "/images/menu/piata-0031--w480.webp 480w, /images/menu/piata-0031--w768.webp 768w, /images/menu/piata-0031--w1200.webp 1200w, /images/menu/piata-0031--w1600.webp 1600w"
  },
  "/images/mess-logo-interior.jpg.jpg": {
    "width": 1920,
    "height": 1277,
    "blurDataURL": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAAAQAgCdASoQAAsAA4BaJbACdADxIp065k+AAP7SBpD4sG3gf7BUZHXhWi+fKrtZ797wvVQ1oCiTzNp8umLjZL7etRE/hD8vjDBBODaxO33vm+nIm49d7SMQ9EQpOQAA",
    "avifSrcSet": "/images/mess-logo-interior.jpg--w480.avif 480w, /images/mess-logo-interior.jpg--w768.avif 768w, /images/mess-logo-interior.jpg--w1200.avif 1200w, /images/mess-logo-interior.jpg--w1600.avif 1600w, /images/mess-logo-interior.jpg--w1920.avif 1920w",
    "webpSrcSet": "/images/mess-logo-interior.jpg--w480.webp 480w, /images/mess-logo-interior.jpg--w768.webp 768w, /images/mess-logo-interior.jpg--w1200.webp 1200w, /images/mess-logo-interior.jpg--w1600.webp 1600w, /images/mess-logo-interior.jpg--w1920.webp 1920w"
  },
  "/images/mess-philosophy-poster.jpg": {
    "width": 720,
    "height": 1280,
    "blurDataURL": "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAADQAwCdASoQABwAPu1krU6ppaSiMAgBMB2JQBOgBDjmybFLeCMGdQAA/tq+8mAXOoPixxr3dPYr57SjdQ8JRjwFjcOCM9eixp76rmzf4v0gGgtnbJvozZOX4PDg6weLGToaVnMimngyq8qRMAA=",
    "avifSrcSet": "/images/mess-philosophy-poster--w480.avif 480w, /images/mess-philosophy-poster--w720.avif 720w",
    "webpSrcSet": "/images/mess-philosophy-poster--w480.webp 480w, /images/mess-philosophy-poster--w720.webp 720w"
  },
  "/images/raw/about-plants-light.png": {
    "width": 472,
    "height": 287,
    "blurDataURL": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAAAwAgCdASoQAAoAA4BaJZACdAf2BadgGT1hAAD+7PbYv9f19G2sdtFnuDQ9lz4fH5nqJOkWP+oz5JPzKVzNLfvTYYJDyYiByNFEPsgHvuOZtNJze8iOXmj9NyRyjfDzI+nEqYAA",
    "avifSrcSet": "/images/raw/about-plants-light--w472.avif 472w",
    "webpSrcSet": "/images/raw/about-plants-light--w472.webp 472w"
  },
  "/images/raw/about-space-start.png": {
    "width": 940,
    "height": 1024,
    "blurDataURL": "data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAAAwBACdASoQABIAPu1iqU2ppaOiMAgBMB2JQBadZYA2j4fi2CbY6ni4ZgAA/psYb7RGJtesBAgiNBzj2CUT3/DNsC1aoffQmhkAqL9FeSmXvOLgH05O/ipgd5d59opKenj++qbx/rch5k+Tz876zNFyUF/GUCKy0Y864xAA",
    "avifSrcSet": "/images/raw/about-space-start--w480.avif 480w, /images/raw/about-space-start--w768.avif 768w, /images/raw/about-space-start--w940.avif 940w",
    "webpSrcSet": "/images/raw/about-space-start--w480.webp 480w, /images/raw/about-space-start--w768.webp 768w, /images/raw/about-space-start--w940.webp 940w"
  },
  "/images/raw/gallery-food-35.png": {
    "width": 1024,
    "height": 681,
    "blurDataURL": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADwAQCdASoQAAsAA4BaJagCdADp9M2vAAAA+gHNIk1RvNOvBLYfr97ijSgFP1KeMVYP09Bj5cUb1c42KYWkAwesntkI5oXw5BVRGvF2enwAAA==",
    "avifSrcSet": "/images/raw/gallery-food-35--w480.avif 480w, /images/raw/gallery-food-35--w768.avif 768w, /images/raw/gallery-food-35--w1024.avif 1024w",
    "webpSrcSet": "/images/raw/gallery-food-35--w480.webp 480w, /images/raw/gallery-food-35--w768.webp 768w, /images/raw/gallery-food-35--w1024.webp 1024w"
  },
  "/images/raw/gallery-hero-still.png": {
    "width": 980,
    "height": 737,
    "blurDataURL": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAAAQAgCdASoQAAwAA4BaJZQCdAEPCbnqCGPQAP3EZ8W3kh6taYpY8DeNJB24yp+cFq6cvdiuTXCPGc9UIRPp0n1+ZCod9rE4SgxwxnUUHvk9Z9rYtdDYkEAA",
    "avifSrcSet": "/images/raw/gallery-hero-still--w480.avif 480w, /images/raw/gallery-hero-still--w768.avif 768w, /images/raw/gallery-hero-still--w980.avif 980w",
    "webpSrcSet": "/images/raw/gallery-hero-still--w480.webp 480w, /images/raw/gallery-hero-still--w768.webp 768w, /images/raw/gallery-hero-still--w980.webp 980w"
  },
  "/images/raw/mess-internal-0027-1.png": {
    "width": 768,
    "height": 1024,
    "blurDataURL": "data:image/webp;base64,UklGRrIAAABXRUJQVlA4IKYAAABwBACdASoQABUAPu1iqk2ppaQiMAgBMB2JaADCjBAAMzbGayqG3c2CHalyAAD+8N6GdGvj9wIRflFSKgBK+arTIM46EuSLC6+Tzk/hzHvl16G1zQt+HWXYNd+qBEh/7j1SoeaCrry/Cma5FvjQDbykhze3gX/j1GmeZZw7wzCfX6CCaFJJ0mpfHAePfOTN/wVTyTbOv1/1K1K9Vf/O/by/6iUHuAAA",
    "avifSrcSet": "/images/raw/mess-internal-0027-1--w480.avif 480w, /images/raw/mess-internal-0027-1--w768.avif 768w",
    "webpSrcSet": "/images/raw/mess-internal-0027-1--w480.webp 480w, /images/raw/mess-internal-0027-1--w768.webp 768w"
  },
}

export function getImageManifestEntry(src: string): ImageManifestEntry | undefined {
  if (!src || typeof src !== 'string') return undefined
  const key = src.split('?')[0]
  return imageManifest[key]
}
