/** Auto-generated by scripts/optimize-images.mjs — do not edit */

export type ImageManifestEntry = {
  width: number
  height: number
  blurDataURL: string
  avifSrcSet: string
  webpSrcSet: string
}

export const imageManifest: Record<string, ImageManifestEntry> = {
  "/images/111/mess-internal-0002.jpg": {
    "width": 2000,
    "height": 1500,
    "blurDataURL": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAAAQAgCdASoQAAwAA4BaJbACdAEQ0EKbr4gAAP67avpcMlUbWYerUTM8FqHdGuotaGqwBT9x4/CaXXd1eoujQxIKJbKinZE/+lJZro+tUz9lLcmSlcLNn7hBC3j0HIKiTzFAAA==",
    "avifSrcSet": "/images/111/mess-internal-0002--w480.avif 480w, /images/111/mess-internal-0002--w768.avif 768w, /images/111/mess-internal-0002--w1200.avif 1200w, /images/111/mess-internal-0002--w1600.avif 1600w, /images/111/mess-internal-0002--w2000.avif 2000w",
    "webpSrcSet": "/images/111/mess-internal-0002--w480.webp 480w, /images/111/mess-internal-0002--w768.webp 768w, /images/111/mess-internal-0002--w1200.webp 1200w, /images/111/mess-internal-0002--w1600.webp 1600w, /images/111/mess-internal-0002--w2000.webp 2000w"
  },
  "/images/111/mess-internal-0004.jpg": {
    "width": 2000,
    "height": 1333,
    "blurDataURL": "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAAAwAgCdASoQAAsAA4BaJbACdAYv1Vt3gvaxAAD+7P/eFTACn5fs3yDyeqT8pr8tAbnJc/TorKrdA+MhZW8KOok2GrtbQcPBcNfE1NlN0WrvPp/3Z/vJFzLduUg72sLrccjJtMqhYZamf4+pPSI8AA==",
    "avifSrcSet": "/images/111/mess-internal-0004--w480.avif 480w, /images/111/mess-internal-0004--w768.avif 768w, /images/111/mess-internal-0004--w1200.avif 1200w, /images/111/mess-internal-0004--w1600.avif 1600w, /images/111/mess-internal-0004--w2000.avif 2000w",
    "webpSrcSet": "/images/111/mess-internal-0004--w480.webp 480w, /images/111/mess-internal-0004--w768.webp 768w, /images/111/mess-internal-0004--w1200.webp 1200w, /images/111/mess-internal-0004--w1600.webp 1600w, /images/111/mess-internal-0004--w2000.webp 2000w"
  },
  "/images/111/mess-internal-0005.jpg": {
    "width": 1500,
    "height": 2250,
    "blurDataURL": "data:image/webp;base64,UklGRs4AAABXRUJQVlA4IMIAAADQBACdASoQABgAPu1iqU2ppaOiMAgBMB2JbAC7DiAByukG0JclTnaO9nwdbcj8gAD4W2NZABjkMxZ/9UgpYZUnU+Jap5I7JJO3SwbhqCMnwWqeBr0m/NZjw3WhInPecbwiIHSLZHje+ntG/lDk+BSM8aAEUKrw2FOKvEnEy5ynKexqpHTXd+KvfJLh5njFOheMO+vDcbD5w/aOZqxBlkjTiU1YlDvNfS5wJqLeiME3I3UIIiZ7oBWC/6qHkWDRDwAAAA==",
    "avifSrcSet": "/images/111/mess-internal-0005--w480.avif 480w, /images/111/mess-internal-0005--w768.avif 768w, /images/111/mess-internal-0005--w1200.avif 1200w, /images/111/mess-internal-0005--w1500.avif 1500w",
    "webpSrcSet": "/images/111/mess-internal-0005--w480.webp 480w, /images/111/mess-internal-0005--w768.webp 768w, /images/111/mess-internal-0005--w1200.webp 1200w, /images/111/mess-internal-0005--w1500.webp 1500w"
  },
  "/images/111/mess-internal-0006.jpg": {
    "width": 1600,
    "height": 1066,
    "blurDataURL": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAAAwAgCdASoQAAsAA4BaJbAC7AD2Oa3pFp5qwAD+heilH7xeq0iAUigfQ7eDuarRivgtWwsBbw6VA0Ij9Tlc/vGxXKxarIGO7WYGC9WoRbggZBZJtxKwbqpJT3nAJrN95JQ4wfW3u6gAAA==",
    "avifSrcSet": "/images/111/mess-internal-0006--w480.avif 480w, /images/111/mess-internal-0006--w768.avif 768w, /images/111/mess-internal-0006--w1200.avif 1200w, /images/111/mess-internal-0006--w1600.avif 1600w",
    "webpSrcSet": "/images/111/mess-internal-0006--w480.webp 480w, /images/111/mess-internal-0006--w768.webp 768w, /images/111/mess-internal-0006--w1200.webp 1200w, /images/111/mess-internal-0006--w1600.webp 1600w"
  },
  "/images/111/mess-internal-0007.jpg": {
    "width": 768,
    "height": 1153,
    "blurDataURL": "data:image/webp;base64,UklGRvAAAABXRUJQVlA4IOQAAABQBACdASoQABgAPu1iqU2ppaOiMAgBMB2JbACdMoAlsRG/DG5YDGTksp6AAP64QOEMvcLyL2G8MNwgKYjhr6/q9CnfF3Gs458S+atUw13IaPMgY3MqsAv+mXGPHAR9cEkQ3yPHJe6Jt8bgn+crMSaZr/Z9p5Av5pw5ByJ+O2ulTRz00Pn7u2jm0H/DiQ+9eREh7KTKn9KRLvoRm3axyvzqN8Inc80Ummyi/49lFffpvoK3GaduRIOnJOzBplzwNfxO58/12B5aC7wuA//qlmq+Q+RuV2wqBDT341ChfpiCxzoAAAA=",
    "avifSrcSet": "/images/111/mess-internal-0007--w480.avif 480w, /images/111/mess-internal-0007--w768.avif 768w",
    "webpSrcSet": "/images/111/mess-internal-0007--w480.webp 480w, /images/111/mess-internal-0007--w768.webp 768w"
  },
  "/images/111/mess-internal-0008.jpg": {
    "width": 2000,
    "height": 1333,
    "blurDataURL": "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAAAQAgCdASoQAAsAA4BaJbACdAEWy5oPn2AAAP5rVH/dFpRvz0qKbC2HDXHv5R+nS0QlX1OfJqrW1pM0+2dc4WDrmZ7EIR6brgc5QHOiMLCqSglhEq2fDzUrO832gN1YfKmjH5NuEHMOjZbC2FF+oAAA",
    "avifSrcSet": "/images/111/mess-internal-0008--w480.avif 480w, /images/111/mess-internal-0008--w768.avif 768w, /images/111/mess-internal-0008--w1200.avif 1200w, /images/111/mess-internal-0008--w1600.avif 1600w, /images/111/mess-internal-0008--w2000.avif 2000w",
    "webpSrcSet": "/images/111/mess-internal-0008--w480.webp 480w, /images/111/mess-internal-0008--w768.webp 768w, /images/111/mess-internal-0008--w1200.webp 1200w, /images/111/mess-internal-0008--w1600.webp 1600w, /images/111/mess-internal-0008--w2000.webp 2000w"
  },
  "/images/111/mess-internal-0009.jpg": {
    "width": 1600,
    "height": 1066,
    "blurDataURL": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAADwAQCdASoQAAsAA4BaJbACdAEOua2kQ4AA/sYCctzX0va4JzQgxDDzRIZ59Y83KnaLJ7iOd1yl28vgP9ZbaoAnwK3+lbrZuD++t+LGeCjA+ydTIPTnLDVG2Yy0AA==",
    "avifSrcSet": "/images/111/mess-internal-0009--w480.avif 480w, /images/111/mess-internal-0009--w768.avif 768w, /images/111/mess-internal-0009--w1200.avif 1200w, /images/111/mess-internal-0009--w1600.avif 1600w",
    "webpSrcSet": "/images/111/mess-internal-0009--w480.webp 480w, /images/111/mess-internal-0009--w768.webp 768w, /images/111/mess-internal-0009--w1200.webp 1200w, /images/111/mess-internal-0009--w1600.webp 1600w"
  },
  "/images/111/mess-internal-0010.jpg": {
    "width": 2000,
    "height": 1333,
    "blurDataURL": "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAAAwAgCdASoQAAsAA4BaJbACdAEVU3dCDqAqAAD+J72dYmW4/mqhuzV+1WP/YqC/n9Ej+t7ynrqJGlb5G/0lzsOv2iA5WH8wM5L+XneLTBOBF3xtmGpjWo2ZL9n/7B/5kU/s3z3Ccnnp7eAAAAA=",
    "avifSrcSet": "/images/111/mess-internal-0010--w480.avif 480w, /images/111/mess-internal-0010--w768.avif 768w, /images/111/mess-internal-0010--w1200.avif 1200w, /images/111/mess-internal-0010--w1600.avif 1600w, /images/111/mess-internal-0010--w2000.avif 2000w",
    "webpSrcSet": "/images/111/mess-internal-0010--w480.webp 480w, /images/111/mess-internal-0010--w768.webp 768w, /images/111/mess-internal-0010--w1200.webp 1200w, /images/111/mess-internal-0010--w1600.webp 1600w, /images/111/mess-internal-0010--w2000.webp 2000w"
  },
  "/images/111/mess-internal-0015.jpg": {
    "width": 2000,
    "height": 1333,
    "blurDataURL": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAADwAQCdASoQAAsAA4BaJbAC7AD1mf2IHhAA/oXopR+8XqtIgFIoH0O36BXR3K3no6ZDhXJcN2gQSjeVkjIznH15plVtzy57/qthHkC8GW0/UW8TlKRITVB+OUdXaAN0woT9wtvpTJVwAA==",
    "avifSrcSet": "/images/111/mess-internal-0015--w480.avif 480w, /images/111/mess-internal-0015--w768.avif 768w, /images/111/mess-internal-0015--w1200.avif 1200w, /images/111/mess-internal-0015--w1600.avif 1600w, /images/111/mess-internal-0015--w2000.avif 2000w",
    "webpSrcSet": "/images/111/mess-internal-0015--w480.webp 480w, /images/111/mess-internal-0015--w768.webp 768w, /images/111/mess-internal-0015--w1200.webp 1200w, /images/111/mess-internal-0015--w1600.webp 1600w, /images/111/mess-internal-0015--w2000.webp 2000w"
  },
  "/images/111/mess-internal-0016.jpg": {
    "width": 1600,
    "height": 2400,
    "blurDataURL": "data:image/webp;base64,UklGRu4AAABXRUJQVlA4IOIAAAAwBACdASoQABgAPu1iqU2ppaQiMAgBMB2JbACdMoAlsRGs1s3sueVqx3wA/rhA4Qy9wvIvYbww3KQXpOZJNhOr0KZU4R9NL8O0s0M4kObnKK305UM/ZVjMd7NMasr2DLlISPKS8yj/Gbwx2FIJAqITlFHFELigm4z7EWUuP0PiVQBcwovVje8x04Qor25SLMJOwWtjULL1UUP+W1tE+F73DoZ54fmikzTeexLdUVlvj/d+sKIGANjotbERgcf43f4nc+f67A8sxqICL/8pZqvkPkbldsKgQ2xCghBX2pTkC4AA",
    "avifSrcSet": "/images/111/mess-internal-0016--w480.avif 480w, /images/111/mess-internal-0016--w768.avif 768w, /images/111/mess-internal-0016--w1200.avif 1200w, /images/111/mess-internal-0016--w1600.avif 1600w",
    "webpSrcSet": "/images/111/mess-internal-0016--w480.webp 480w, /images/111/mess-internal-0016--w768.webp 768w, /images/111/mess-internal-0016--w1200.webp 1200w, /images/111/mess-internal-0016--w1600.webp 1600w"
  },
  "/images/111/mess-internal-0018.jpg": {
    "width": 2000,
    "height": 1333,
    "blurDataURL": "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAAAQAgCdASoQAAsAA4BaJbACdAYuu/eNunngAPwwI3beIORRCrNUYSlcZ9b8jiN7S3AYUIV4EeYWpurmiFjovkYCtFB9C5D3hnmQ/Yr439DwDtsNtQNNnSBSm4N74AyDCXLj15wix55bqU1SVfAAAA==",
    "avifSrcSet": "/images/111/mess-internal-0018--w480.avif 480w, /images/111/mess-internal-0018--w768.avif 768w, /images/111/mess-internal-0018--w1200.avif 1200w, /images/111/mess-internal-0018--w1600.avif 1600w, /images/111/mess-internal-0018--w2000.avif 2000w",
    "webpSrcSet": "/images/111/mess-internal-0018--w480.webp 480w, /images/111/mess-internal-0018--w768.webp 768w, /images/111/mess-internal-0018--w1200.webp 1200w, /images/111/mess-internal-0018--w1600.webp 1600w, /images/111/mess-internal-0018--w2000.webp 2000w"
  },
  "/images/111/mess-internal-0019.jpg": {
    "width": 1920,
    "height": 1279,
    "blurDataURL": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAAAQAgCdASoQAAsAA4BaJagCdAED8E+zrlQAAP7lJweipT/u1DNVErg7jeTEJjWsmu0Jmxj4vO4NChdJ2b6bzNYCljMbu0KcH50E7rqvuerlBZtQGPLJdLBo4iNHw8QA",
    "avifSrcSet": "/images/111/mess-internal-0019--w480.avif 480w, /images/111/mess-internal-0019--w768.avif 768w, /images/111/mess-internal-0019--w1200.avif 1200w, /images/111/mess-internal-0019--w1600.avif 1600w, /images/111/mess-internal-0019--w1920.avif 1920w",
    "webpSrcSet": "/images/111/mess-internal-0019--w480.webp 480w, /images/111/mess-internal-0019--w768.webp 768w, /images/111/mess-internal-0019--w1200.webp 1200w, /images/111/mess-internal-0019--w1600.webp 1600w, /images/111/mess-internal-0019--w1920.webp 1920w"
  },
  "/images/111/mess-internal-0020.jpg": {
    "width": 2000,
    "height": 1333,
    "blurDataURL": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAAAQAgCdASoQAAsAA4BaJagC7AD2IHwkBhsAAMtFfTDN+Xc8nPAPN9Yq7nNi4IChteBdhfmsaJGdgdLSkIjo7zS0K1AQXoWoF96wSUzyh5RxFihmEPZPWJKKHsZ/SH64AAA=",
    "avifSrcSet": "/images/111/mess-internal-0020--w480.avif 480w, /images/111/mess-internal-0020--w768.avif 768w, /images/111/mess-internal-0020--w1200.avif 1200w, /images/111/mess-internal-0020--w1600.avif 1600w, /images/111/mess-internal-0020--w2000.avif 2000w",
    "webpSrcSet": "/images/111/mess-internal-0020--w480.webp 480w, /images/111/mess-internal-0020--w768.webp 768w, /images/111/mess-internal-0020--w1200.webp 1200w, /images/111/mess-internal-0020--w1600.webp 1600w, /images/111/mess-internal-0020--w2000.webp 2000w"
  },
  "/images/111/mess-internal-0023.jpg": {
    "width": 1500,
    "height": 2250,
    "blurDataURL": "data:image/webp;base64,UklGRrwAAABXRUJQVlA4ILAAAACQBACdASoQABgAPu1iqU2ppaOiMAgBMB2JbACdMoBOACN6BKO1oP6vwSAmNcAA/CWEvLNseXf7K6kpsfJF+ayrR8Acc5ER3cCF3aoeaEyINB2QHJ7n7Do7xlKnwNPR73ykKneSWaaubIKVKkbSxBgTSAat26MtLXeceG4w7ZvfE6hOnS/p9IfBJWjy7bYwf7GjnxFsWvxGtSDwgUsc0ikmJE+9mPvXIIqSJNpvum4AAA==",
    "avifSrcSet": "/images/111/mess-internal-0023--w480.avif 480w, /images/111/mess-internal-0023--w768.avif 768w, /images/111/mess-internal-0023--w1200.avif 1200w, /images/111/mess-internal-0023--w1500.avif 1500w",
    "webpSrcSet": "/images/111/mess-internal-0023--w480.webp 480w, /images/111/mess-internal-0023--w768.webp 768w, /images/111/mess-internal-0023--w1200.webp 1200w, /images/111/mess-internal-0023--w1500.webp 1500w"
  },
  "/images/111/mess-internal-0030.jpg": {
    "width": 1600,
    "height": 2400,
    "blurDataURL": "data:image/webp;base64,UklGRqwAAABXRUJQVlA4IKAAAABQBACdASoQABgAPu1iqU2ppaOiMAgBMB2JZgCdAYxY1f/VYW85DRcSwLuMAP7URKh+dMbcY7tYixXn89iOP+yc47Ay01iO2bXuELj2uC4DY5JgihECo55Vsf1/yMxBk3mHs4bXZLLChZ2AxA6WlMfC6D8sI5ZDR+QWdxIC60TnUBtsUdAXsBFQDSx7RTbmxejonWLjMGyGI9LGkSK9oAAA",
    "avifSrcSet": "/images/111/mess-internal-0030--w480.avif 480w, /images/111/mess-internal-0030--w768.avif 768w, /images/111/mess-internal-0030--w1200.avif 1200w, /images/111/mess-internal-0030--w1600.avif 1600w",
    "webpSrcSet": "/images/111/mess-internal-0030--w480.webp 480w, /images/111/mess-internal-0030--w768.webp 768w, /images/111/mess-internal-0030--w1200.webp 1200w, /images/111/mess-internal-0030--w1600.webp 1600w"
  },
  "/images/111/mess-internal-0034.jpg": {
    "width": 1600,
    "height": 2133,
    "blurDataURL": "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAAAQBACdASoQABUAPu1iqk2ppaQiMAgBMB2JbACdH8ADAp5PJaFe0DTLAAD+3qrTVIZRnflRTJ5Xc3jzlShgD2+WCMSFVOGPWzeEH/Zp6UVRI3B/uFVr3/WfU+GMrWpHUTTcEDCG4IW2HmyJXcymEAAA",
    "avifSrcSet": "/images/111/mess-internal-0034--w480.avif 480w, /images/111/mess-internal-0034--w768.avif 768w, /images/111/mess-internal-0034--w1200.avif 1200w, /images/111/mess-internal-0034--w1600.avif 1600w",
    "webpSrcSet": "/images/111/mess-internal-0034--w480.webp 480w, /images/111/mess-internal-0034--w768.webp 768w, /images/111/mess-internal-0034--w1200.webp 1200w, /images/111/mess-internal-0034--w1600.webp 1600w"
  },
  "/images/about-1.jpg": {
    "width": 1066,
    "height": 1600,
    "blurDataURL": "data:image/webp;base64,UklGRrwAAABXRUJQVlA4ILAAAACQBACdASoQABgAPu1iqU2ppaOiMAgBMB2JaACdIExgvhfuhjPpWi70RN6jogAA/ni24GSgoOOrJ7CctTbB24F26tAPqLtCM5SeIGzUhBdYlb47n+UCc7pzQdHXVUIa441FG2KxmZ5NwpFruv3+3G21V/lv7zdlMJhXU11g3ptKwmhP1QKxtrlJteP2t56MMxSHeK0uv7+OCKJlSAKeoJj7hQPKo5TOJITMNBwyd7AAAA==",
    "avifSrcSet": "/images/about-1--w480.avif 480w, /images/about-1--w768.avif 768w, /images/about-1--w1066.avif 1066w",
    "webpSrcSet": "/images/about-1--w480.webp 480w, /images/about-1--w768.webp 768w, /images/about-1--w1066.webp 1066w"
  },
  "/images/about-2.jpg": {
    "width": 1920,
    "height": 1279,
    "blurDataURL": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAAAQAgCdASoQAAsAA4BaJagCdAED8E+zrlQAAP7lJweipT/u1DNVErg7jeTEJjWsmu0Jmxj4vO4NChdJ2b6bzNYCljMbu0KcH50E7rqvuerlBZtQGPLJdLBo4iNHw8QA",
    "avifSrcSet": "/images/about-2--w480.avif 480w, /images/about-2--w768.avif 768w, /images/about-2--w1200.avif 1200w, /images/about-2--w1600.avif 1600w, /images/about-2--w1920.avif 1920w",
    "webpSrcSet": "/images/about-2--w480.webp 480w, /images/about-2--w768.webp 768w, /images/about-2--w1200.webp 1200w, /images/about-2--w1600.webp 1600w, /images/about-2--w1920.webp 1920w"
  },
  "/images/about-3.jpg": {
    "width": 1066,
    "height": 1600,
    "blurDataURL": "data:image/webp;base64,UklGRvAAAABXRUJQVlA4IOQAAABwBACdASoQABgAPu1iqU2ppaQiMAgBMB2JbACdMoAlrxG+rmEEBDc5DMCXmAD+uEDhC7xS8iuqMjDYpBek5kjne6Kr+tmHytwGNs6GIgrq13hMatb4xi58I5bBCFR5V9LCdrr5VKeMIyfl1iTblTR/NZZd0dbQVSGfHQxvMCS4/GdFdtEMTpE/Pj0APX6HKwZB0YlraBmOgj2tVrywq6fWemT9pfAnmjrwC41r25nAt6Tt1OWDmhlcnMiwkfOb43f4nc+f67A8sxqICL/8pZqvkPkbldrYmz2UMZw634gw7DmAAAA=",
    "avifSrcSet": "/images/about-3--w480.avif 480w, /images/about-3--w768.avif 768w, /images/about-3--w1066.avif 1066w",
    "webpSrcSet": "/images/about-3--w480.webp 480w, /images/about-3--w768.webp 768w, /images/about-3--w1066.webp 1066w"
  },
  "/images/about-4.webp": {
    "width": 1920,
    "height": 1277,
    "blurDataURL": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAABwAgCdASoQAAsAA4BaJbACdAYqrzYL4P72K2kAAP7R/rW1ygLwCcDmpbh2i+ckOP/0bU5mNKhU55INXfcwQdCnwPcCifPyX8af2ifY2N3WLg/vfN9ORNx672kYh0qXsHAAAA==",
    "avifSrcSet": "/images/about-4--w480.avif 480w, /images/about-4--w768.avif 768w, /images/about-4--w1200.avif 1200w, /images/about-4--w1600.avif 1600w, /images/about-4--w1920.avif 1920w",
    "webpSrcSet": "/images/about-4--w480.webp 480w, /images/about-4--w768.webp 768w, /images/about-4--w1200.webp 1200w, /images/about-4--w1600.webp 1600w, /images/about-4--w1920.webp 1920w"
  },
  "/images/about-editorial-poster.jpg": {
    "width": 820,
    "height": 1230,
    "blurDataURL": "data:image/webp;base64,UklGRrwAAABXRUJQVlA4ILAAAACQBACdASoQABgAPu1iqU2ppaOiMAgBMB2JaACdIExguBWZhkoh4y4QWtLOzQAA/ni23eBFZsQJwRIYCqbYNDW5WFOBsgHBLkilhK46J5LWwYDqVicoKUXT0exmuqM/6n1Q0ajnllzhOI24t78dqF3zOBy0Cjv215s5oQLXwOzck+nByVpCFs4C5poZix77WrVLbEoqFf0e6n8DdnF21q/aSL6dlIhD5lVWaNqj0AAAAA==",
    "avifSrcSet": "/images/about-editorial-poster--w480.avif 480w, /images/about-editorial-poster--w768.avif 768w, /images/about-editorial-poster--w820.avif 820w",
    "webpSrcSet": "/images/about-editorial-poster--w480.webp 480w, /images/about-editorial-poster--w768.webp 768w, /images/about-editorial-poster--w820.webp 820w"
  },
  "/images/decor/photo/banana-leaf.png": {
    "width": 1280,
    "height": 785,
    "blurDataURL": "data:image/webp;base64,UklGRkgBAABXRUJQVlA4WAoAAAAQAAAADwAACQAAQUxQSJAAAAABgGJt27LoeT9ckrtr+xNOJxOpHJpHmjsbYAGsQGeWYKuY6u7yju4hIiYA/ws5pLs2SPwhZITiGc8BEiTkguBe8geXEIyBQAhML/mV10HZ4tSlj1dWD/z5wgdpLcpvj1cfzJ8vb3yc0xFg6H3w6/PHJ+9LagKEITq64k8+aZkEAYDaL+WrzYINhH+VcgAg/AlWUDggkgAAAHACAJ0BKhAACgADgFolsAJ0MEdIiQlDCWLZneAA/uhPDYhv1i/MW9r3zrIvu6jzmZ5TejB3pmx+lx+XhDOeST0O0qFH2ExY39/ej1gtz8i3aMXXQ6SjDixFC/v/24rYPIxc3KLhTpDAlHMkL7f0j/7z5lO+1TSew09/2PV+1Gkx+d2svj/+CEyUcw8TOBhwAAAA",
    "avifSrcSet": "/images/decor/photo/banana-leaf--w480.avif 480w, /images/decor/photo/banana-leaf--w768.avif 768w, /images/decor/photo/banana-leaf--w1200.avif 1200w, /images/decor/photo/banana-leaf--w1280.avif 1280w",
    "webpSrcSet": "/images/decor/photo/banana-leaf--w480.webp 480w, /images/decor/photo/banana-leaf--w768.webp 768w, /images/decor/photo/banana-leaf--w1200.webp 1200w, /images/decor/photo/banana-leaf--w1280.webp 1280w"
  },
  "/images/decor/photo/fan-palm.png": {
    "width": 1063,
    "height": 1280,
    "blurDataURL": "data:image/webp;base64,UklGRqYBAABXRUJQVlA4WAoAAAAQAAAADwAAEgAAQUxQSP8AAAAFgGVb2/HmeT/8SWrbtm23V7pvJ9gR2LZt29YXJ1OIiAkAyOijBfy/0PvbNxkBuLDM6zjxceN6oh0DxFjhb7gu+H+Fvb5vurwYE69Soz2MKT/zf6IrZvWHWPtok8E7gi18b30d01uk4a5jpZlHeEzeHDwaxcBRXdhuqXuZCllavfq+6eW+jxn1v9H5EXQwezq+V75DCV+iKis252dvbFB5D+3fwT/Ct7ItGaudD9fb39cU4u7i691Y+ni7u3JBFztGIsgwrxd5E+2lpt4J4K5efxc+YStMCaMyAlL/ZoRf2JL4g32m/MIXmXKAjM55xc6T0QFAy5xXcJSMBWsfNgAAVlA4IIAAAAAQBACdASoQABMAPu1iqU2ppaOiMAgBMB2JbACdDiAByezqbHKRfPX3BAD+2YJyn5dXaBMitYP5DPZ3HUWRLK/OknA7R73jIxeMMTUSa7jCZX5MGhfGzaREuEvyqJoFh6W2Dbn0wvRrpW/266o8FKb8CwZRQT5LVvFpzYx8YxrgAA==",
    "avifSrcSet": "/images/decor/photo/fan-palm--w480.avif 480w, /images/decor/photo/fan-palm--w768.avif 768w, /images/decor/photo/fan-palm--w1063.avif 1063w",
    "webpSrcSet": "/images/decor/photo/fan-palm--w480.webp 480w, /images/decor/photo/fan-palm--w768.webp 768w, /images/decor/photo/fan-palm--w1063.webp 1063w"
  },
  "/images/decor/photo/fern.png": {
    "width": 868,
    "height": 1280,
    "blurDataURL": "data:image/webp;base64,UklGRkACAABXRUJQVlA4WAoAAAAQAAAADwAAFwAAQUxQSIEBAAAAAAAAAAAAAwATZgIAAAAAAAAAAQEAAQAHnHoABAAAAAAAAQACBw1LjM57FAAIAQAAAAANLGmUmoaln4lSEwACAAIRNmR/lKyGir29g08hAAADKGyUjpupf5adeoaMRCMGC0V3h4mQqn+Yn52biWcYABk6VnCIlp91pbWgpZx4NAscZ4OUjZKTd6ubkJaejk4WRY6Tm5WUmXqtqb6/sYgvAw4wR2F4o6B/rJqPhHl8PQsndJWnoa2Nbaamoa6bmHEiAUaTsLWnlXzBvpOFcWA6HDJZSV5+kJh4sbG+u7JxHQAAGn2onqOseKuqqLO9n0AHH4VXSZKpr4GLtKaqo4lpJiEWb6XCuqyQgK6or6eTRRYAIkecmpCurXmrqqGsomscAQNahpKzpZd9mcrDv59CDAAJFkKGqHypeoC2lmNfNwYAAAAKamTDnJtxhMNvBwABAAEADiTFXb9hPhQQQicAAQAAAgBINmGKAAICAAAAAAAAAAABCQM+CQACAAECAQAAAFZQOCCYAAAAkAMAnQEqEAAYAD7tYqlNqaWjojAIATAdiWwAnQwVEiETVGA50AD+R+6ttiI2tBPj+vAlmuQXzI+sEsEqeKJWSRi/oDlrTiMRRQz73/xzuf4tvnSZ+qW5VV9Sf3frt/jhT/xbkF+wyz5WVSh2/Jki0OsTi2veDCJyV8oiltyGqGn8Kfe9UihBgwyujE5bBHeW5jEVjjB0QAA=",
    "avifSrcSet": "/images/decor/photo/fern--w480.avif 480w, /images/decor/photo/fern--w768.avif 768w, /images/decor/photo/fern--w868.avif 868w",
    "webpSrcSet": "/images/decor/photo/fern--w480.webp 480w, /images/decor/photo/fern--w768.webp 768w, /images/decor/photo/fern--w868.webp 868w"
  },
  "/images/decor/photo/leaf-cluster-border.png": {
    "width": 1280,
    "height": 640,
    "blurDataURL": "data:image/webp;base64,UklGRgABAABXRUJQVlA4WAoAAAAQAAAADwAABwAAQUxQSIEAAAAAAgABAAEAAwUAAQABAAEAAAQAQp8sAFZjFgEABjVkdhBwuaX/0xZ3inIlAGq9tN9n9PDA5MIlUIuJQRW5wdXDrNGozNLUOD+slXAvu9/uyLw5z7jt3RYWoJ9YFqHg7MpgB1h/6ZMAACRaHQAqRGRYBAIBAgQEAAAABwIAAAIBAAAAVlA4IFgAAAAwAgCdASoQAAgAA4BaJbACdLoAApve4a7zYAD+7Nuo08Y40PtPpxErdS7zrBGcU3OAPIMXGDRlOnSDfR2OLDb/z39gHpKZiT69rXfq0XviSPZzQMRpKegA",
    "avifSrcSet": "/images/decor/photo/leaf-cluster-border--w480.avif 480w, /images/decor/photo/leaf-cluster-border--w768.avif 768w, /images/decor/photo/leaf-cluster-border--w1200.avif 1200w, /images/decor/photo/leaf-cluster-border--w1280.avif 1280w",
    "webpSrcSet": "/images/decor/photo/leaf-cluster-border--w480.webp 480w, /images/decor/photo/leaf-cluster-border--w768.webp 768w, /images/decor/photo/leaf-cluster-border--w1200.webp 1200w, /images/decor/photo/leaf-cluster-border--w1280.webp 1280w"
  },
  "/images/decor/photo/monstera-1.png": {
    "width": 1280,
    "height": 1280,
    "blurDataURL": "data:image/webp;base64,UklGRjQBAABXRUJQVlA4WAoAAAAQAAAADwAADwAAQUxQSIkAAAABgJpt27Lsfl5colaXDUi6gztkWIAVoBHpFt2dRiX97u478HzHP0JETAD+V2MHSSHoyypIszSKWhAn4Hu78kJwclRfS3oQJxDpbDMQHFDsPzXAE4yHz4EXJEG3+FpU7CDOUO6ePYUhOyXg6exuJ16IUwRlc3+sgcAKeOp3f3HIGBDsfrsVxIEIPABWUDgghAAAAHACAJ0BKhAAEAADgFolsAJ0fwPZLIgssc4Q3FAA/tFBkiAlBJV8XjDsuCQcbUKusQGW26VuVENeD8EgO/i+d1vWEYHgW3e1Hk+STR6dsYVxNILh4wcw/0X1XQvVfXTVgfnVm6RWhMipcGu6Jy3EBrBkcyx8C0doAYyPBIq+JVNnXAAAAA==",
    "avifSrcSet": "/images/decor/photo/monstera-1--w480.avif 480w, /images/decor/photo/monstera-1--w768.avif 768w, /images/decor/photo/monstera-1--w1200.avif 1200w, /images/decor/photo/monstera-1--w1280.avif 1280w",
    "webpSrcSet": "/images/decor/photo/monstera-1--w480.webp 480w, /images/decor/photo/monstera-1--w768.webp 768w, /images/decor/photo/monstera-1--w1200.webp 1200w, /images/decor/photo/monstera-1--w1280.webp 1280w"
  },
  "/images/decor/photo/monstera-2.png": {
    "width": 1037,
    "height": 1280,
    "blurDataURL": "data:image/webp;base64,UklGRuABAABXRUJQVlA4WAoAAAAQAAAADwAAEwAAQUxQSAUBAAABkGvb2rFX+0PsVDYrO6lsu3JvVelyBU6VKsfsbJuVbVvv+z776CIiYgIAwHJsWPDfzpsNACwHFmJ6PYepKa2AhYCKqBXefEpRPGnBf+4hP3+jEVL40sUQjfDjUyojmnddjFJpXk+8QaHmuouSD0r4scFn9cZn8yYXdZsOvqXhp+hSb9+kUDQYCilaL/R0pMGyzvOnUbu/UfhA/aiB/U1E8dyeK1SieAb4QuGTY/1LVMbwVQyOUK/VhhQdoNDwYSiCs9MxfubGD5Ka87ABB/NUQgp3B8OybA+UUguFb2NhA7AQ9oFCw1s++NcCjlBTcyfsf+BilpqKM3D+YyFs/3fzYV88bAAAVlA4ILQAAACwBACdASoQABQAPu1iqU2ppaOiMAgBMB2JbACdMoMjkgzyQAehAPhnVt3dhJAAAP04x9OFLl+be1kR77BSGPfTybk2iDtm0jUZ5SEjc61So3eCJsgruFyIgx0qvUYMTpJg7BEMBqgBdQCuS3oeqrfpaFXP5aLoChaIi2XxK2bvHNUtlT1p0d34yPIDnb+q3bjGGaLcRO7L+6sluCBeHUxT9DNuORrv5Lq1tU1uWfyXVsTgAAA=",
    "avifSrcSet": "/images/decor/photo/monstera-2--w480.avif 480w, /images/decor/photo/monstera-2--w768.avif 768w, /images/decor/photo/monstera-2--w1037.avif 1037w",
    "webpSrcSet": "/images/decor/photo/monstera-2--w480.webp 480w, /images/decor/photo/monstera-2--w768.webp 768w, /images/decor/photo/monstera-2--w1037.webp 1037w"
  },
  "/images/decor/photo/monstera-3.png": {
    "width": 1000,
    "height": 780,
    "blurDataURL": "data:image/webp;base64,UklGRmwBAABXRUJQVlA4WAoAAAAQAAAADwAACwAAQUxQSLkAAAABgGrb1rFtn+f9/Kva9iWY8f++/NtMtm3bdrJt28h/MuN3ExGRAIjBJlQAFQUAIMQOVkmDWhxVVtzBAIbkm/Gukfio7hZ/YpB7Zo52Rk9XtPmCEUAcDf3PrT0f/LZm2oDAYP/1fPb28TqQP3ZhCwbZcE7XwcPmzfxyaJQOoLfQUNUYVdh/NLEuAwM8XnZq7ZHSPD9S3mUEAmeqyjjEVflH+2bEc5ATH24LUpiXnAYCIAJBPV4ICCytAABWUDggjAAAADACAJ0BKhAADAADgFolsAJ0ME5Ihkj6qdGAAPwbdlQa93U0s8Ojkz7cXWz7LjTp5y4ozzPkk+Shh++h+ntDsZ3eNqgDb1Ob+2h5wUC5pjE/+djQkFEvfNl/MzCkW5mIc8+2cAfmoJDRcfuyjEQfnWcvnD7vdEnCPy65emPHVNP8k9wJ8/89+NGL+AAA",
    "avifSrcSet": "/images/decor/photo/monstera-3--w480.avif 480w, /images/decor/photo/monstera-3--w768.avif 768w, /images/decor/photo/monstera-3--w1000.avif 1000w",
    "webpSrcSet": "/images/decor/photo/monstera-3--w480.webp 480w, /images/decor/photo/monstera-3--w768.webp 768w, /images/decor/photo/monstera-3--w1000.webp 1000w"
  },
  "/images/decor/photo/monstera-upright.png": {
    "width": 815,
    "height": 1280,
    "blurDataURL": "data:image/webp;base64,UklGRhICAABXRUJQVlA4WAoAAAAQAAAADwAAGAAAQUxQSCwBAAABkHNru2m78t+19kVnVTZidza7VHZSpbLtpHdp204627atfddaT5yImABJ1qjuxuNDU2SNJEWqu/07not1FBkpUpt3eOe+s6K8WMYqe05wARwje52yUvru3o8JEGg6ii7Schosx+G5l3eWnmoZM74+ITg2duNBjtrD85w5uMC1M8QtNYIvnCjahydw6NtKbXi1He5dJXhWteCkzrJ4DQ48xzSEHXrI5xHbcHg2TIjv9WlyEz5NvYQHz7HUJatXEofvX4DADE3i5FBc8BAcH+afgotlnwj8HoBvbNROHI71W3Eu5lm52nofU1tTXhu+86aNrObjWJer/nCjjiIpeej8Ds1KZYZta65IkpFRdV0lSMbqt4RElTWTjSKrPxtVtVWkfzSq7vg/pV1k/wRWUDggwAAAABAFAJ0BKhAAGQA+7WKpTamlo6IwCAEwHYlsAJ0vXUAA3iKuQqC4XdzXNf6EHb1srpgA/qKsZBF7+R043s0petQ+DapEE+DZ0GewciUSUHe8UCom+vlqHhEQ6vkYJ7e9Vgg2/EetYgF8CdXo/Av073n3AxKooOFwGXZpHjVc4zXT7iSixjutXJP7ceuP9ueVPtOqDzOQgWR29P3R5btcMwG9LZ8+JOmsgp9pI+LFw1v2JQ5TuH+R8GeQ7X5GT90AAA==",
    "avifSrcSet": "/images/decor/photo/monstera-upright--w480.avif 480w, /images/decor/photo/monstera-upright--w768.avif 768w, /images/decor/photo/monstera-upright--w815.avif 815w",
    "webpSrcSet": "/images/decor/photo/monstera-upright--w480.webp 480w, /images/decor/photo/monstera-upright--w768.webp 768w, /images/decor/photo/monstera-upright--w815.webp 815w"
  },
  "/images/decor/photo/monstera-vine.png": {
    "width": 1273,
    "height": 1280,
    "blurDataURL": "data:image/webp;base64,UklGRnQBAABXRUJQVlA4WAoAAAAQAAAADwAADwAAQUxQSOMAAAABkGvb1rFn+0VwA7ZZ2eqSLqVR2qlso3JKqzMrJ5Vt207e73ve8/MeImIC8G8Oxg3JEHn8m0cAI5Yjgv+fl1KhpGkdADwHDlHqhaSQ3/o0wHHg1NA5pN9L7yk3ixCN1CEg8vRoSn5cv3+G3e1+X3N65mT5FCkZPWutESMiSf6WaMN76rOCJKZUSIzGqmv9YHW+TTIRMYlqIAjwe38iRiQziYpgZYxciiYm0UvGFdnn0Zn/xDvC3ojO1JwD0UiPGfKDANeO+Vjw4CyaPxY+HyHgb0FEUMsh7ScBPA8eAMTk1dc8DgBWUDggagAAADACAJ0BKhAAEAADgFolsAJ0BiyNrfZvs3sAAP7xSd7f0ZYi9QGyANXcdQROfCWF6Qe5lA4jE9qvY2IbvqIL0W36WXowGfIERirIEmtslp/t18L3IBPtFlylj0gta7ZvtcMf7MM3HXWgAAA=",
    "avifSrcSet": "/images/decor/photo/monstera-vine--w480.avif 480w, /images/decor/photo/monstera-vine--w768.avif 768w, /images/decor/photo/monstera-vine--w1200.avif 1200w, /images/decor/photo/monstera-vine--w1273.avif 1273w",
    "webpSrcSet": "/images/decor/photo/monstera-vine--w480.webp 480w, /images/decor/photo/monstera-vine--w768.webp 768w, /images/decor/photo/monstera-vine--w1200.webp 1200w, /images/decor/photo/monstera-vine--w1273.webp 1273w"
  },
  "/images/decor/photo/palm-cluster.png": {
    "width": 1280,
    "height": 641,
    "blurDataURL": "data:image/webp;base64,UklGRigBAABXRUJQVlA4WAoAAAAQAAAADwAABwAAQUxQSHgAAAABgJtt2/HsfhGzstGZnbNABrAGyARpkz2MATSJe3b87X+HiEj8Y4QIlTL8IQTgGlc4mYqaAELAzNnWdHd/3ndiIATe9vLz4/OyaGaUIBA1Dp+fp0k9YDaZGIV+8XkelM1iodpsUwOa8TxnZCCccYmMAW4/Bygl+AdWUDggigAAADACAJ0BKhAACAADgFolsAJ0BiomYAXSkrAAAP7U67t20NvTcRdecdMeYkZWQhUuHoJz38t+HVXaBkjx5hMXCKHY7u3mfHZNqY0Folyh2nHrwaf8QNe6tws5hKB9HtRxD642sEhx2TBWPfo5ea3ph2xXvVdcczWTgvThuXnd8tcTd+W7T+J9vgAAAA==",
    "avifSrcSet": "/images/decor/photo/palm-cluster--w480.avif 480w, /images/decor/photo/palm-cluster--w768.avif 768w, /images/decor/photo/palm-cluster--w1200.avif 1200w, /images/decor/photo/palm-cluster--w1280.avif 1280w",
    "webpSrcSet": "/images/decor/photo/palm-cluster--w480.webp 480w, /images/decor/photo/palm-cluster--w768.webp 768w, /images/decor/photo/palm-cluster--w1200.webp 1200w, /images/decor/photo/palm-cluster--w1280.webp 1280w"
  },
  "/images/decor/photo/palm-frond.png": {
    "width": 1280,
    "height": 914,
    "blurDataURL": "data:image/webp;base64,UklGRvYAAABXRUJQVlA4WAoAAAAQAAAADwAACgAAQUxQSJQAAAABgJpt27Ll/q1p/PdQksMEMAAHCWawCTTy07S6pb/h7s2Tu8P7Phe6Q0RMgBQIKtx3ekPvzEahNqWAkkONs3ieHcZ+QPEiz9cY5t0Hi0GVPJvj708KShc38PbPS716+OBv84xGw8u4f3BMqeIAM8CMhzNq1M6H/ca5z7a6iJbg7hX87ofRrJAGly9HunmhqWG4VGEJVlA4IDwAAACwAQCdASoQAAsAA4BaJbAAAp2fuvloAP7zMGUJKxfQGf3CRJdpJsLKwq5Vw/tp6EF//taU93Z50hQkAAA=",
    "avifSrcSet": "/images/decor/photo/palm-frond--w480.avif 480w, /images/decor/photo/palm-frond--w768.avif 768w, /images/decor/photo/palm-frond--w1200.avif 1200w, /images/decor/photo/palm-frond--w1280.avif 1280w",
    "webpSrcSet": "/images/decor/photo/palm-frond--w480.webp 480w, /images/decor/photo/palm-frond--w768.webp 768w, /images/decor/photo/palm-frond--w1200.webp 1200w, /images/decor/photo/palm-frond--w1280.webp 1280w"
  },
  "/images/decor/photo/split-leaf-1.png": {
    "width": 1280,
    "height": 1186,
    "blurDataURL": "data:image/webp;base64,UklGRlABAABXRUJQVlA4WAoAAAAQAAAADwAADgAAQUxQSNUAAAABgLNt2/lV/vPPrpGTNv2a2mxMNdr21n/LrtmuSd/Atm3b7vd73nv6R0SSSofMGypJ8vD2syAVqbTJ6wpSOBRGFGkTmajP8GVcDpmxaEwq2+WvKfxZFOFfyCglrVnc9wEekVAg8OlEv/gvuEFbMADIqKcfRnILvk8AKP+opn2gW1IgwCzQb2CcCfHr2AgZwGwIOTRbDgHdhZAxK5Fd0ePzlPseFIAxpV5g4BczDWABDa7/wJ/CzCxfr0+0xruFVEEAYOylRIQl1q5NDh9o7OxePt3/5AEAVlA4IFQAAABQAgCdASoQAA8AA4BaJbACdLoAAzqVjtnrUIAA88z0Po83jfz5YnZO5jRz6ndJz7p62982X3RKM2xJ8VXh7K3jyXU5g8DRr8yOLRpfN1OQKrJaAAA=",
    "avifSrcSet": "/images/decor/photo/split-leaf-1--w480.avif 480w, /images/decor/photo/split-leaf-1--w768.avif 768w, /images/decor/photo/split-leaf-1--w1200.avif 1200w, /images/decor/photo/split-leaf-1--w1280.avif 1280w",
    "webpSrcSet": "/images/decor/photo/split-leaf-1--w480.webp 480w, /images/decor/photo/split-leaf-1--w768.webp 768w, /images/decor/photo/split-leaf-1--w1200.webp 1200w, /images/decor/photo/split-leaf-1--w1280.webp 1280w"
  },
  "/images/decor/photo/split-leaf-2.png": {
    "width": 1179,
    "height": 1280,
    "blurDataURL": "data:image/webp;base64,UklGRowBAABXRUJQVlA4WAoAAAAQAAAADwAAEAAAQUxQSO4AAAABkKNt27FHb2xtIJV62046Ox0rGwuwbY9t29PZtq3ve59rsImImAALaytl6VMabrHM57KC0RBloUL2/ORHpMdzXkS9epfUuvUH8ptrqhMK537kobUJBjlhMFf5q4xfApgc9HjE9YxHPfwGEUF7zfAr/dw8vwxTQLN2HEo21pki/C+C5uBBH+eotHjfNrQ2BOHlsYkk//iOWxgAwosqTADh7llEeOl2A41wOV9VYgovVcyubSutcW5+G7T8Z6H690yNrdwFQ35/56WligMB8ycfGq7wTFmqYQwQzoQvwktloew3/v74+WGD504+fL8LVlA4IHgAAAAwBACdASoQABEAPu1iqU2ppaOiMAgBMB2JagCdLwABZzQEGU63cXDbeIAA/r3BoQzr88R8ZoTk5gmcjFf1mZsuhjMOe0q6ICythZ9Lykj5sfUonGW3Uoj7hnhDfdhMK0eZWMm2vl9f/oIvFfL6//QRoX8e4coAAAA=",
    "avifSrcSet": "/images/decor/photo/split-leaf-2--w480.avif 480w, /images/decor/photo/split-leaf-2--w768.avif 768w, /images/decor/photo/split-leaf-2--w1179.avif 1179w",
    "webpSrcSet": "/images/decor/photo/split-leaf-2--w480.webp 480w, /images/decor/photo/split-leaf-2--w768.webp 768w, /images/decor/photo/split-leaf-2--w1179.webp 1179w"
  },
  "/images/gallery-1.jpg": {
    "width": 1066,
    "height": 1600,
    "blurDataURL": "data:image/webp;base64,UklGRsQAAABXRUJQVlA4ILgAAADwBACdASoQABgAPu1kqU2ppaOiMAgBMB2JbACdMoR3AdDpBwJvrdCJOyQBPAX3goAA/q7F3q8mtlnJOeW1shG8xbPeZ6EAOd3/biZSOX9mB5bXcjeppCAUdwP1zMyYiY4c/uLTS5eomU+r07UiLzWeyb7LE8yfDCbnsr3i07oKZPW4/r22OUsah2HxU5HRJMXSV/z899irkADb+tZQ5b7KJbWLa9rVdq+AH6qkc5obSD5GNPzk8AAA",
    "avifSrcSet": "/images/gallery-1--w480.avif 480w, /images/gallery-1--w768.avif 768w, /images/gallery-1--w1066.avif 1066w",
    "webpSrcSet": "/images/gallery-1--w480.webp 480w, /images/gallery-1--w768.webp 768w, /images/gallery-1--w1066.webp 1066w"
  },
  "/images/gallery-2.jpg": {
    "width": 1066,
    "height": 1600,
    "blurDataURL": "data:image/webp;base64,UklGRrwAAABXRUJQVlA4ILAAAABQBACdASoQABgAPu1iqU2ppaOiMAgBMB2JaACdAYx23vQRwwL3yYwgG95sAP54tuBk7x0RyNg2mWZFZZpcg67BzTcm70GsClLaRZSlX1ESoQVj0n1t5KiAQQXYSl+S0THo+kz/fMd5jc/CheXLYlzJd/TjxYd3t40ADRvmYvssWH2dMZbc3bpU43YT+ZTIAmSdjsir+uJesuxW5SzHba+8kDc9QITEkPNYkZiwr0hkAA==",
    "avifSrcSet": "/images/gallery-2--w480.avif 480w, /images/gallery-2--w768.avif 768w, /images/gallery-2--w1066.avif 1066w",
    "webpSrcSet": "/images/gallery-2--w480.webp 480w, /images/gallery-2--w768.webp 768w, /images/gallery-2--w1066.webp 1066w"
  },
  "/images/gallery-3.jpg": {
    "width": 1199,
    "height": 1600,
    "blurDataURL": "data:image/webp;base64,UklGRpwAAABXRUJQVlA4IJAAAABQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JbACdMoAluxFilQm82nPiefCAAPliJzBg1LDxLxW7rSPyKrgjHomckE/Y9uZbx4g5EMtVndtnxwTN+sSwnAD7F8d0wQ2jYES+ITorKzT7Gpm2GF/hh6Y1dYoiL20ZrwuxuNVhtuGxKpFfpN7rybu8x7Jp1/wkAAA=",
    "avifSrcSet": "/images/gallery-3--w480.avif 480w, /images/gallery-3--w768.avif 768w, /images/gallery-3--w1199.avif 1199w",
    "webpSrcSet": "/images/gallery-3--w480.webp 480w, /images/gallery-3--w768.webp 768w, /images/gallery-3--w1199.webp 1199w"
  },
  "/images/gallery-4.jpg": {
    "width": 1600,
    "height": 1066,
    "blurDataURL": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAAAwAgCdASoQAAsAA4BaJaACdAEDW7UzdI1fSAD+7OTVV3o5zoUtcsJFouNh3WFwdRBt2CecVEJ55pY/Ll8txbh43UahBOq/sfy8Dgc/43PtRjvx8KABMfRUIIAt7MZWuAA=",
    "avifSrcSet": "/images/gallery-4--w480.avif 480w, /images/gallery-4--w768.avif 768w, /images/gallery-4--w1200.avif 1200w, /images/gallery-4--w1600.avif 1600w",
    "webpSrcSet": "/images/gallery-4--w480.webp 480w, /images/gallery-4--w768.webp 768w, /images/gallery-4--w1200.webp 1200w, /images/gallery-4--w1600.webp 1600w"
  },
  "/images/gallery-5.jpg": {
    "width": 1066,
    "height": 1600,
    "blurDataURL": "data:image/webp;base64,UklGRrAAAABXRUJQVlA4IKQAAACQBACdASoQABgAPu1iqU2ppaQiMAgBMB2JZgCdAYxs1Zds7upW+FjIGFm16QAA/tREqKhVRtx1HM63gaa5TvVC6+Q9PQ0yB/mCw8ktWdn/WSpk6buN4cxCY/CkCfbEmTcHvY+v8GiK9CQN0L1UNfoqSkz5YRyyGkVQTfZcwNrSvGgV628NUvqD/PaAPLW8HoDz1m3ffCT4l9igyxfwmiWO/kAAAA==",
    "avifSrcSet": "/images/gallery-5--w480.avif 480w, /images/gallery-5--w768.avif 768w, /images/gallery-5--w1066.avif 1066w",
    "webpSrcSet": "/images/gallery-5--w480.webp 480w, /images/gallery-5--w768.webp 768w, /images/gallery-5--w1066.webp 1066w"
  },
  "/images/gallery-7.jpg": {
    "width": 1199,
    "height": 1600,
    "blurDataURL": "data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAABQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JYgBWAQ/4DzZaTv3PfzHuVhngAP7g2kvI3ZrH+o51VTGOMG9AXhp5y+bLob7EX/EnwQ9Hi+NPk9DUPVgDA61cd6JzDnQYiDMbGr+9LRXcOur7l1mFeWYLC0dzG2wK9V/DiG+Ktrw/xTuMckzXvupnzwAAAA==",
    "avifSrcSet": "/images/gallery-7--w480.avif 480w, /images/gallery-7--w768.avif 768w, /images/gallery-7--w1199.avif 1199w",
    "webpSrcSet": "/images/gallery-7--w480.webp 480w, /images/gallery-7--w768.webp 768w, /images/gallery-7--w1199.webp 1199w"
  },
  "/images/gallery-8.jpg": {
    "width": 1066,
    "height": 1600,
    "blurDataURL": "data:image/webp;base64,UklGRrIAAABXRUJQVlA4IKYAAABwBACdASoQABgAPu1iqU2ppaOiMAgBMB2JbACdAYv+yUo3Q1AEKTyAFdhPAAD+3I6RDLp+0BFhP+RKerMqcXiDATuF9B3wllCGkwrjVdYK1lAdHjTcDT6OGQN0QYhoeoO8KKnJFr+u1N1aUoWTNcKtk0k3gpXYIgPY13aSXWXviuLBHRVdW9TjeTRJBeVbu8tNWPAjIC3+S2RfgLAVdVBOxaW7GmAA",
    "avifSrcSet": "/images/gallery-8--w480.avif 480w, /images/gallery-8--w768.avif 768w, /images/gallery-8--w1066.avif 1066w",
    "webpSrcSet": "/images/gallery-8--w480.webp 480w, /images/gallery-8--w768.webp 768w, /images/gallery-8--w1066.webp 1066w"
  },
  "/images/hero-interior.jpg": {
    "width": 1199,
    "height": 1600,
    "blurDataURL": "data:image/webp;base64,UklGRqQAAABXRUJQVlA4IJgAAABwBACdASoQABUAPu1iqU2ppaOiMAgBMB2JbACdMoMYAEI8xjh+12jxK56cAAD88Z6uEjs+8Rwg+YRPbsAmY74LVjUk1zwFLnXvlUS2xls4soFXwr7VrgBydNGIKrL1adCO4KbvwRJNoflojg/6US//m2ZB6y4C2dF7MM7FGz+ahLewhBaZ9FNVA33ERIxs0mlhsh2uNMAAAA==",
    "avifSrcSet": "/images/hero-interior--w480.avif 480w, /images/hero-interior--w768.avif 768w, /images/hero-interior--w1199.avif 1199w",
    "webpSrcSet": "/images/hero-interior--w480.webp 480w, /images/hero-interior--w768.webp 768w, /images/hero-interior--w1199.webp 1199w"
  },
  "/images/ingredients/natural-sweetness.jpg": {
    "width": 600,
    "height": 600,
    "blurDataURL": "data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAABwAgCdASoQABAAA4BaJbACdAYulqicFIGRZ6wAAP7qTbEE0fxn3eTGwK5uV2Wjk3e3kFMeEiSAHRFXpczEW8e00xdFgXuMyQDROj77JZ6RTZGypf1v+1Auj2S3ScO8/vJ4lx3d3KGK8qHr9KKtExZXm577T2inyuAAAA==",
    "avifSrcSet": "/images/ingredients/natural-sweetness--w480.avif 480w, /images/ingredients/natural-sweetness--w600.avif 600w",
    "webpSrcSet": "/images/ingredients/natural-sweetness--w480.webp 480w, /images/ingredients/natural-sweetness--w600.webp 600w"
  },
  "/images/ingredients/no-frying.jpg": {
    "width": 1264,
    "height": 848,
    "blurDataURL": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAAAwAgCdASoQAAsAA4BaJQBdgMYYnMohT5rDwAD+6qnij6a1r38t4Vd/Le3oJJJVaxtfqqpvsETHV5Vcla6Uwov7t3dV1poMiqdaTtMs57XgIlZRtJpd0v3MpuACUAAA",
    "avifSrcSet": "/images/ingredients/no-frying--w480.avif 480w, /images/ingredients/no-frying--w768.avif 768w, /images/ingredients/no-frying--w1200.avif 1200w, /images/ingredients/no-frying--w1264.avif 1264w",
    "webpSrcSet": "/images/ingredients/no-frying--w480.webp 480w, /images/ingredients/no-frying--w768.webp 768w, /images/ingredients/no-frying--w1200.webp 1200w, /images/ingredients/no-frying--w1264.webp 1264w"
  },
  "/images/ingredients/olive-oil.jpg": {
    "width": 1264,
    "height": 848,
    "blurDataURL": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAACwAQCdASoQAAsAA4BaJYgC7ABZnQAAAP5kaJfqtZWvHxB4d9FMxuXrtExXishOAqQV+7M2su+EWT91V5vUHyHSH2AAAA==",
    "avifSrcSet": "/images/ingredients/olive-oil--w480.avif 480w, /images/ingredients/olive-oil--w768.avif 768w, /images/ingredients/olive-oil--w1200.avif 1200w, /images/ingredients/olive-oil--w1264.avif 1264w",
    "webpSrcSet": "/images/ingredients/olive-oil--w480.webp 480w, /images/ingredients/olive-oil--w768.webp 768w, /images/ingredients/olive-oil--w1200.webp 1200w, /images/ingredients/olive-oil--w1264.webp 1264w"
  },
  "/images/ingredients/plant-milk.jpg": {
    "width": 1264,
    "height": 848,
    "blurDataURL": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAACwAQCdASoQAAsAA4BaJQBWAB0ytz5AAP7qqhEnNpfFjJfakj3rOP0cXhPHC6e8MU7JM/460jvvmk8hVRPafsJOuJvjMSigclU9j84sTeabDkPQerkhlm8i1Z4ageQlWGXAAA==",
    "avifSrcSet": "/images/ingredients/plant-milk--w480.avif 480w, /images/ingredients/plant-milk--w768.avif 768w, /images/ingredients/plant-milk--w1200.avif 1200w, /images/ingredients/plant-milk--w1264.avif 1264w",
    "webpSrcSet": "/images/ingredients/plant-milk--w480.webp 480w, /images/ingredients/plant-milk--w768.webp 768w, /images/ingredients/plant-milk--w1200.webp 1200w, /images/ingredients/plant-milk--w1264.webp 1264w"
  },
  "/images/ingredients/sourdough.jpg": {
    "width": 600,
    "height": 600,
    "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAAAQAgCdASoQABAAA4BaJYgC7AEO/vBv/ijQAP75DkOsNb7Xc0DGlcKQzLBOmg6W1tG+ZTifvas2FcmzWWK3gwsSqLtLeHNc+X7IAA==",
    "avifSrcSet": "/images/ingredients/sourdough--w480.avif 480w, /images/ingredients/sourdough--w600.avif 600w",
    "webpSrcSet": "/images/ingredients/sourdough--w480.webp 480w, /images/ingredients/sourdough--w600.webp 600w"
  },
  "/images/ingredients/whole-grains.jpg": {
    "width": 600,
    "height": 600,
    "blurDataURL": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAABQAgCdASoQABAAA4BaJZgCdH8AF77/bdJ/5YAA/vQrY+mZtxPE1Z1ya/lgRSOo1aQSr8c7turkq8xMl6MxSJRK1bxawF8yMO/iGppGZVz9glpxCvkAhyuLB6O6w1jyGArQAA==",
    "avifSrcSet": "/images/ingredients/whole-grains--w480.avif 480w, /images/ingredients/whole-grains--w600.avif 600w",
    "webpSrcSet": "/images/ingredients/whole-grains--w480.webp 480w, /images/ingredients/whole-grains--w600.webp 600w"
  },
  "/images/keep-rising-2.jpg": {
    "width": 1080,
    "height": 1439,
    "blurDataURL": "data:image/webp;base64,UklGRqgAAABXRUJQVlA4IJwAAACwBACdASoQABUAPu1iqU2ppaOiMAgBMB2JZAC2yywTnAnN05mFHUUJbEh4Un4AAP6iElADtG670rKEraC6PepbZmkvDUhxZtWrTQyRkDf0223yVNNgQ6ef4Rs3uSSz2GCMTgKu1c24Arh2dyOxWFt2y/Ad7oi8+4467Q7EMHMnqgRChiw57Q9KdkGDMqccEtbgkyPG7GelBdS1MAA=",
    "avifSrcSet": "/images/keep-rising-2--w480.avif 480w, /images/keep-rising-2--w768.avif 768w, /images/keep-rising-2--w1080.avif 1080w",
    "webpSrcSet": "/images/keep-rising-2--w480.webp 480w, /images/keep-rising-2--w768.webp 768w, /images/keep-rising-2--w1080.webp 1080w"
  },
  "/images/keep-rising-team.jpg": {
    "width": 1080,
    "height": 1440,
    "blurDataURL": "data:image/webp;base64,UklGRpYAAABXRUJQVlA4IIoAAAAwBACdASoQABUAPu1iqU2ppaOiMAgBMB2JYwCdAYvq1fCHVHEyba8o+QAA2/jzhFOuXNCjjSBmbD0OPqKsAgVDxyXu/IFAnJdQiO6A71GTfYSY92wUYNF46eW8dDfPXRBCC/CH16cubq43ajSBvFpiea5OwyDbJpkB32pbSG7cpbyxlbJcRDjwAAA=",
    "avifSrcSet": "/images/keep-rising-team--w480.avif 480w, /images/keep-rising-team--w768.avif 768w, /images/keep-rising-team--w1080.avif 1080w",
    "webpSrcSet": "/images/keep-rising-team--w480.webp 480w, /images/keep-rising-team--w768.webp 768w, /images/keep-rising-team--w1080.webp 1080w"
  },
  "/images/keep-rising.jpg": {
    "width": 841,
    "height": 1115,
    "blurDataURL": "data:image/webp;base64,UklGRo4AAABXRUJQVlA4IIIAAACwAwCdASoQABUAPu1kq04ppaQiMAgBMB2JaAAAUvzYkJc5U832AAD+vhUT36eLtXu3X7zFoeeFXw+pjTN535QntUnloAsyYfxGxG0o1kD8XHHUyWr5JoTTjJdxrW37Yq1F+4PSYa93/UwRQEqh0X45w2UPi0jgM+eWf9PrzykaAAAA",
    "avifSrcSet": "/images/keep-rising--w480.avif 480w, /images/keep-rising--w768.avif 768w, /images/keep-rising--w841.avif 841w",
    "webpSrcSet": "/images/keep-rising--w480.webp 480w, /images/keep-rising--w768.webp 768w, /images/keep-rising--w841.webp 841w"
  },
  "/images/menu-vegan-poke.jpg": {
    "width": 1024,
    "height": 1024,
    "blurDataURL": "data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAADQAgCdASoQABAAA4BaJbACdH8EwADk/RaDVjx0VS6AAP7c27S0Go16tMe1j/+whrTlwrUvEPefvHdCAJvKysdqZjskXWImFABlO/omkQi7hwOfrq4zosYPRJgvAfcGkHhVy4Hnel2SIQZv9OvEKLv85hdc8bwefuhtn/3R/RV5kYphyWoJBiKXEoAAAA==",
    "avifSrcSet": "/images/menu-vegan-poke--w480.avif 480w, /images/menu-vegan-poke--w768.avif 768w, /images/menu-vegan-poke--w1024.avif 1024w",
    "webpSrcSet": "/images/menu-vegan-poke--w480.webp 480w, /images/menu-vegan-poke--w768.webp 768w, /images/menu-vegan-poke--w1024.webp 1024w"
  },
  "/images/menu/all-red-on-toast.jpg": {
    "width": 2048,
    "height": 1536,
    "blurDataURL": "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAACQAgCdASoQAAwAA4BaJbACdH8AgmigbUM0HLU+AAD+8bRG1trKH0VVv4q4ilKEgUnjR96kVzcZ3YGe3Z34dCWVO9dgd1Dw0Buz97+XDeHhg9NoC87Pwh6aeyk24kNWOw5Q2W7HrWqwvnInv79CAAAA",
    "avifSrcSet": "/images/menu/all-red-on-toast--w480.avif 480w, /images/menu/all-red-on-toast--w768.avif 768w, /images/menu/all-red-on-toast--w1200.avif 1200w, /images/menu/all-red-on-toast--w1600.avif 1600w, /images/menu/all-red-on-toast--w2048.avif 2048w",
    "webpSrcSet": "/images/menu/all-red-on-toast--w480.webp 480w, /images/menu/all-red-on-toast--w768.webp 768w, /images/menu/all-red-on-toast--w1200.webp 1200w, /images/menu/all-red-on-toast--w1600.webp 1600w, /images/menu/all-red-on-toast--w2048.webp 2048w"
  },
  "/images/menu/apaki-on-toast.jpg": {
    "width": 2048,
    "height": 1536,
    "blurDataURL": "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAABwAgCdASoQAAwAA4BaJbACdH8AFwbq0xuptqgAAP7xukDvpP5z4lj3GqC65bGWKejWnGJajk+v51QUwdyEYQN05vmNlwmq+frDgaAZpm/GbXLz0HQLU2Mvh60t14wURobzKgS8dI89dpvklKmQAAAA",
    "avifSrcSet": "/images/menu/apaki-on-toast--w480.avif 480w, /images/menu/apaki-on-toast--w768.avif 768w, /images/menu/apaki-on-toast--w1200.avif 1200w, /images/menu/apaki-on-toast--w1600.avif 1600w, /images/menu/apaki-on-toast--w2048.avif 2048w",
    "webpSrcSet": "/images/menu/apaki-on-toast--w480.webp 480w, /images/menu/apaki-on-toast--w768.webp 768w, /images/menu/apaki-on-toast--w1200.webp 1200w, /images/menu/apaki-on-toast--w1600.webp 1600w, /images/menu/apaki-on-toast--w2048.webp 2048w"
  },
  "/images/menu/drink-yellow-lemon-poster.jpg": {
    "width": 720,
    "height": 966,
    "blurDataURL": "data:image/webp;base64,UklGRpwAAABXRUJQVlA4IJAAAAAQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JbACdMoADYjTy1czSmaL6AAD+7GwK8qG+09a3HowThCREXOu46Yj/KOw6ydXflY3R993r9W7sDmOZBsyHoGhgAXigMam3gFxuFt43UfLq2vxBizr06G2zk5sgqn+xaxRjzyoIDpHcSVB9Dmu9OC5L6HO0BETIAAA=",
    "avifSrcSet": "/images/menu/drink-yellow-lemon-poster--w480.avif 480w, /images/menu/drink-yellow-lemon-poster--w720.avif 720w",
    "webpSrcSet": "/images/menu/drink-yellow-lemon-poster--w480.webp 480w, /images/menu/drink-yellow-lemon-poster--w720.webp 720w"
  },
  "/images/menu/glyka-0001.jpg": {
    "width": 1600,
    "height": 1200,
    "blurDataURL": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAAAQAgCdASoQAAwAA4BaJZACdAEQN5g1DbwAAP73mYQAO9CNQ42HIl7N3yFP4s8eG4gDhMbnBxhJPzPblLyHhFH0wi5U2kzzyeJsqd8/L/EuTN9gyOZelNfqsX3N6AAA",
    "avifSrcSet": "/images/menu/glyka-0001--w480.avif 480w, /images/menu/glyka-0001--w768.avif 768w, /images/menu/glyka-0001--w1200.avif 1200w, /images/menu/glyka-0001--w1600.avif 1600w",
    "webpSrcSet": "/images/menu/glyka-0001--w480.webp 480w, /images/menu/glyka-0001--w768.webp 768w, /images/menu/glyka-0001--w1200.webp 1200w, /images/menu/glyka-0001--w1600.webp 1600w"
  },
  "/images/menu/glyka-0002.jpg": {
    "width": 1600,
    "height": 1200,
    "blurDataURL": "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAABwAgCdASoQAAwAA4BaJbACdH8AgoC/UIxA7+IAAP7y2Axt/QT62qHuxon6sQ4j47ayqetEIDawY2nU7e/wZSprm7P7XQjdbeI9W15khqaMYZyLq26UBKq04qk8jhBr8F2mS23GpUgtHqAA",
    "avifSrcSet": "/images/menu/glyka-0002--w480.avif 480w, /images/menu/glyka-0002--w768.avif 768w, /images/menu/glyka-0002--w1200.avif 1200w, /images/menu/glyka-0002--w1600.avif 1600w",
    "webpSrcSet": "/images/menu/glyka-0002--w480.webp 480w, /images/menu/glyka-0002--w768.webp 768w, /images/menu/glyka-0002--w1200.webp 1200w, /images/menu/glyka-0002--w1600.webp 1600w"
  },
  "/images/menu/glyka-0003.jpg": {
    "width": 1600,
    "height": 1200,
    "blurDataURL": "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAACQAgCdASoQAAwAA4BaJbACdGaA2wAp8SpzTOHxgAD+72hgNeD6gJxBDzVIyHUp3VUJpeLfR7oUMqc9io5BXZ7FRyhIng6t1u3c0xHr8G50qdPcD4MgJ4QQpqe2eeT8kQ9boxmz1kmCjerOqjUXX0AA",
    "avifSrcSet": "/images/menu/glyka-0003--w480.avif 480w, /images/menu/glyka-0003--w768.avif 768w, /images/menu/glyka-0003--w1200.avif 1200w, /images/menu/glyka-0003--w1600.avif 1600w",
    "webpSrcSet": "/images/menu/glyka-0003--w480.webp 480w, /images/menu/glyka-0003--w768.webp 768w, /images/menu/glyka-0003--w1200.webp 1200w, /images/menu/glyka-0003--w1600.webp 1600w"
  },
  "/images/menu/glyka-0004.jpg": {
    "width": 1600,
    "height": 1200,
    "blurDataURL": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAABQAgCdASoQAAwAA4BaJZACdAEN+hXfK0A7wGAA/vRd/ECuL725q7XH5pXO/B881zQ1kwAA9VyVbg9uIJ2HKG3N3XD6rRF06ycA5DDw9bNWNe64/k5ybQEPtM4yzACEQCpdAAAA",
    "avifSrcSet": "/images/menu/glyka-0004--w480.avif 480w, /images/menu/glyka-0004--w768.avif 768w, /images/menu/glyka-0004--w1200.avif 1200w, /images/menu/glyka-0004--w1600.avif 1600w",
    "webpSrcSet": "/images/menu/glyka-0004--w480.webp 480w, /images/menu/glyka-0004--w768.webp 768w, /images/menu/glyka-0004--w1200.webp 1200w, /images/menu/glyka-0004--w1600.webp 1600w"
  },
  "/images/menu/glyka-0005.jpg": {
    "width": 1600,
    "height": 1200,
    "blurDataURL": "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAABwAgCdASoQAAwAA4BaJZgC7AYuH25P8i32FgYAAP7tK3IdblZ0lzFdMgzdlvEMBMOP4Xl9ILlLLQBV9HAzR71Jw9P19JqH4hl0eIEI5fKjGIsGuh4XB08m+QBkx6KJkX5kGtMUpWfI5bIX3zkMsBluSJcAAA==",
    "avifSrcSet": "/images/menu/glyka-0005--w480.avif 480w, /images/menu/glyka-0005--w768.avif 768w, /images/menu/glyka-0005--w1200.avif 1200w, /images/menu/glyka-0005--w1600.avif 1600w",
    "webpSrcSet": "/images/menu/glyka-0005--w480.webp 480w, /images/menu/glyka-0005--w768.webp 768w, /images/menu/glyka-0005--w1200.webp 1200w, /images/menu/glyka-0005--w1600.webp 1600w"
  },
  "/images/menu/glyka-0006.jpg": {
    "width": 1600,
    "height": 1200,
    "blurDataURL": "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAAAwAgCdASoQAAwAA4BaJYgCdAD6PYGkoBbwAAD+7R7t/VCuh5BzsQ2quNxhDbbuU1QvtrMZmp4jG3XOlcml6RgBRC8mIUDfE293uw0j2atftM+hRRz3AoB8z4m7DMYojN/8OsogL9lhisWyCCig4wAA",
    "avifSrcSet": "/images/menu/glyka-0006--w480.avif 480w, /images/menu/glyka-0006--w768.avif 768w, /images/menu/glyka-0006--w1200.avif 1200w, /images/menu/glyka-0006--w1600.avif 1600w",
    "webpSrcSet": "/images/menu/glyka-0006--w480.webp 480w, /images/menu/glyka-0006--w768.webp 768w, /images/menu/glyka-0006--w1200.webp 1200w, /images/menu/glyka-0006--w1600.webp 1600w"
  },
  "/images/menu/glyka-0007.jpg": {
    "width": 1600,
    "height": 1200,
    "blurDataURL": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAABwAgCdASoQAAwAA4BaJbACdAYtzqwFZ87DtsgAAP7zULjiAFH0q5fVkP7xDb/qvkpFa3RRjMHSDYD/uqAeXzn4Hmqq7FjSQLvViDhn4D/vfAF0uFP24qkjnIm4ZPC5lbwHK8W4QAA=",
    "avifSrcSet": "/images/menu/glyka-0007--w480.avif 480w, /images/menu/glyka-0007--w768.avif 768w, /images/menu/glyka-0007--w1200.avif 1200w, /images/menu/glyka-0007--w1600.avif 1600w",
    "webpSrcSet": "/images/menu/glyka-0007--w480.webp 480w, /images/menu/glyka-0007--w768.webp 768w, /images/menu/glyka-0007--w1200.webp 1200w, /images/menu/glyka-0007--w1600.webp 1600w"
  },
  "/images/menu/glyka-0008.jpg": {
    "width": 1600,
    "height": 1200,
    "blurDataURL": "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAAAwAgCdASoQAAwAA4BaJZACdAYuRSXXZCXqAAD+9e7pIvB8H6Oaj8xcN2TXtywsZTBPhsKTVD3CV9RCsqmBBK7/gm1B3OB5m3IXyjCY9uEXCsIFmpf1FsNdD3/61vuSbe7XnWF9hj5fdPgfjblAAA==",
    "avifSrcSet": "/images/menu/glyka-0008--w480.avif 480w, /images/menu/glyka-0008--w768.avif 768w, /images/menu/glyka-0008--w1200.avif 1200w, /images/menu/glyka-0008--w1600.avif 1600w",
    "webpSrcSet": "/images/menu/glyka-0008--w480.webp 480w, /images/menu/glyka-0008--w768.webp 768w, /images/menu/glyka-0008--w1200.webp 1200w, /images/menu/glyka-0008--w1600.webp 1600w"
  },
  "/images/menu/kokteil-0001.jpg": {
    "width": 1600,
    "height": 2134,
    "blurDataURL": "data:image/webp;base64,UklGRpwAAABXRUJQVlA4IJAAAADwAwCdASoQABUAPu1iqU2ppaOiMAgBMB2JbACdABxN5eaUHhbkeMbQAP7usWT62FwC7EPL5btIhkAjUJB06QL2F5SqveFtHXj1wApCTr/032k6oofLAVNQHiZX5nrXIgMUsMc5pjNLhj82slVc7/A+eNcZkxw5icR+m+sCSuXkMx7us7tDNfuw8U21k5ygAAA=",
    "avifSrcSet": "/images/menu/kokteil-0001--w480.avif 480w, /images/menu/kokteil-0001--w768.avif 768w, /images/menu/kokteil-0001--w1200.avif 1200w, /images/menu/kokteil-0001--w1600.avif 1600w",
    "webpSrcSet": "/images/menu/kokteil-0001--w480.webp 480w, /images/menu/kokteil-0001--w768.webp 768w, /images/menu/kokteil-0001--w1200.webp 1200w, /images/menu/kokteil-0001--w1600.webp 1600w"
  },
  "/images/menu/kokteil-0003.jpg": {
    "width": 1600,
    "height": 2133,
    "blurDataURL": "data:image/webp;base64,UklGRpwAAABXRUJQVlA4IJAAAABQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JbACdMoAvQBrCztWP1XuAP2cAAP7wy97EXq8PTp+JSL0x0UjGlfSCb7+uFL4GQdDomtU7UBXgIrYh0zt/mM2qEiuG7a0o76cR3xS2hbV05CPgngFvOFIb897loJ14jCyeGQfH0nFyBVxsprvJmAck57sNMXpDAAA=",
    "avifSrcSet": "/images/menu/kokteil-0003--w480.avif 480w, /images/menu/kokteil-0003--w768.avif 768w, /images/menu/kokteil-0003--w1200.avif 1200w, /images/menu/kokteil-0003--w1600.avif 1600w",
    "webpSrcSet": "/images/menu/kokteil-0003--w480.webp 480w, /images/menu/kokteil-0003--w768.webp 768w, /images/menu/kokteil-0003--w1200.webp 1200w, /images/menu/kokteil-0003--w1600.webp 1600w"
  },
  "/images/menu/kokteil-0005.jpg": {
    "width": 1600,
    "height": 2133,
    "blurDataURL": "data:image/webp;base64,UklGRqAAAABXRUJQVlA4IJQAAAAQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JbACdMoADQMEpbbocOjJ9AAD+7BEiEAsvA0Vv01Bg+DSuHKjddRLW6LFXRgbT1S/RLcixGijASyBPcHGZILay1EgGywQ+s2h0xUNUMzeDzRzwM1D3/+p6JoNnD9EZu93BvGs/zFFZ/Ux/S2U90vy3zF2yDPxR3fcGHqwA",
    "avifSrcSet": "/images/menu/kokteil-0005--w480.avif 480w, /images/menu/kokteil-0005--w768.avif 768w, /images/menu/kokteil-0005--w1200.avif 1200w, /images/menu/kokteil-0005--w1600.avif 1600w",
    "webpSrcSet": "/images/menu/kokteil-0005--w480.webp 480w, /images/menu/kokteil-0005--w768.webp 768w, /images/menu/kokteil-0005--w1200.webp 1200w, /images/menu/kokteil-0005--w1600.webp 1600w"
  },
  "/images/menu/kokteil-0006.jpg": {
    "width": 1600,
    "height": 2133,
    "blurDataURL": "data:image/webp;base64,UklGRqoAAABXRUJQVlA4IJ4AAABQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JbACsLwAB058zNrGESy8xEfRAAP7sbAr7jGoQfxi49GCpOZBv1etYG9XpxeSPfMFutmOE5tilKLSKb1+37HSy2NWbts1LlHw5k6ZdOHrzMginzlHONYe0/EP0Y2pbREXhYNZGBaaj+I9/uYlbDB/ghkuxb7lw8FV+xXJaSfFbEP1htKAAAA==",
    "avifSrcSet": "/images/menu/kokteil-0006--w480.avif 480w, /images/menu/kokteil-0006--w768.avif 768w, /images/menu/kokteil-0006--w1200.avif 1200w, /images/menu/kokteil-0006--w1600.avif 1600w",
    "webpSrcSet": "/images/menu/kokteil-0006--w480.webp 480w, /images/menu/kokteil-0006--w768.webp 768w, /images/menu/kokteil-0006--w1200.webp 1200w, /images/menu/kokteil-0006--w1600.webp 1600w"
  },
  "/images/menu/kokteil-0007.jpg": {
    "width": 1600,
    "height": 2134,
    "blurDataURL": "data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAACQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JbACdMoRwACaMuPfvLJACys7HhoAA/u6vMmlQcsuElDbKbd8pKREA0dvDmOBYSqm+y9FxX7ryOoowpkXOb/Wfvt7M37BMC9ph/eMyXOeVqxanfWavLm3lFl2hs+EZC116NUVcy/98pDBs+BWIOGF3t6A/RCAA",
    "avifSrcSet": "/images/menu/kokteil-0007--w480.avif 480w, /images/menu/kokteil-0007--w768.avif 768w, /images/menu/kokteil-0007--w1200.avif 1200w, /images/menu/kokteil-0007--w1600.avif 1600w",
    "webpSrcSet": "/images/menu/kokteil-0007--w480.webp 480w, /images/menu/kokteil-0007--w768.webp 768w, /images/menu/kokteil-0007--w1200.webp 1200w, /images/menu/kokteil-0007--w1600.webp 1600w"
  },
  "/images/menu/kokteil-0008.jpg": {
    "width": 1600,
    "height": 2133,
    "blurDataURL": "data:image/webp;base64,UklGRqoAAABXRUJQVlA4IJ4AAACwBACdASoQABUAPu1iqU2ppaOiMAgBMB2JbACdMoR4GCXf7sehR9E6/cPXjVFYAP7uq/oxihyuQBz/fb4UCN8wgqhWh8jwargLQzXuK1EVeYksoMAh6d+s6RQ5a7QIHkygFbWRig/+O58hixKg9cVxnz0Gt8nS42+cNRx/84O+pjygUKOCo31U5pj1riYaIDKAyyigcXq81+BrqGaAAA==",
    "avifSrcSet": "/images/menu/kokteil-0008--w480.avif 480w, /images/menu/kokteil-0008--w768.avif 768w, /images/menu/kokteil-0008--w1200.avif 1200w, /images/menu/kokteil-0008--w1600.avif 1600w",
    "webpSrcSet": "/images/menu/kokteil-0008--w480.webp 480w, /images/menu/kokteil-0008--w768.webp 768w, /images/menu/kokteil-0008--w1200.webp 1200w, /images/menu/kokteil-0008--w1600.webp 1600w"
  },
  "/images/menu/piata-0009.jpg": {
    "width": 1600,
    "height": 1200,
    "blurDataURL": "data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAADQAgCdASoQAAwAA4BaJbACdDiAN5AIjgoG8azbmiykAP7xs16Z9zmaiT1dqz/ed+kA4oAYpuH6dipDAURRE1SEKPWbgUD3qYuaDyU6/NuuKridtr8yTr3h1mL/27qaH0Gb7uXpsya0v6QBIdN9F4PfavkX9pjyK+gAAA==",
    "avifSrcSet": "/images/menu/piata-0009--w480.avif 480w, /images/menu/piata-0009--w768.avif 768w, /images/menu/piata-0009--w1200.avif 1200w, /images/menu/piata-0009--w1600.avif 1600w",
    "webpSrcSet": "/images/menu/piata-0009--w480.webp 480w, /images/menu/piata-0009--w768.webp 768w, /images/menu/piata-0009--w1200.webp 1200w, /images/menu/piata-0009--w1600.webp 1600w"
  },
  "/images/menu/piata-0013.jpg": {
    "width": 1600,
    "height": 1200,
    "blurDataURL": "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAABwAgCdASoQAAwAA4BaJbACdH8AGTrdhopg7vRAAP70tprbz34HPZGPUAummnpar2ejSHI2ZiBEQjkkt4Vf6/DB5FUMm4NlVp2qUbrXxzpDyq2XKQPqhZ4RER0ff42G4SArZv9q6XhwbAAA",
    "avifSrcSet": "/images/menu/piata-0013--w480.avif 480w, /images/menu/piata-0013--w768.avif 768w, /images/menu/piata-0013--w1200.avif 1200w, /images/menu/piata-0013--w1600.avif 1600w",
    "webpSrcSet": "/images/menu/piata-0013--w480.webp 480w, /images/menu/piata-0013--w768.webp 768w, /images/menu/piata-0013--w1200.webp 1200w, /images/menu/piata-0013--w1600.webp 1600w"
  },
  "/images/menu/piata-0015.jpg": {
    "width": 1600,
    "height": 1200,
    "blurDataURL": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAABwAgCdASoQAAwAA4BaJbACdAYv1d0XexZgraGAAP7zXum0E1JvR/uRV9jr7NHwJZThYkngQ8uAu3eVCrTVMuKK6fYwMIBoK2F7zQMS8CkglJ12/dly8hv/4RgZWvUc5PYjhazcDhKAAA==",
    "avifSrcSet": "/images/menu/piata-0015--w480.avif 480w, /images/menu/piata-0015--w768.avif 768w, /images/menu/piata-0015--w1200.avif 1200w, /images/menu/piata-0015--w1600.avif 1600w",
    "webpSrcSet": "/images/menu/piata-0015--w480.webp 480w, /images/menu/piata-0015--w768.webp 768w, /images/menu/piata-0015--w1200.webp 1200w, /images/menu/piata-0015--w1600.webp 1600w"
  },
  "/images/menu/piata-0016.jpg": {
    "width": 1600,
    "height": 1200,
    "blurDataURL": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAABwAgCdASoQAAwAA4BaJbACdH8AGZaPcbQ5M5sAAP7zY0zhBQjdJefmsWT5oJxnR4sRbO1KjMklH3g1+6d/M9mwrIET+PEtMevG9Noq0pqjDtm4eCPKfUKxn4if2NgYLt3WLRQtVsIAAA==",
    "avifSrcSet": "/images/menu/piata-0016--w480.avif 480w, /images/menu/piata-0016--w768.avif 768w, /images/menu/piata-0016--w1200.avif 1200w, /images/menu/piata-0016--w1600.avif 1600w",
    "webpSrcSet": "/images/menu/piata-0016--w480.webp 480w, /images/menu/piata-0016--w768.webp 768w, /images/menu/piata-0016--w1200.webp 1200w, /images/menu/piata-0016--w1600.webp 1600w"
  },
  "/images/menu/piata-0018.jpg": {
    "width": 1600,
    "height": 1200,
    "blurDataURL": "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAABQAgCdASoQAAwAA4BaJbACdH8AgqSlMzuQpEAA/vG6B1vMs9Bty/oUA0Pi7tyxE7o9GmreilMe6CKYQA+Oo3dQmM1qNLmZbmMH28ukjwRq3g84X3tXaZgJlHuJ5abJuRKt+QN4/ne1zCoiZWYodF1+95OgAA==",
    "avifSrcSet": "/images/menu/piata-0018--w480.avif 480w, /images/menu/piata-0018--w768.avif 768w, /images/menu/piata-0018--w1200.avif 1200w, /images/menu/piata-0018--w1600.avif 1600w",
    "webpSrcSet": "/images/menu/piata-0018--w480.webp 480w, /images/menu/piata-0018--w768.webp 768w, /images/menu/piata-0018--w1200.webp 1200w, /images/menu/piata-0018--w1600.webp 1600w"
  },
  "/images/menu/piata-0020.jpg": {
    "width": 1600,
    "height": 1200,
    "blurDataURL": "data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAADwAgCdASoQAAwAA4BaJbACdH8KsBXALszHKKbbB0qbIAD+7SAH43YTJce4ERNTXAAeT7ENwXeFTnqRvYwLkNxHMnByGmdnWttWFl79UD2MDByVNoC30PqDrhzgedTRsy6DJtonf+15UHDaDWAWvHYWUY/x2ArSDxOlQAAA",
    "avifSrcSet": "/images/menu/piata-0020--w480.avif 480w, /images/menu/piata-0020--w768.avif 768w, /images/menu/piata-0020--w1200.avif 1200w, /images/menu/piata-0020--w1600.avif 1600w",
    "webpSrcSet": "/images/menu/piata-0020--w480.webp 480w, /images/menu/piata-0020--w768.webp 768w, /images/menu/piata-0020--w1200.webp 1200w, /images/menu/piata-0020--w1600.webp 1600w"
  },
  "/images/menu/piata-0022.jpg": {
    "width": 1600,
    "height": 1200,
    "blurDataURL": "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAAAwAgCdASoQAAwAA4BaJbACdH8AEWTD6n/wAAD+9uDvJnslDp1w3evtzzWkhxQkqtRgbhiX+w4wsjhEAcaFkHDd9C1+Ke9HI/ZAHmRSv1+XUVnLU5SaVkjRR2Dw/OpDcB6K0L7vwf5EAwKgAAA=",
    "avifSrcSet": "/images/menu/piata-0022--w480.avif 480w, /images/menu/piata-0022--w768.avif 768w, /images/menu/piata-0022--w1200.avif 1200w, /images/menu/piata-0022--w1600.avif 1600w",
    "webpSrcSet": "/images/menu/piata-0022--w480.webp 480w, /images/menu/piata-0022--w768.webp 768w, /images/menu/piata-0022--w1200.webp 1200w, /images/menu/piata-0022--w1600.webp 1600w"
  },
  "/images/menu/piata-0025.jpg": {
    "width": 1600,
    "height": 1200,
    "blurDataURL": "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAADwAgCdASoQAAwAA4BaJbACdH8EwAbyIRD5WrAfErgOAAD+9uDvFMYiu+MDtgSpXawT3SOuoe81UP+RYcr21nmPfCzrbE+8fofQQ0ERCy/cQj7bjYrv5Spk0t0J9V/5286DnF/aZuB0+fbud2xZQk4AAAA=",
    "avifSrcSet": "/images/menu/piata-0025--w480.avif 480w, /images/menu/piata-0025--w768.avif 768w, /images/menu/piata-0025--w1200.avif 1200w, /images/menu/piata-0025--w1600.avif 1600w",
    "webpSrcSet": "/images/menu/piata-0025--w480.webp 480w, /images/menu/piata-0025--w768.webp 768w, /images/menu/piata-0025--w1200.webp 1200w, /images/menu/piata-0025--w1600.webp 1600w"
  },
  "/images/menu/piata-0028.jpg": {
    "width": 1600,
    "height": 1200,
    "blurDataURL": "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAABQAgCdASoQAAwAA4BaJbACdAYtfdYyeIDnU/gA/vNREwTz2LPBpOhpKYSYk+5qrvx1hcrH4CzzbmoZ++Lc85Na9HHD8sguyvFe5XgjQ2e/0/FSjv6tiQ1E1h6FidanhR/hI5Ti+qe6nvWMEzs22lo0Mx2H8AAA",
    "avifSrcSet": "/images/menu/piata-0028--w480.avif 480w, /images/menu/piata-0028--w768.avif 768w, /images/menu/piata-0028--w1200.avif 1200w, /images/menu/piata-0028--w1600.avif 1600w",
    "webpSrcSet": "/images/menu/piata-0028--w480.webp 480w, /images/menu/piata-0028--w768.webp 768w, /images/menu/piata-0028--w1200.webp 1200w, /images/menu/piata-0028--w1600.webp 1600w"
  },
  "/images/menu/piata-0031.jpg": {
    "width": 1600,
    "height": 1200,
    "blurDataURL": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAABQAgCdASoQAAwAA4BaJbACdH8AFwD2/+eMLgAA/vaTRAqk16D4T+c+P3zHvKyTbgsDeMIKFpDtvUcL4Viu6O/LXtCQnSnzxFgEBtC//DfNfNhKIAAAAA==",
    "avifSrcSet": "/images/menu/piata-0031--w480.avif 480w, /images/menu/piata-0031--w768.avif 768w, /images/menu/piata-0031--w1200.avif 1200w, /images/menu/piata-0031--w1600.avif 1600w",
    "webpSrcSet": "/images/menu/piata-0031--w480.webp 480w, /images/menu/piata-0031--w768.webp 768w, /images/menu/piata-0031--w1200.webp 1200w, /images/menu/piata-0031--w1600.webp 1600w"
  },
  "/images/menu/yogurt-bowl.jpg": {
    "width": 1195,
    "height": 896,
    "blurDataURL": "data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAABQAgCdASoQAAwAA4BaJbACdAYuRTJLePXkrwAA/vS01bU0/eoCO8bPc+u2KURAoLP+s//Wh1NryXr1PqEobiRfTL9FdNZjoKL2L/giv1Am5KXpLbHFgtitcgNZWwVxE+tHbaPO9YU4kk8l8JMhGv7fy+LQUlu0v64D2yYGC24AAA==",
    "avifSrcSet": "/images/menu/yogurt-bowl--w480.avif 480w, /images/menu/yogurt-bowl--w768.avif 768w, /images/menu/yogurt-bowl--w1195.avif 1195w",
    "webpSrcSet": "/images/menu/yogurt-bowl--w480.webp 480w, /images/menu/yogurt-bowl--w768.webp 768w, /images/menu/yogurt-bowl--w1195.webp 1195w"
  },
  "/images/mess-philosophy-poster.jpg": {
    "width": 720,
    "height": 1280,
    "blurDataURL": "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAAAwBACdASoQABwAPu1iqU2ppaOiMAgBMB2JYwC7ACG0W+od2cu+wzHJFGAA/uji2OdLKdlV9ANrpHrIvtyyTcnop8VBtzmQW4uvBeCjl2xn35uSP8LsykPtpgez5WzNG7f2OO+eZjMkpmJgAAA=",
    "avifSrcSet": "/images/mess-philosophy-poster--w480.avif 480w, /images/mess-philosophy-poster--w720.avif 720w",
    "webpSrcSet": "/images/mess-philosophy-poster--w480.webp 480w, /images/mess-philosophy-poster--w720.webp 720w"
  },
  "/images/nutrition-tips.jpg": {
    "width": 1600,
    "height": 2420,
    "blurDataURL": "data:image/webp;base64,UklGRt4AAABXRUJQVlA4INIAAABQBQCdASoQABgAPu1iqU2ppaOiMAgBMB2JbACdMoR3IsB9gEmAzqA3VHQX/l4GMB2nLgAA/qXUW/X3FUV7XMP6hPPfqPCQcWAJvVJKfyEwairvXEYQ2tLHFF8zaE7b6q6omDuY6cBmY6mofcA2XVhEPlVpAAX5TKX5bgzfuRjZ1U7lMRSmXwHsoGDWLnmdZ9g4UUNcafV/WAzNjFWnfR6QOPbYw+vj9Fw0bbG9etMtF16tn12wl7iCL3x73PvSgXP5A5Dz4Zle+KfNmTBR/rwAAAA=",
    "avifSrcSet": "/images/nutrition-tips--w480.avif 480w, /images/nutrition-tips--w768.avif 768w, /images/nutrition-tips--w1200.avif 1200w, /images/nutrition-tips--w1600.avif 1600w",
    "webpSrcSet": "/images/nutrition-tips--w480.webp 480w, /images/nutrition-tips--w768.webp 768w, /images/nutrition-tips--w1200.webp 1200w, /images/nutrition-tips--w1600.webp 1600w"
  },
}

export function getImageManifestEntry(src: string): ImageManifestEntry | undefined {
  if (!src || typeof src !== 'string') return undefined
  const key = src.split('?')[0]
  return imageManifest[key]
}
