export const WORDMARK_STAGGER_MS = 80
export const WORDMARK_LETTER_DURATION_MS = 350
export const UNDERLINE_DURATION_MS = 300
export const LOADER_HOLD_MS = 350
export const CURTAIN_SLIDE_MS = 750

const WORDMARK_CHARS = 'M.E.S.S.'.length

const WORDMARK_FINISH_MS =
  (WORDMARK_CHARS - 1) * WORDMARK_STAGGER_MS + WORDMARK_LETTER_DURATION_MS
const UNDERLINE_FINISH_MS = WORDMARK_FINISH_MS + UNDERLINE_DURATION_MS
const HOLD_FINISH_MS = UNDERLINE_FINISH_MS + LOADER_HOLD_MS

export const LOADING_DURATION_MS = HOLD_FINISH_MS + CURTAIN_SLIDE_MS
