/**
 * Build-time responsive AVIF/WebP + LQIP manifest for static export.
 * Outputs sit beside originals: about-1.jpg → about-1--w768.avif
 */

import sharp from 'sharp'
import {
  readFileSync,
  writeFileSync,
  readdirSync,
  statSync,
  mkdirSync,
  existsSync,
} from 'fs'
import { join, relative, dirname, extname, basename } from 'path'
import { fileURLToPath } from 'url'
import { createHash } from 'crypto'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = join(__dirname, '..')
const IMAGES_ROOT = join(ROOT, 'public', 'images')
const MANIFEST_PATH = join(ROOT, 'lib', 'image-manifest.ts')
const WIDTHS = [480, 768, 1200, 1600]
const AVIF_QUALITY = 60
const WEBP_QUALITY = 81
const RASTER_EXT = new Set(['.jpg', '.jpeg', '.png', '.webp'])
const OUTPUT_RE = /--w\d+\.(avif|webp)$/i

function walk(dir, files = []) {
  for (const name of readdirSync(dir)) {
    const abs = join(dir, name)
    if (statSync(abs).isDirectory()) {
      walk(abs, files)
    } else {
      files.push(abs)
    }
  }
  return files
}

function publicPath(absFile) {
  return '/' + relative(join(ROOT, 'public'), absFile).split('\\').join('/')
}

function outputBase(absSource) {
  const dir = dirname(absSource)
  const ext = extname(absSource)
  const stem = basename(absSource, ext)
  return { dir, stem, ext: ext.toLowerCase() }
}

function hashFile(abs) {
  return createHash('md5').update(readFileSync(abs)).digest('hex')
}

function buildSrcSet(map) {
  return Object.entries(map)
    .sort(([a], [b]) => Number(a) - Number(b))
    .map(([w, url]) => `${url} ${w}w`)
    .join(', ')
}

async function processImage(absSource) {
  const { dir, stem } = outputBase(absSource)
  const publicSrc = publicPath(absSource)
  const meta = await sharp(absSource).metadata()
  const srcW = meta.width ?? 0
  const srcH = meta.height ?? 0
  if (!srcW || !srcH) return null

  const targetWidths = WIDTHS.filter((w) => w <= srcW)
  if (targetWidths.length === 0) targetWidths.push(srcW)

  const avifMap = {}
  const webpMap = {}

  for (const w of targetWidths) {
    const avifName = `${stem}--w${w}.avif`
    const webpName = `${stem}--w${w}.webp`
    const avifPath = join(dir, avifName)
    const webpPath = join(dir, webpName)

    const resized = await sharp(absSource)
      .resize({ width: w, withoutEnlargement: true })
      .toBuffer()

    await sharp(resized).avif({ quality: AVIF_QUALITY, effort: 4 }).toFile(avifPath)
    await sharp(resized).webp({ quality: WEBP_QUALITY }).toFile(webpPath)

    avifMap[w] = publicPath(avifPath)
    webpMap[w] = publicPath(webpPath)
  }

  const blurBuf = await sharp(absSource)
    .resize({ width: 16, withoutEnlargement: true })
    .webp({ quality: 40 })
    .toBuffer()
  const blurDataURL = `data:image/webp;base64,${blurBuf.toString('base64')}`

  return {
    key: publicSrc,
    entry: {
      width: srcW,
      height: srcH,
      blurDataURL,
      avifSrcSet: buildSrcSet(avifMap),
      webpSrcSet: buildSrcSet(webpMap),
    },
    sourceHash: hashFile(absSource),
  }
}

function readCache() {
  const cachePath = join(ROOT, '.cache', 'image-optimize.json')
  if (!existsSync(cachePath)) return {}
  try {
    return JSON.parse(readFileSync(cachePath, 'utf8'))
  } catch {
    return {}
  }
}

function writeCache(cache) {
  const cacheDir = join(ROOT, '.cache')
  if (!existsSync(cacheDir)) mkdirSync(cacheDir, { recursive: true })
  writeFileSync(join(cacheDir, 'image-optimize.json'), JSON.stringify(cache, null, 2))
}

function writeManifest(manifest) {
  const keys = Object.keys(manifest).sort()
  const body = keys
    .map((k) => `  ${JSON.stringify(k)}: ${JSON.stringify(manifest[k], null, 2).replace(/\n/g, '\n  ')},`)
    .join('\n')

  const ts = `/** Auto-generated by scripts/optimize-images.mjs — do not edit */\n\nexport type ImageManifestEntry = {\n  width: number\n  height: number\n  blurDataURL: string\n  avifSrcSet: string\n  webpSrcSet: string\n}\n\nexport const imageManifest: Record<string, ImageManifestEntry> = {\n${body}\n}\n\nexport function getImageManifestEntry(src: string): ImageManifestEntry | undefined {\n  if (!src || typeof src !== 'string') return undefined\n  const key = src.split('?')[0]\n  return imageManifest[key]\n}\n`

  writeFileSync(MANIFEST_PATH, ts)
}

async function main() {
  if (!existsSync(IMAGES_ROOT)) {
    writeManifest({})
    console.log('No public/images — wrote empty manifest')
    return
  }

  const cache = readCache()
  const manifest = {}
  const nextCache = {}
  const files = walk(IMAGES_ROOT).filter((abs) => {
    const ext = extname(abs).toLowerCase()
    if (!RASTER_EXT.has(ext)) return false
    if (OUTPUT_RE.test(basename(abs))) return false
    return true
  })

  let processed = 0
  let skipped = 0

  for (const abs of files) {
    const publicSrc = publicPath(abs)
    const sourceHash = hashFile(abs)
    const cached = cache[publicSrc]

    if (cached?.sourceHash === sourceHash && cached.entry) {
      manifest[publicSrc] = cached.entry
      nextCache[publicSrc] = { sourceHash, entry: cached.entry }
      skipped++
      continue
    }

    try {
      const result = await processImage(abs)
      if (!result) continue
      manifest[result.key] = result.entry
      nextCache[result.key] = { sourceHash: result.sourceHash, entry: result.entry }
      processed++
      if (processed % 10 === 0) console.log(`  … ${processed} optimized`)
    } catch (err) {
      console.warn(`Skip ${publicSrc}:`, err.message)
    }
  }

  writeCache(nextCache)
  writeManifest(manifest)
  console.log(`Image optimize done: ${processed} processed, ${skipped} cached, ${Object.keys(manifest).length} in manifest`)
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
